webpack.config.js
https://jira.dhis2.org/browse/DHIS2-3422
Required by https://github.com/dhis2/d2-ui/pull/246
=> Load ckeditor JS files used by interpretation panel

src/components/layers/basemaps/BasemapCard.js, src/components/layers/layers/LayerCard.js, src/components/layers/toolbar/LayerToolbar.js
From https://jira.dhis2.org/browse/DHIS2-4225
New position of visibility icon:
=> DHIS2-4225 - Move layer card visibility toggle from header to footer.

src/components/core/SelectField.js, src/components/core/__tests__/SelectField.spec.js, src/components/optionSet/OptionSetSelect.js
Wrapper component around MUI TextField supporting default styling,labels, error text, multiple select, and rendering select items from an array of objects.
=> SelectField

plugin.html
No changes to production code, just easier for testing.
=> Allow runtime selection of map ID and userOrgUnit ID in plugin.html

src/components/filter/FilterSelect.js, yarn.lock
Fixes: https://jira.dhis2.org/browse/DHIS2-4706
=> Support TRUE_ONLY value type in filter

package.json, yarn.lock
Partly fixes: https://jira.dhis2.org/browse/DHIS2-4482
Just a dependency upgrade of d2-ui-file-menu. The changes in devDependencies only seems to be reordering.
=> d2-ui-file-menu upgrade

src/components/edit/EventDialog.js, src/loaders/trackedEntityLoader.js
This PR fixes a problem with geometry types in TEI layer. Polygons have previously been stored wrong in DHIS2 backend, but this is no longer the case.
=> Geometry type fix for TEI layer

src/components/map/Layer.js, yarn.lock
Small fix to solve issue with the measurement tool: 
https://jira.dhis2.org/browse/DHIS2-4927
The fix was to lover the layer z-index from 600 to 590:
https://github.com/ljagis/leaflet-measure/issues/54
=> Lower layer z-index to solve issue with leaflet-measure

src/epics/favorites.js, src/util/api.js
Use the new URL parameters skipTranslations and skipSharing when saving map objects to avoid conflicts.
https://jira.dhis2.org/browse/DHIS2-4929
=> Avoid loosing latest translation and sharing settings

src/components/map/BoundaryLayer.js, src/components/map/EventLayer.js, src/components/map/FacilityLayer.js, src/components/map/Layer.js, src/components/map/ThematicLayer.js, src/components/map/TrackedEntityLayer.js, yarn.lock
This PR will only zoom/pan the map the first time a layer is added, and not on every update.
=> Keep map view on layer update

package.json, src/components/core/FontStyle.js, src/components/download/DownloadDialog.js, src/components/edit/LayerDialogStyles.js, src/components/interpretations/InterpretationsPanel.js, src/components/map/ContextMenu.js, src/components/map/Map.js, src/components/orgunits/OrgUnitDialog.js, yarn.lock
This PR fixes various issues:
- Upgrade GIS API with the lastes Google Maps API version
- Convert font with 'px' size to integer
- Use className rather than inline styles 
- Close download dialog on image download
- Output download error to console (temporarily)
- Avoid horisontal scroll in layer dialogs
- Context menu style fixes (align icon and labels) 
- Fix map control styles (due to new global stylesheet from ui/core)
=> Style and bug fixes

src/components/edit/LayerDialogStyles.js
=> Fix flexbox columns in IE

i18n/en.pot, src/components/core/FontStyle.js, src/components/edit/BoundaryDialog.js, src/components/edit/FacilityDialog.js, src/components/edit/thematic/ThematicDialog.js, src/components/layers/layers/LayerCard.js, src/components/map/Map.js, src/components/orgunits/OrgUnitLevelSelect.js, src/util/analytics.js
This PR fixes minor bugs and style issues: 
- Improved styling og event popups
- Align font style buttons
- Increased margin in org unit dialog
- Remove edit button for external layers (nothing to edit) 
- Fix in function excluding data types from list of data elements
=> Bug and styles fixes

src/components/app/App.css, src/components/app/App.js, src/components/layers/legend/Legend.js, src/components/map/EventLayer.js
Minor styling fixes:
- Scrollbar styles 
- Legend unit in bold
- Remove line breaks from event popups HTML
=> Minor styling fixes

src/components/dataElement/DataElementGroupSelect.js, src/components/dataElement/DataElementOperandSelect.js, src/components/dataElement/DataElementSelect.js, src/components/dataItem/EventDataItemSelect.js, src/components/dataSets/DataSetsSelect.js, src/components/edit/thematic/ThematicDialog.js, src/components/edit/thematic/ValueTypeSelect.js, src/components/program/ProgramIndicatorSelect.js
Issue: https://jira.dhis2.org/browse/DHIS2-5366
=> Show data element operand when loading a saved map

plugin.html, webpack.config.js
The issue was that `plugin.html` no longer included `polyfill.min.js`
This fixes the functionality of `plugin.html`.  However, the userOrgUnit filtering appears to be broken (and it appears to be a backend bug?)
=> Fix plugin.html

package.json, yarn.lock
Update Cypress dependency to fix an issue with end-to-end tests.
CC @jenniferarnesen, might need to do this in DV also
=> chore: update cypress dependency

package.json, src/loaders/trackedEntityLoader.js
Fixes an import reference resulting in this bug: 
https://jira.dhis2.org/browse/DHIS2-6368
=> Import reference fix

plugin.html, src/util/favorites.js
Fixes an issue when map config sent from the dashboard has external layer config in a string.
=> External layer bug fix

src/components/layers/basemaps/Basemap.js
Fixes: https://jira.dhis2.org/browse/DHIS2-6679
Smallest PR ever?
=> fix: basemap name cut off

package.json, yarn.lock
FIxes [DHIS2-6667](https://jira.dhis2.org/browse/DHIS2-6667), content of fix was merged in dhis2/gis-api#54
=> fix: upgrade gis-api to 32.0.21

src/components/layers/legend/LegendItem.js
Fixes [DHIS2-6571](https://jira.dhis2.org/browse/DHIS2-6571)
=> fix: set width and height for line legend items in ff

src/components/layers/basemaps/BasemapCard.js, src/components/layers/layers/LayerCard.js
Solves "the text should should show near to the icon(arrow icon)": https://jira.dhis2.org/browse/DHIS2-6681
The tooltip is placed closer to the button, but not on top as it will be hidded by the cursor.
=> Adjust tooltip position

src/loaders/trackedEntityLoader.js, src/util/favorites.js
Fixes #130 
Fixes [DHIS2-6746](https://jira.dhis2.org/browse/DHIS2-6746)
Add support for saving and loading TEI layer relationship configuration through the JSON-encoded `config` property of the MapView
=> feat: support saving and loading of TEI relationship maps

src/loaders/eventLoader.js
This catches any error that occurs while loading a layer and displays an alert.  In the special case of 403 and 409 (permissions) errors we show a special "Access denied" error.  The layer is still added, so it can be edited or removed manually.
I don't love the mutation of the config object but it is what it is for now.
=> fix: show an alert when a load error occurs

src/components/edit/EarthEngineDialog.js, src/epics/earthEngine.js, src/loaders/earthEngineLoader.js, src/reducers/layers.js
Backport of #140 to DHIS2 Maps 2.31
Fixes: https://jira.dhis2.org/browse/DHIS2-6993
=> fix: new earth engine temperature layer for 2.31

src/components/edit/EarthEngineDialog.js, src/epics/earthEngine.js, src/loaders/earthEngineLoader.js, src/reducers/layers.js
Backport of https://github.com/dhis2/maps-app/pull/140/ to DHIS2 Maps 2.30
Fixes: https://jira.dhis2.org/browse/DHIS2-6993
=> fix: new earth engine temperature layer for 2.30

package.json, yarn.lock
Update interpretations package.
Update includes removal of "apply" button on new interpretations.
Ticket [DHIS2-6250](https://jira.dhis2.org/browse/DHIS2-6250)
=> chore: update interpretations panel [DHIS2-6250]

i18n/en.pot, src/loaders/eventLoader.js
[DHIS2-6898](https://jira.dhis2.org/browse/DHIS2-6898) (backport of [DHIS2-6042](https://jira.dhis2.org/browse/DHIS2-6042) which is in 2.32.0)
=> fix: show an alert when an error occurs while adding a layer (backport v31)

i18n/en.pot, src/loaders/eventLoader.js
DHIS2-6898 (backport of DHIS2-6042 which is in 2.32.0)
=> fix: (v30) show an alert when a load error occurs

i18n/en.pot, package.json, src/components/earthengine/Collection.js, src/components/map/Layer.js, src/loaders/earthEngineLoader.js, yarn.lock
Fixes: 
https://jira.dhis2.org/browse/DHIS2-7344
https://jira.dhis2.org/browse/DHIS2-7345
=> fix: bug fixes for Earth Engine layers

src/reducers/layerEdit.js
This fixes [DHIS2-6829](https://jira.dhis2.org/browse/DHIS2-6829), should try to get this one in today for 2.33 hard freeze!
=> fix: clear conflicting settings when changing TEI type

.travis.yml, src/components/map/MapView.js, src/components/plugin/Plugin.js
Makes sure all maps are updated when split view items on dashboards are resized.
=> Resize fix for dashboard maps

.travis.yml, src/components/app/App.css, src/components/map/EventLayer.js, src/util/helpers.js
2.32 backport of: https://jira.dhis2.org/browse/DHIS2-6394
=> fix: format coordinate values in event popups - 2.32 backport

package.json, src/components/map/EventLayer.js, yarn.lock
Fixes: https://jira.dhis2.org/browse/DHIS2-7753
=> Server cluster spiderify fix - 2.31 backport

package.json, src/components/map/EventLayer.js, src/components/orgunits/OrgUnitDialog.js, src/loaders/boundaryLoader.js, src/loaders/trackedEntityLoader.js, src/util/analyticalObject.js, src/util/dom-to-image.js
=> fix: boundary layers, org unit dialog and event popups

src/components/filter/FilterSelect.js
Fixes: https://jira.dhis2.org/browse/DHIS2-7867
The issue was fixed by using the same style for text and date fields.
=> fix: avoid overflow of filter date fields

i18n/en.pot, package.json, src/components/classification/NumericLegendStyle.js, src/components/dimensions/DimensionFilterRow.js, src/components/edit/thematic/ThematicDialog.js, src/components/filter/FilterSelect.js, src/components/map/ThematicLayer.js, src/components/periods/PeriodSelect.js, src/loaders/thematicLoader.js, src/loaders/trackedEntityLoader.js, src/util/analyticalObject.js, src/util/dom-to-image.js
2.33 backport of #262, #263, #264, #265.
=> Backport fixes v33

i18n/en.pot, package.json, src/components/filter/FilterSelect.js, src/components/periods/PeriodSelect.js
Backport #262 and #264 to 2.31.
=> fix: backport #262 and #264 to 2.31

package.json, src/components/map/Map.js, src/components/map/MapItem.js, yarn.lock
Only render layers when map is ready (style is ready for Maps GL).
=> fix: map state

package.json, src/components/map/Map.js, src/components/map/MapApi.js, src/constants/mapControls.js, yarn.lock
This small PR adds support for a fullscreen map control, and an additional check if the map controls are supported by the mapping API in use.
=> feat: fullscreen map control

package.json, src/map.js
=> fix: authentication header

cypress/integration/layers/thematiclayer.spec.js, package.json, src/components/map/Map.js, src/components/map/MapApi.js, src/components/map/MapContainer.js, src/components/map/TrackedEntityLayer.js, src/components/plugin/Legend.js, src/components/plugin/Plugin.js, src/constants/mapControls.js, src/epics/earthEngine.js, src/loaders/trackedEntityLoader.js, yarn.lock
This PR will trigger a map resize when one of the panels (layers, interpratations, data table) are expanded or collapsed. 
Also included in this PR:
- Fullscreen control for plugin maps (Dashboard)
- Class names to plugin markup. 
- Load Earth Engine API on demand if not already present. This is how it works with maps-gl.
- Popup fix for TEI layers.
- Have TEI ids in feature properties (Mapbox GL JS only support integer ids on feature)
=> fix: map resize on panel change

package.json, src/app.js, src/components/app/App.js, src/components/map/Popup.css, src/components/plugin/ContextMenu.css, src/components/plugin/ContextMenu.js, src/map.js, yarn.lock
This PR upgrades to v32 of the web api + minor class name change.
=> fix: upgrade to v34 of backend api

src/loaders/facilityLoader.js
Fixes: https://jira.dhis2.org/browse/DHIS2-8474
Selecting an org unit level that don't align with the selected org units in the tree is not valid: 
Previously we didn't catch the error from the Web API, with this PR we show the error returned to the user:
This selection will not be possible in the new org unit selection in the making.
=> fix: catch error for invalid org unit selection for facility layer (DHIS2-8474)

package.json, yarn.lock
Fixes: https://jira.dhis2.org/browse/DHIS2-8496
Related maps-gl PR: https://github.com/dhis2/maps-gl/pull/69
=> fix: latest maps-gl

package.json, src/components/edit/thematic/ThematicDialog.js
Backport of [DHIS2-8485](https://jira.dhis2.org/browse/DHIS2-8485) to 2.34.0. 
Original PR: #498
=> fix: backport of DHIS2-8485

src/components/edit/thematic/ThematicDialog.js, src/components/filter/FilterSelect.js, src/components/map/ThematicLayer.js, src/components/plugin/Plugin.js, src/loaders/facilityLoader.js, src/util/analyticalObject.js, src/util/favorites.js
2.33 backports of: 
- [7089](https://jira.dhis2.org/browse/DHIS2-7089) | #586 | https://github.com/dhis2/maps-app/pull/620/commits/0fafcbf2cd6001c2da49d7ac08099822ca799c9b | Filtering on data element option with "Not one of" gives error
- [7924](https://jira.dhis2.org/browse/DHIS2-7924) | #585 | https://github.com/dhis2/maps-app/pull/620/commits/2b632465cca39dfeb1929d4695b7f75e4df96a8e | Editing map layer with OU grandchildren selected breaks map 
- [8176](https://jira.dhis2.org/browse/DHIS2-8176) | #584 | https://github.com/dhis2/maps-app/pull/620/commits/26effce5b53046705736a5f0438d5c896ca38415 | Org Units with no data displaying for periods in Maps timeline
- [8474](https://jira.dhis2.org/browse/DHIS2-8474) | #495 | https://github.com/dhis2/maps-app/pull/620/commits/109d65bc34d4986e3e67 …
=> Backports to 2.33.4

src/components/edit/LayerEdit.js, src/util/analytics.js
=> fix: rename import v34

i18n/en.pot, src/components/classification/Classification.js, src/components/edit/EarthEngineDialog.js, src/components/edit/LayerEdit.js, src/components/edit/TrackedEntityDialog.js, src/components/edit/thematic/AggregationTypeSelect.js, src/components/layers/layers/LayerCard.js, src/components/orgunits/OrgUnitTree.js, src/components/orgunits/SelectedOrgUnits.js, src/components/orgunits/UserOrgUnitsSelect.js, src/components/periods/PeriodTypeSelect.js, src/components/periods/RelativePeriodSelect.js, src/components/periods/RenderingStrategy.js, src/constants/aggregationTypes.js, src/constants/layers.js, src/constants/periods.js, src/epics/favorites.js, src/epics/layers.js, src/loaders/earthEngineLoader.js, src/loaders/thematicLoader.js, src/reducers/layers.js, src/util/analytics.js
Backport to 2.33.4 of: https://jira.dhis2.org/browse/DHIS2-8658
Original PR: #590 
A wrong import was found in the original PR, which is fixed in this PR and in #630
=> fix: make all strings translatable 2.33 (DHIS2-8658)

i18n/en.pot, src/components/classification/Classification.js, src/components/edit/EarthEngineDialog.js, src/components/edit/LayerEdit.js, src/components/edit/TrackedEntityDialog.js, src/components/edit/thematic/AggregationTypeSelect.js, src/components/layers/layers/LayerCard.js, src/components/orgunits/OrgUnitTree.js, src/components/orgunits/SelectedOrgUnits.js, src/components/orgunits/UserOrgUnitsSelect.js, src/components/periods/PeriodTypeSelect.js, src/components/periods/RelativePeriodSelect.js, src/constants/aggregationTypes.js, src/constants/layers.js, src/constants/periods.js, src/epics/favorites.js, src/epics/layers.js, src/loaders/earthEngineLoader.js, src/loaders/thematicLoader.js, src/reducers/layers.js, src/util/analytics.js
Backport to 2.33.4 of: https://jira.dhis2.org/browse/DHIS2-8658
Original PR: #590
A wrong import was found in the original PR, which is fixed in this PR and in #630
=> fix: make all strings translatable 2.32 (DHIS2-8658)

i18n/en.pot, package.json, src/components/core/FontStyle.js, src/components/edit/LayerEdit.js, src/components/layers/basemaps/Basemap.js, src/components/layers/basemaps/BasemapCard.js, src/components/map/mapLocale.js, src/constants/basemaps.js, src/map.js, src/reducers/basemaps.js, src/reducers/map.js
=> fix: add missing translations - 2.34 backport (DHIS2-8658)

i18n/en.pot, package.json, src/components/core/FontStyle.js, src/components/edit/LayerEdit.js, src/components/layers/basemaps/Basemap.js, src/components/layers/basemaps/BasemapCard.js, src/constants/basemaps.js, src/map.js, src/reducers/basemaps.js, src/reducers/map.js
=> fix: add missing translations - 2.33 backport (DHIS2-8658)

i18n/en.pot, src/components/layers/basemaps/BasemapCard.js, src/constants/basemaps.js
=> fix: add missing translations - 2.32 backport (DHIS2-8658)

package.json, src/util/favorites.js, src/util/helpers.js
2.32 backport of #765
Fixes: https://jira.dhis2.org/browse/DHIS2-8840
=> fix: persist publicAccess on map save - 2.32 backport (DHIS2-8840)

package.json, src/util/favorites.js, src/util/helpers.js
2.33 backport of #765
Fixes: https://jira.dhis2.org/browse/DHIS2-8840
=> fix: persist publicAccess on map save - 2.33 backport (DHIS2-8840)

package.json, src/util/favorites.js, src/util/helpers.js
2.34 backport of #765 
Fixes: https://jira.dhis2.org/browse/DHIS2-8840
=> fix: persist publicAccess on map save - 2.34 backport (DHIS2-8840)

package.json, src/components/app/App.js, webpack.config.js, yarn.lock
Backport of #781 and parts of #405 to be able to upgrade headerbar to support translations.
=> fix: upgrade headerbar to support translations

package.json, src/components/app/App.js, webpack.config.js, yarn.lock
2.32 backport of #781 and parts of #405 to be able to upgrade headerbar to support translations.
=> fix: upgrade headerbar to support translations - 2.32 backport

package.json, src/components/app/App.js
=> fix: set proper base url for production [32]

i18n/en.pot, package.json, src/components/datatable/DataTable.js, src/components/layers/legend/Legend.js, yarn.lock
=> fix: add missing translation strings

src/util/favorites.js, src/util/helpers.js
=> fix: keep created and lastUpdated map properties v32 (DHIS2-9060)

src/util/favorites.js, src/util/helpers.js
=> fix: keep created and lastUpdated map properties v33 (DHIS2-9060)

src/util/favorites.js, src/util/helpers.js
=> fix: keep created and lastUpdated map properties v34 (DHIS2-9060)

src/components/edit/LayerEdit.js, src/components/edit/trackedEntity/ProgramStatusSelect.js, src/components/edit/trackedEntity/TrackedEntityDialog.js, src/components/layers/legend/Legend.js, src/constants/programStatuses.js, src/loaders/eventLoader.js, src/loaders/facilityLoader.js, src/loaders/trackedEntityLoader.js, src/reducers/layerEdit.js
Fixes: https://jira.dhis2.org/browse/DHIS2-8166
This PR includes a separate ProgramStatusSelect component which allows "All" to be selected: 
"All" is new default value (previously "Active"). 
The selected program status is shown in the legend if not "All":
=> feat: allow all program statuses to be selected for TEI layers (DHIS2-8166)

package.json, yarn.lock
Fixes: https://jira.dhis2.org/browse/DHIS2-9357
Fixes app crash when visibility is toggled for TEI layers
=> fix: visibility toggle for TEI layers

package.json, src/components/map/MapItem.js, src/map.js
Backport of: https://github.com/dhis2/maps-app/pull/995
=> fix: map plugin style handling 2.34 backport (DHIS2-9315)

i18n/en.pot, package.json, src/components/classification/LegendSetSelect.js, src/components/classification/NumericLegendStyle.js, src/components/edit/thematic/ThematicDialog.js
DHIS2 Maps backport of #985 to 2.34.
=> fix: require legend set selection 2.34 backport (DHIS2-9314)

package.json, src/components/orgunits/OrgUnitLevelSelect.js, yarn.lock
2.34 backport of #984
WIP until properly tested locally (dhis2-core is not building)
=> fix: allow uid to idenitify org unit levels - 2.34 (TECH-427)

i18n/en.pot, package.json, src/components/classification/LegendSetSelect.js, src/components/classification/NumericLegendStyle.js, src/components/edit/thematic/ThematicDialog.js
=> fix: require legend set selection 2.32 backport (DHIS2-9314)

package.json, src/components/map/Map.js, src/components/map/MapItem.js, src/components/map/MapView.js, src/components/map/SplitView.js, yarn.lock
=> fix: split view map scroll zoom handling

src/components/map/ThematicLayer.js
Issue: https://jira.dhis2.org/browse/DHIS2-9510
=> fix: avoid app crash if missing period id (DHIS2-9510)

package.json, src/components/edit/event/EventDialog.js
=> fix: start/end dates backport

package.json, src/components/map/MapContainer.js
Fixes: https://jira.dhis2.org/browse/DHIS2-9522
=> fix: trigger map redraw when data table is dragged (DHIS2-9522)

package.json, yarn.lock
Fixes: https://jira.dhis2.org/browse/DHIS2-9570
=> fix: maps-gl upgrade with style fix

src/components/periods/StartEndDates.js
=> fix: only remove date field if undefined

package.json, src/map.js
2.35.0 backport of #1083
Fixes: https://jira.dhis2.org/browse/DHIS2-9593
Will not be merged before the backport is approved by RCB.
=> fix: unique class name prefix for each map plugin item (DHIS2-9593, 2.35.0 backport)

package.json, src/map.js
v34 backport of #1083
Fixes: https://jira.dhis2.org/browse/DHIS2-9593
=> fix: unique class name prefix for each map plugin item (DHIS2-9593, v34 backport)

src/components/edit/trackedEntity/TrackedEntityDialog.js, src/loaders/trackedEntityLoader.js, src/util/teiRelationshipsParser.js
=> Remove functionality to show TEI relationships outside program (DHIS2-9634, 2.35.0 backport)

src/components/edit/thematic/ThematicDialog.js
Fixes: https://jira.dhis2.org/browse/DHIS2-9733
=> fix: start/end dates check

src/components/edit/thematic/ThematicDialog.js
=> fix: start/end dates check (2.35.0 backport)

src/components/app/FileMenu.js, src/components/app/styles/AppMenu.module.css, src/components/app/styles/FileMenu.module.css
This PR makes sure all app menu items are aligned and have the same color - grey900
After this PR:
Before:
=> fix: app menu style

src/components/map/layers/Alert.js, src/components/map/layers/earthEngine/EarthEngineLayer.js, src/components/map/layers/styles/Alert.module.css
This PR will catch and show errors from the Earth Engine API:
=> fix: catch EE API errors

src/loaders/earthEngineLoader.js, src/util/favorites.js
This PR persist all EE layer options when the map is saved (including layer opacity).
When layer was created: 
Identical to loaded layer: 
When layer was created: 
Identical to loaded layer: 
When layer was created: 
Identical to loaded layer: 
When layer was created: 
Identical to loaded layer: 
When layer was created: 
Identical to loaded layer:
=> fix: persist ee layer options on save

package.json, yarn.lock
https://github.com/dhis2/maps-gl/pull/298
=> fix: maps-gl dependecy upgrade to fix opacity crash bug

package.json, src/components/periods/PeriodSelect.js, src/reducers/layerEdit.js, yarn.lock
This PR fixes: 
- Removes an invalid proptype check resulting in a console warning
- Thematic layer: Don't reset number of `classes` and `color scale` when classification is switched between `equal intervals` and `equal counts`
- Upgrade `@dhis2/analytics` and `@dhis2/ui` dependencies. Maps use `FileMenu` and `DimensionsPanel` from `@dhis2/analytics`. I've tested that both these components work fine locally.
=> fix: various minor bugs

src/map.js
Fixes: https://jira.dhis2.org/browse/DHIS2-10684
`patch/2.36.0` backport of #1575
=> fix: switch from const to function for map plugin

src/util/styleByDataItem.js
Fixes: https://jira.dhis2.org/browse/DHIS2-10736
Before:
=> fix: use name to identify style by data item

src/constants/earthEngine.js
Fixes: https://jira.dhis2.org/browse/DHIS2-10819
=> fix: upgrade WorldPop population dataset (DHIS2-10817)

package.json, src/components/datatable/DataTable.js
=> fix: show color in data table for thematic layers (DHIS2-10872)

src/components/edit/BoundaryDialog.js, src/components/edit/styles/LayerDialog.module.css, src/components/edit/trackedEntity/TrackedEntityDialog.js, src/components/filter/FilterSelect.js, src/components/filter/styles/FilterSelect.module.css, src/components/layers/download/styles/EventDownloadInputs.module.css
Fixes: https://jira.dhis2.org/browse/DHIS2-10873
This PR fixes various alignment issues in the layer and download dialogs: 
Before: 
---
Before: 
---
Before: 
---
Before:
=> fix: style issues after upgrading from Material UI to DHIS2 UI (DHIS2-10873)

webpack.config.js
2.36.0 backport of #1642 (approved by RBC)
Fixes: https://jira.dhis2.org/browse/DHIS2-10882
=> fix: remove slash from base url in production (DHIS2-10882)

src/constants/layers.js
=> fix: reduce event page size to 100k

package.json, yarn.lock
Fixes: https://jira.dhis2.org/browse/DHIS2-10889
https://github.com/dhis2/maps-gl/pull/314
=> fix: upgrade maps-gl to improve donut cluster rendering (DHIS2-10889) 

i18n/en.pot, src/constants/periods.js
Implements https://jira.dhis2.org/browse/DHIS2-7029
Adds last 10 years as a relative period.
=> feat: add last 10 years relative period (DHIS2-7029)

src/util/styleByDataItem.js
2.35 backport of #1591
Fixes: https://jira.dhis2.org/browse/DHIS2-10736
=> fix: use name to identify style by data item (DHIS2-10736, 2.35 backport)

package.json, src/components/download/DownloadDialog.js, src/components/map/MapContainer.js
patch/2.34.6 backport of #1712 / #1764 
Fixes: https://jira.dhis2.org/browse/DHIS2-11143
=> fix: exclude attribution toggle button from download (#1764)

package.json, src/util/infrastructural.js
Fixes: https://jira.dhis2.org/browse/DHIS2-11433
2.36 backport of #1788
=> fix: period type in uppercase (DHIS2-11433)

package.json, src/components/map/layers/Layer.js, src/components/map/layers/ThematicLayer.js, yarn.lock
This PR removes code that is not needed when the issue was fixed in https://github.com/dhis2/maps-gl/pull/398
=> fix: always open popup with single click

package.json, yarn.lock
This PR upgrades the d2-ui-x and @dhis2/analytics dependencies.
=> chore: d2-ui dependency upgrades

src/reducers/layerEdit.js
Fixes: https://jira.dhis2.org/browse/DHIS2-11920
2.36 backport of #1897
=> fix: remove style data item on program change (DHIS2-11920, 2.36 backport)

package.json
Will include commit https://github.com/dhis2/maps-app/commit/dbd4a1ca328249ef5297c42d403b4fee42d98cb5
=> fix: increase patch version in package.json

cypress/integration/layers/thematiclayer.cy.js, package.json, yarn.lock
Run earth engine operations in a Shared Worker:
https://github.com/dhis2/maps-gl/pull/427
=> fix: maps-gl upgrade with shared ee worker

cypress/integration/plugin.cy.js, public/plugin.html, src/map.js
Add 3 spans to plugin.html that can be checked by the cypress plugin tests (the map itself can't be checked since it is drawn on a canvas element).
=> chore: enable plugin cypress tests

.github/workflows/dhis2-verify-app.yml, cypress/elements/basemap_card.js, cypress/elements/file_menu.js, cypress/integration/basemaps.cy.js, cypress/integration/filemenu.cy.js, cypress/integration/plugin.cy.js, cypress/integration/systemsettings.cy.js
Some tests still fail regularly on CI while they pass when run locally. I was unable to fix all the tests, so a few had to be disabled for now.
=> fix: modify or fix flaky cypress tests

src/hooks/useBasemapConfig.js
Fixes: https://jira.dhis2.org/browse/DHIS2-12463
Might be cleaner ways to solve it :-)
=> fix: external basemap opacity (DHIS2-12463)

i18n/en.pot, src/components/map/layers/earthEngine/EarthEngineLayer.js
Fixes: https://jira.dhis2.org/browse/DHIS2-12506
Related maps-gl PR: https://github.com/dhis2/maps-gl/pull/433
=> fix: pass translated "no value" label for Earth Engine layers (DHIS2-12506)

i18n/en.pot, src/constants/earthEngine.js
2.37 backport of https://github.com/dhis2/maps-app/pull/2030
=> fix: use male/female instead of men/women, 2.37 backport

i18n/en.pot, src/constants/earthEngine.js
=> fix: use male/female instead of men/women, 2.36 backport 

package.json, yarn.lock
Fixes:  https://jira.dhis2.org/browse/DHIS2-12583
Approved in: https://github.com/dhis2/maps-gl/pull/436
=> fix: make sure map is present before removing layers and source (DHIS2-12583)

src/loaders/facilityLoader.js, src/util/orgUnits.js
Fixes for facility layer in 2.37: https://jira.dhis2.org/browse/DHIS2-12504
2.37 backport of: https://github.com/dhis2/maps-app/pull/2043
=> fix: improved error handling for facility layers (DHIS2-12504, 2.37 backport)

src/components/map/layers/ThematicLayer.js, src/constants/layers.js, src/loaders/thematicLoader.js, src/util/orgUnits.js
This PR will add catchment areas support for thematic layers. 
Partly fixes: https://jira.dhis2.org/browse/DHIS2-11969
If a catchment area exist it will be styled according to the value. The org unit point will show as a black dot. 
After this PR:
=> feat: catchment areas for thematic layers (DHIS2-11969)

i18n/en.pot, src/loaders/earthEngineLoader.js, src/loaders/facilityLoader.js, src/loaders/orgUnitLoader.js, src/loaders/thematicLoader.js
This PR will unify no coordinate warnings across facility, thematic and earth engine layers: 
**Facility layer**: no facility coordinates found
**Facility layer**: no catchment area coordinates found
**Facility layer**: no facility or catchment area coordinates found
**Org unit layer**: no org unit coordinates found
**Org unit layer**: no catchment area coordinates found
**Org unit layer**: no org uni or catchment area coordinates found
**EE layer**: no org unit coordinates found
**EE layer**: no catchment area coordinates found
Earth Engine layer will not show two warnings at the same time - as we show one or the other.
=> fix: no coordinates warnings

src/components/datatable/DataTable.js
Fixes: https://jira.dhis2.org/browse/DHIS2-12800
=> fix: close data table if no data (DHIS2-12800)

package.json, yarn.lock
Use latest maps-gl in DHIS2 Maps 2.37. 
Includes fix for: https://jira.dhis2.org/browse/DHIS2-12196
=> fix: maps-gl upgrade v37 (DHIS2-12196)

src/loaders/orgUnitLoader.js
Fixes for 2.37: https://jira.dhis2.org/browse/DHIS2-12504
2.37 backport of: https://github.com/dhis2/maps-app/pull/2096
=> fix: show error when org unit selection is invalid (DHIS2-12504)

i18n/en.pot, src/components/download/DownloadDialog.js, src/components/legend/styles/LegendItem.module.css
2.36 backport of: https://github.com/dhis2/maps-app/pull/2105
=> fix: improved map download style (DHIS2-12861, DHIS2-12862, 2.36 backport) 

src/components/app/FileMenu.js
This fixes the breaking change in analytics.
**Requires**: https://github.com/dhis2/analytics/pull/1114
=> fix: remove d2 and pass currentUser to FileMenu

src/components/map/layers/Layer.js, src/loaders/thematicLoader.js, src/reducers/map.js
This PR fixes issues with drill down/up for split view maps: https://jira.dhis2.org/browse/DHIS2-13574
After this PR:
=> fix: drill down/up for split view maps (DHIS2-13574)

src/components/map/layers/Layer.js, src/loaders/thematicLoader.js, src/reducers/map.js
2.38 backport of https://github.com/dhis2/maps-app/pull/2239
=> fix: drill down/up for split view maps (DHIS2-13574, 2.38 backport)

src/components/map/SplitView.js
This PR refactors SplitView into a function component. 
The component still renders as before:
=> chore: split view as functional component

.github/workflows/dhis2-verify-app.yml, i18n/en.pot, package.json, src/components/edit/earthEngine/BandSelect.js, src/components/map/layers/earthEngine/EarthEngineLayer.js, src/constants/earthEngine.js, yarn.lock
Fixes for 2.38: https://dhis2.atlassian.net/browse/DHIS2-13689
2.38 backport of https://github.com/dhis2/maps-app/pull/2281
=> fix: use tileScale to avoid ee aggregation timeout (DHIS2-13689, 2.38 backport)

package.json, src/components/map/layers/BasemapLayer.js, yarn.lock
Depends on: https://github.com/dhis2/maps-gl/pull/511
=> fix: simplified basemap handling

src/components/app/FileMenu.js, src/components/layers/overlays/OverlayCard.js, src/components/map/layers/BasemapLayer.js, src/constants/alerts.js
Suggestion to reduce some useAlert boilerplate code.
=> chore: reduce boilerplate code for useAlert

i18n/en.pot, src/components/map/layers/EventPopup.js
=> chore: useDataQuery in EventPopup

src/components/orgunits/OrgUnitFieldSelect.js, src/util/orgUnits.js
useDataEngine user instead of useDataQuery, due to 2 filter params
=> chore: useDataEngine in OrgUnitFieldSelect

config/testContext.js, config/testSetup.js
=> chore: fix failing jest tests

src/util/favorites.js, src/util/helpers.js
This PR will make sure map description is saved and retrieved from the database. 
Fixes: https://dhis2.atlassian.net/browse/DHIS2-14630
=> fix: save and retrieve map description (DHIS2-14630)

src/util/favorites.js, src/util/helpers.js
This PR will make sure map description is saved and retrieved from the database.
2.37 backport of https://github.com/dhis2/maps-app/pull/2470
Fixes: https://dhis2.atlassian.net/browse/DHIS2-14630
=> fix: save and retrieve map description (DHIS2-14630, 2.37 backport)

src/util/favorites.js, src/util/helpers.js
This PR will make sure map description is saved and retrieved from the database.
2.38 backport of https://github.com/dhis2/maps-app/pull/2470
Fixes: https://dhis2.atlassian.net/browse/DHIS2-14630
=> fix: save and retrieve map description (DHIS2-14630, 2.38 backport)

src/util/favorites.js, src/util/helpers.js
This PR will make sure map description is saved and retrieved from the database.
2.39 backport of https://github.com/dhis2/maps-app/pull/2470
Fixes: https://dhis2.atlassian.net/browse/DHIS2-14630
=> fix: save and retrieve map description (DHIS2-14630, 2.39 backport)

package.json, yarn.lock
Upgrade @dhis2/maps-gl to include https://github.com/dhis2/maps-gl/pull/535
Fixes: https://dhis2.atlassian.net/browse/DHIS2-14928
=> fix: toggle visibility for donut cluster (DHIS2-14928)

package.json, yarn.lock
=> fix: upgrade to latest analytics

package.json, yarn.lock
A part of [DHIS2-12937](https://dhis2.atlassian.net/browse/DHIS2-12937)
[DHIS2-12937]: https://dhis2.atlassian.net/browse/DHIS2-12937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(deps): bump deps for headerbar connection status [DHIS2-12937]

src/components/plugin/ContextMenu.js, src/components/plugin/Map.js
Also moved the hook to the component it is actually used in
=> fix: useDisconnectionStatus instead of useOnlineStatus

package.json, src/components/loaders/LayersLoader.js, yarn.lock
Fixes: https://dhis2.atlassian.net/browse/DHIS2-14969
Some checks were missing, causing infinite re-rendering when opening the Data Table.
=> fix: add checks to avoid Data Table crash for Event layers [patch/2.40.0] [DHIS2-14969]

src/components/map/layers/Layer.js
2.38 backport of https://github.com/dhis2/maps-app/pull/2705
Fixes for 2.38: https://dhis2.atlassian.net/browse/DHIS2-15439
=> fix: keep layer visibility when period is changed (DHIS2-15439, v38 backport)

src/components/edit/thematic/ThematicDialog.js
2.38 backport of https://github.com/dhis2/maps-app/pull/2703
Fixes for 2.38: https://dhis2.atlassian.net/browse/DHIS2-15435
=> fix: set rendering strategy to single if not relative period (DHIS2-15435, v38 backport)

src/components/edit/thematic/ThematicDialog.js
2.39 backport of https://github.com/dhis2/maps-app/pull/2703
Fixes for 2.39: https://dhis2.atlassian.net/browse/DHIS2-15435
=> fix: set rendering strategy to single if not relative period (DHIS2-15435, v39 backport)

src/components/map/layers/Layer.js
2.39 backport of https://github.com/dhis2/maps-app/pull/2705
Fixes for 2.39: https://dhis2.atlassian.net/browse/DHIS2-15439
=> fix: keep layer visibility when period is changed (DHIS2-15439, v39 backport)

cypress/integration/interpretations.cy.js, src/components/interpretations/InterpretationMap.js
Fixes: https://dhis2.atlassian.net/browse/DHIS2-15788
The issue was solved by adding the default basemap logic to the interpretation map.
After this PR:
With a different default basemap from system settings:
=> fix: set default basemap for interpretation map (DHIS2-15788)

src/components/layers/overlays/OverlayCard.js
Fixes https://dhis2.atlassian.net/browse/DHIS2-15794
https://github.com/dhis2/maps-app/assets/6113918/b8c20aee-1221-4dfe-8268-07b98b9a47fc
=> fix: open as chart in new tab to prevent user losing their work (DHIS2-15794)

.github/workflows/dhis2-verify-app.yml, cypress.config.js, jest.config.js, package.json, yarn.lock
Two changes in this PR:
1. sets up the configuration needed to send test results to the report portal.
2. use the workflow in the dhis2/workflows repo instead of the temporary one in line-listing (dhis2-verify-app.yml)
=> chore: set up report portal

.github/workflows/dhis2-verify-app.yml, cypress/elements/layer.js, cypress/integration/layers/multilayers.cy.js, cypress/plugins/excludeByVersionTags.js, src/components/layers/LayerCard.js, src/components/layers/LayersPanel.js
Fixes https://dhis2.atlassian.net/browse/DHIS2-16024
=> fix: sorting of layers by drag and drop was not working [DHIS2-16024]

src/components/loaders/LayersLoader.js, src/components/loaders/__tests__/LayersLoader.spec.js, src/components/loaders/__tests__/__snapshots__/LayersLoader.spec.js.snap
Because of the double-negatives and multiple clauses in this statement, I found the code hard to understand. So I re-wrote it in a more verbose style.  The logic is the same: you can run the tests on the old code and it will pass.
=> chore: use more verbose style in LayersLoader to clarify logic

.github/workflows/dhis2-verify-app.yml, cypress.config.js, jest.config.js
not push the jest test results to report portal when running the test locally
=> test: send jest test results only when env is setup

package.json, yarn.lock
Fixes: https://dhis2.atlassian.net/browse/DHIS2-16392
Related analytics PR:
https://github.com/dhis2/analytics/pull/1643
PR showing the fix: PR showing the fix: https://github.com/dhis2/analytics/pull/1600
=> fix: upgrade analytics for interpretation flashing fix [v39]

src/loaders/eventLoader.js, src/util/__tests__/filter.spec.js, src/util/filter.js
Fixes https://dhis2.atlassian.net/browse/DHIS2-16710
Backport of
https://github.com/dhis2/maps-app/pull/3154/commits/9396b8ee3990ee091f9a0904ce3bb50d918e482e and
https://github.com/dhis2/maps-app/pull/3015/commits/bd69a520b357790ca57e2db529ac037c611be03d
=> fix: correctly filter numeric values [v39]

cypress/integration/systemsettings.cy.js, src/loaders/eventLoader.js, src/util/__tests__/filter.spec.js, src/util/filter.js
Fixes https://dhis2.atlassian.net/browse/DHIS2-16710
Backport of
https://github.com/dhis2/maps-app/commit/9396b8ee3990ee091f9a0904ce3bb50d918e482e and
https://github.com/dhis2/maps-app/commit/bd69a520b357790ca57e2db529ac037c611be03d
=> fix: correctly filter numeric values [v38]

cypress/elements/map_canvas.js, cypress/elements/map_context_menu.js, cypress/integration/layers/thematiclayer.cy.js, src/components/core/Radio.js, src/components/map/ContextMenu.js
Fixes https://dhis2.atlassian.net/browse/DHIS2-15798
Backport of https://github.com/dhis2/maps-app/pull/2945
=> fix: hide show long/lat for splitview maps [v39]

package.json, yarn.lock
=> fix: analytics upgrade fixes paragraph newlines in description

package.json, yarn.lock
Fixes https://dhis2.atlassian.net/browse/DHIS2-15914
Backport of https://github.com/dhis2/maps-app/pull/3182
=> fix: map descriptions newlines were not rendered in interpretations panel [v39]

src/components/plugin/Map.js, src/util/__tests__/pluginHelper.spec.js, src/util/pluginHelper.js
fixes https://dhis2.atlassian.net/browse/BETA-144
Code now checks whether the rows or filters properties of the visualization has changed
Before:
https://github.com/dhis2/maps-app/assets/6113918/675b6560-9de4-4d72-8f8f-0fd2f29cbddd
After:
https://github.com/dhis2/maps-app/assets/6113918/42d1a1ed-6396-486e-97e6-498eb207b537
=> fix: dashboard filters were not being applied to maps

.gitignore, i18n/en.pot, src/components/layers/overlays/OverlayCard.js, src/components/layers/toolbar/LayerToolbarMoreMenu.js, webpack.config.js
Fixes [DHIS2-15794](https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/boards/117?selectedIssue=DHIS2-15794)
Backport of https://github.com/dhis2/maps-app/pull/3196
[DHIS2-15794]: https://dhis2.atlassian.net/browse/DHIS2-15794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: users losing work when opening as chart [v39]

cypress/integration/manageLayers.cy.js, src/components/earthEngine/EarthEngineLayer.js, src/components/earthEngine/EarthEngineModal.js, src/components/earthEngine/ManageLayersButton.js
Adding tests to check:
the EarthEngineModal behavior works according to expectations,
adding and removing layers produces the expected effects.
Adding data-test properties when needed.
=> chore: add layers management cypress tests

package.json, src/components/Root.js, src/components/SystemInfoProvider.js, src/components/edit/LayerEdit.js, src/components/edit/thematic/ThematicDialog.js, src/components/periods/PeriodSelect.js, src/util/periods.js, yarn.lock
Implement [DHIS2-16904](https://jira.dhis2.org/browse/DHIS2-16904)
Backport of #3269
[DHIS2-16904]: https://dhis2.atlassian.net/browse/DHIS2-16904?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: support "week", "bi-week" and months in period translations [v39]

package.json, src/AppWrapper.js, src/components/plugin/Plugin.js, yarn.lock
Implement [DHIS2-18029](https://dhis2.atlassian.net/browse/DHIS2-18029)
Linked analytics PR: https://github.com/dhis2/analytics/pull/1699
--------------
Pass `translucent` (false) prop to analytics's `CachedDataQueryProvider` component for both plugin and main app.
The grey background is meant to indicate interaction is not possible while loading, but at this stage there is nothing clickable in the UI of the maps-app.
--------------
Before:
After:
[DHIS2-18029]: https://dhis2.atlassian.net/browse/DHIS2-18029?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: grey background flashing when loading

.github/workflows/verify-pr.yml, cypress/elements/layer.js, jest.config.js
Implementing same fix that is in Line Listing: https://github.com/dhis2/line-listing-app/pull/585
=> chore: skip ReportPortal integration for Dependabot PRs

.github/workflows/dhis2-preview-pr.yml, .github/workflows/nightly.yml, .github/workflows/publish-d2-ci.yml, .github/workflows/release.yml, .github/workflows/verify-pr.yml
Implements [DHIS2-18298](https://dhis2.atlassian.net/browse/DHIS2-18298)
---
1. Upgrades all GitHub Actions
2. For actions that could not be upgraded a note explains why
[DHIS2-18298]: https://dhis2.atlassian.net/browse/DHIS2-18298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: upgrade all used gha versions [DHIS2-18298]

.github/workflows/verify-pr.yml, cypress.config.js, jest.config.js, package.json, yarn.lock
https://dhis2.atlassian.net/browse/DHIS2-18491
=> chore: remove ReportPortal integration

src/components/dataItem/CoordinateField.js, src/components/edit/trackedEntity/PeriodTypeSelect.js, src/components/edit/trackedEntity/TrackedEntityDialog.js, src/components/map/Map.js, src/constants/periods.js, src/hooks/useEventDataItems.js, src/hooks/useProgramStageDataElements.js, src/hooks/useProgramTrackedEntityAttributes.js
Implements:
* [DHIS2-17710](https://dhis2.atlassian.net/browse/DHIS2-17710) - Original PR: https://github.com/dhis2/maps-app/pull/3470
* [DHIS2-18312](https://dhis2.atlassian.net/browse/DHIS2-18312) - Original PR: https://github.com/dhis2/maps-app/pull/3475
* [DHIS2-18641](https://dhis2.atlassian.net/browse/DHIS2-18641) - Original PR: https://github.com/dhis2/maps-app/pull/3440
---
* feat: Resize map when opening full screen in dashboard.
* fix: Prevent TrackedEntity layer not loading when "Program/Enrollment date" was selected and "Program" is switched to "No program".
* fix: Maintain coordinate field value when editing Event layer, including when opening a saved map. Do best effort to maintain value when switching between progamStages and programs.
---
[DHIS2-17710]: …
=> fix: release DHIS2-17710, DHIS2-18312 and DHIS2-18641

src/components/app/App.js, src/components/datatable/BottomPanel.js, src/components/map/MapPosition.js, src/constants/layout.js, src/util/helpers.js
Implements [DHIS2-19231](https://dhis2.atlassian.net/browse/DHIS2-19231)
---
Remove hardcoded HEADER_HEIGHT to prevent sizing issues with the new global shell.
_Note: Deployed on https://dev.im.dhis2.org/maps-global-shell-styles/apps/maps for testing._
[DHIS2-19231]: https://dhis2.atlassian.net/browse/DHIS2-19231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: remove hardcoded HEADER_HEIGHT [DHIS2-19231]

cypress/integration/layers/eventlayer.cy.js, cypress/integration/layers/thematiclayer.cy.js, cypress/integration/layers/trackedentitylayer.cy.js, cypress/integration/orgUnitInfo.cy.js, cypress/support/e2e.js, cypress/support/util.js, package.json, src/constants/basemaps.js, yarn.lock
Implements [DHIS2-19274](https://dhis2.atlassian.net/browse/DHIS2-19274)
Will also includes:
* https://github.com/dhis2/app-platform/pull/916
* https://github.com/dhis2/analytics/pull/1770 (PRs 1767 + 1768)
---
* Update `@dhis2/analytics` to:
* Address issues with markdown links ("intepretations" & "about")
* Address issues with "File" menu > "Get link..."
* Update hyperlinks in attributions: `src/constants/basemaps.js`
* Streamline cypress tests
---
[DHIS2-19277]: https://dhis2.atlassian.net/browse/DHIS2-19277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-19270]: https://dhis2.atlassian.net/browse/DHIS2-19270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-19274]: …
=> fix: ensure hyperlinks work when using the upcoming global shell [DHIS2-19274]

src/components/app/useLoadMap.js
[DHIS2-19387](https://dhis2.atlassian.net/browse/DHIS2-19387)
Pretty much the same changes as in DV: https://github.com/dhis2/data-visualizer-app/pull/3375
https://github.com/user-attachments/assets/b0da9b1f-24a0-4678-8499-3fb39958b44b
[DHIS2-19381]: https://dhis2.atlassian.net/browse/DHIS2-19381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-19387]: https://dhis2.atlassian.net/browse/DHIS2-19387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix:  restore navigation between maps using the browser address bar [DHIS2-19387]

cypress/support/e2e.js
See https://github.com/dhis2/data-visualizer-app/pull/3381 for info
=> chore: restore old session logic and use loginByApi helper

.github/pull_request_template.md
Separate the quality checklist from other todos, and make it more comprehensive
=> chore: update PR template with more comprehensive quality checklist

cypress/support/e2e.js, package.json, yarn.lock
Just a quick PR to upgrade the cypress utils and assert the login request
=> chore: upgrade cli-utils-cypress and assert login request

cypress/elements/event_layer.js, cypress/integration/layers/eventlayer.cy.js, package.json, yarn.lock
[DHIS2-19973](https://dhis2.atlassian.net/browse/DHIS2-19973)
[DHIS2-19973]: https://dhis2.atlassian.net/browse/DHIS2-19973?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: update cli app scripts to open links in same tab [DHIS2-19973]
