dhis2/maps-app

src/reducers/map.js

Closes [DHIS2-4727](https://jira.dhis2.org/browse/DHIS2-4727)
We have to save the basemap as a string in the API, so we lose the additional properties (isVisible, isExpanded, transparency).  So for now we'll set them to the default whenever we load a saved favorite.

DHIS2-4727 - Set default basemap state properties

---

i18n/en.pot

The order of translation strings changed when we moved the visibility toggle, but the translation pot wasn't updated before PR #17 was merged.  This is because the translations are only generated in the prestart script.

Update translation order (no-op)

---

src/components/indicator/IndicatorSelect.js

Problem: 
1) open maps app and create a thematic layer
2) select item type: indicator, indicator group: anc, indicator: anc1
3) try to change the indicator from anc1 to something else
you need to re-select the group to be able to change the indicator
The fix was to add an extra check if list of indicators exists.

Bug fix for indicator select

---

src/components/layers/toolbar/LayerToolbar.js

Some favorites created with old versions of the GIS app don't have an opacity property. This PR sets the default opacity 1. It was already done for the map, but not for the opacity slider.

Setting default layer opacity to 1

---

src/components/orgunits/OrgUnitTree.js
src/epics/orgUnits.js

Fixes: https://jira.dhis2.org/browse/DHIS2-4910
Org unit trees can sometimes have multiple org unit roots, and this PR will create one tree per root using the d2-ui OrgUnitTreeMultipleRoots component.

Support multiple org unit roots

---

i18n/en.pot
package.json
src/components/classification/Classification.js
src/components/classification/LegendTypeSelect.js
src/components/classification/NumericLegendStyle.js
src/components/core/DatePicker.js
src/components/edit/EventDialog.js
src/components/filter/FilterSelect.js
src/components/layers/LayersToggle.js
src/components/layers/legend/Legend.js
src/components/map/EventLayer.js
src/components/map/MapProvider.js
src/components/map/PluginMap.js
src/components/map/ThematicLayer.js
src/constants/layers.js
src/loaders/eventLoader.js
src/util/analytics.js
src/util/classify.js
src/util/legend.js
src/util/styleByDataItem.js
yarn.lock

This PR finalises "style by data element" for event layers: https://jira.dhis2.org/browse/DHIS2-3215
Includes:
- Classification constants are now numbers all over (as in analytical objects, but we need to do some conversion as MUI SelectField and Radio components only accept string values.
- The backend transforms the date format, and we need to change it back after switching to a native date picker. 
- Added notification that a program needs to be selected before style by data item is available. 
- Added legend support for event layers when shown in a plugin. 
- Added "explanation" prop to legend object. Is used in event layer tell abot the buffer radius, if used.
- Show "Not set" in event popup if value is not avalable for a data element. 
- Fix for showing the layers in correct orderin …

Style by data element for event layers

---

package.json
src/app.js
src/map.js

Upgrade to version 31 of the Web API. 
For later, it would be nice to keep the API version setting at one place in the repo.

Web API upgrade

---

src/reducers/layers.js

Small fix that sets thematic layer (most used) first in the add layer dialog:  
https://jira.dhis2.org/browse/DHIS2-4224

Thematic as first layer item in add layer dialog

---

src/components/edit/BoundaryDialog.js
src/components/layers/legend/LegendItem.js
src/loaders/boundaryLoader.js

This PR includes legend support for boundary layers: 
A separate request is made to the Web API to fetch the org unit level names (should be cached of already loaded). The plan is to add these names in the metadata section of the analytics response in a later version of the Web API. 
A future improvement would also be to allow the user to change the colors and the width of the boundary lines. So far, this has not been requested by the users.

Boundary layer legend

---

src/components/layers/toolbar/LayerToolbar.js
src/components/layers/toolbar/__tests__/__snapshots__/LayerToolbar.spec.js.snap

Fix the occasional rapid flashing of the tooltip when hovering the mouse close to the opacity slider.  To do this I've increased the "active" width of the tooltip click surface to be 16px high, matching the height of the slider tab button.  This also makes it easier to click somewhere along the slider tail and set the opacity without dragging.

Fix flashing tooltip

---

package.json
src/util/dom-to-image.js
yarn.lock

This PR will fix an issue where downloading a map using Googe Maps was failing. It also includes a newer version of the GIS API where Google Maps is always loaded using https.

Google maps download fix

---

src/loaders/eventLoader.js
src/util/helpers.js

This PR fixes two bugs: 
- Invalid data dimensions (dx) with empty item array is not passed on to web api
- Older map objects (filters) includes dates with hours, and this fix only checks the validity of the date part which we currently support in the event dialog.

Bug fixes for empty dimensions and period validation

---

src/components/datatable/BottomPanel.js

This PR fixes an issue with the data table: When the interpretations panel is opened/closed, the data table needs to be resized to fit the available space.

Resize data table when interpretations panel is opened

---

src/components/layers/download/DataDownloadDialogContent.js

[DHIS2-5369](https://jira.dhis2.org/browse/DHIS2-5369?filter=11014)
Tested in Chrome, Firefox, IE11

Remove unnecessary scroll bar from DataDownloadDialog for Thematic layers

---

src/components/classification/Classification.js
src/components/core/ColorScaleSelect.js
src/components/edit/EarthEngineDialog.js
src/components/edit/EventDialog.js
src/loaders/eventLoader.js
src/util/colors.js
src/util/legend.js
src/util/styleByDataItem.js

We now expect all colors to follow the CSS standard. Previously we stored colors without the #. This PR corrects these colors for events layers where we have this problem: https://jira.dhis2.org/browse/DHIS2-5371
The utility file colorscale.js was renamed to colors.js to make it more generic for color handling.

Correct event colors from older map favorites

---

plugin.html
src/components/map/plugin/PluginLegend.js
src/components/map/plugin/PluginMap.js
src/epics/layers.js
src/loaders/thematicLoader.js

This PR checks for errors when loading thematic layers, and displays this error in a snackbar (Maps app) or in the legend (Dashboard)
Partly fixes: https://jira.dhis2.org/browse/DHIS2-5412
We could add a similar fix for event layers. 
Previously we showed alerts instead of the map on the dashboard, but we decided to change this as some layers might work.

Improved error handling for failing map layers

---

src/components/filter/FilterSelect.js
src/components/layers/legend/legendStyle.js
src/loaders/eventLoader.js
src/util/__tests__/geojson.spec.js
src/util/geojson.js
src/util/styleByDataItem.js

This PR fixes various issues with event layers filters and styling by data element:
- Added right padding to event legend 
- Allow dimensions to have empty items array if it contains a filter (issue with saved maps)
- Fix issue with header names needed for legend
- Don't include styleDataItem as a dimension if it's already included in a filter
Related issue: https://jira.dhis2.org/browse/DHIS2-5397
Sorry that the tests got reformatted when I edited them :-)

Fix issues with filter and style by data element

---

src/components/layers/layers/LayerCard.js

Add "Layer is loading" message to the layer card, and avoids displaying the layer id as a name.

Add loading text to layer card

---

src/components/download/DownloadLegend.js
src/components/map/EventLayer.js
src/components/map/Map.js
src/components/map/MapName.js
src/components/map/ThematicLayer.js
src/util/helpers.js

Fixes: https://jira.dhis2.org/browse/DHIS2-5478
dom-to-image is not loading the Robot font for some reason. A quickfix was to switch to Arial when going into download mode. 
Added removeLineBreaks as a utility method. Used to remove line breaks from html text strings.

Fix for style issues in download maps

---

src/components/core/InterpretationIcon.js
src/components/map/Map.js
src/components/map/MapName.js
src/components/map/plugin/PluginLegend.js
src/reducers/map.js

Fixes: https://jira.dhis2.org/browse/DHIS2-5477
This PR displays the time of the selected interpretation on the map:
The PR also includes a fix for map legends on dashboard maps: the layers are reorders so the top layer is shown first. 
We don't support different date formats/locales in the Maps app. I've created a separate issue for this task: https://jira.dhis2.org/browse/DHIS2-5498
For later: 
- Shared repo for app icons

Show relative period data from interpretations

---

i18n/en.pot
src/components/layers/toolbar/LayerToolbarMoreMenu.js

Before:
After:
**NB**  The FileMenu dividers are also pretty compressed, but it is a bit less straightforward to fix that (since it's a much longer menu).  Will wait for Joe before making this a generic solution.
* Also add missing interpretation time travel translations

Increase LayerCard more menu divider spacing

---

src/components/dataItem/EventDataItemSelect.js

Fixes issue: https://jira.dhis2.org/browse/DHIS2-5457
@larshelge, are Program Tracked Entity Attributes supposed to work as an event data item for thematic layers? 
I saw that we get an error if we select an tracked entitiy attribute in the Maps app:
https://play.dhis2.org/2.31/api/31/analytics.json?dimension=ou:LEVEL-2&dimension=dx:lw1SqmMlnfh&filter=pe:2018&displayProperty=SHORTNAME
Returns error: "Dimension dx is present in query without any valid dimension options"
The reason is that the program id is not included in the dx dimension as for program data elements. This PR adds it: 
https://play.dhis2.org/2.31/api/31/analytics.json?dimension=ou:LEVEL-2&dimension=dx:uy2gU8kT1jF.lw1SqmMlnfh&filter=pe:2018&displayProperty=SHORTNAME
It avoids the error, but I get no data (rows) back.
Is …

Add program id to tracked entity attributes

---

package.json
src/components/core/DatePicker.js
src/components/edit/EventDialog.js
src/components/edit/TrackedEntityDialog.js
src/components/edit/thematic/ThematicDialog.js
src/components/map/Map.js
src/components/map/MapName.js
src/components/periods/PeriodSelect.js
src/constants/layers.js
src/epics/earthEngine.js
src/loaders/eventLoader.js
src/loaders/thematicLoader.js
src/loaders/trackedEntityLoader.js
src/util/__tests__/time.spec.js
src/util/helpers.js
src/util/time.js
yarn.lock

Fixes: https://jira.dhis2.org/browse/DHIS2-5498
This PR cleans up the time handlng in the Maps app:
- All times shown in the interface are in a localised format 
- All time functions in one file (util/time.js) with unit tests
- Switch from d3-time-format to Intl (browser native)
The redux store is also connected to the MapName component as this got more complex with the interpretation time handling.

Support different date formats/locales and improved time handling

---

src/components/dataItem/CoordinateField.js
src/util/favorites.js

Fixes: https://jira.dhis2.org/browse/DHIS2-5850
This PR includes "eventCoordinateField" as a valid mapViews field. So far we have not been saving the selected coordinate field when saving events layers. This resulted in a bug where the default event coordinate was used when the map was loaded. 
When a event layer is loaded, the coordinate field is already selected, so we need to trigger loading of program tracked entity attributes and program data elements in both componentDidMount and componentDidUpdate. 
This fix needs to be backported to DHIS2 Maps 2.29, 2.30 and 2.31.

Saving and loading og coordinate fields for events

---

src/epics/orgUnits.js
src/loaders/boundaryLoader.js

Stupid error that restricts the number of org units levels, org unit groups and org unit group sets we load from the Web API. 
Fixes: https://jira.dhis2.org/browse/DHIS2-6003
Fix needs to be backported to 2.29, 2.30 and 2.31.

Paging typo fix

---

package.json
src/components/app/App.css
src/components/app/App.js
yarn.lock

This PR includes importing the new @dhis2/ui package with updated styling rules such that `<strong>` and `<em>` tags are rendered without being reset.
The `<UI>` wrapper is removed, replaced with the new `reset.css` style sheet.
The old `<HeaderBar />` is replaced with the new from @dhis2/ui.
Additionally, 1 rule to the body (`font-family`) have been added, (similar to how the usage-analytics app, dashboard and data-visualizer utilize the new packages).
After merging this change, i'll open a PR for updating the interpretation package with rich text support.

import new @dhis2/ui package with header bar and .css style sheet

---

src/components/edit/BoundaryDialog.js
src/components/edit/FacilityDialog.js
src/components/edit/thematic/ThematicDialog.js
src/components/orgunits/OrgUnitGroupSelect.js
src/components/orgunits/OrgUnitLevelSelect.js
src/reducers/layerEdit.js
src/util/analytics.js

This PR fixes issue: https://jira.dhis2.org/browse/DHIS2-6190
When selecting an user org unit level, all other org unit selections are cleared and disabled. This is fixed for thematic, facility and boundary layers. 
This is the same behaviour as the Data Visualizer app.
At a later stage we should switch to the same org unit selection components as the Data visualizer app. 
This fix needs to be backported to Map app 2.29.

Empty and disable org unit levels and groups selections when user org unit is selected

---

src/epics/externalLayers.js

When the API request from loadExternalLayers-epic failed, it crashed the epic-stream. Heres a copy paste explanation from #100 
> What happened was that a promise that returned an array was merge-mapped, and then concatAll()'ed, which means that the stream now contains an array of objects, instead of a promise. Which is fine since its an array, and when that is collected each element is emitted in sequence, which is the desired behavior. However, when it fails, the action returned in the catch handler is collected by the concatAll() and the pure action-object is returned, rather than an observable of the action.
When working with redux-observable you really have to thing twice if you start chaining operators directly on the action stream.
I simplified the epic by moving the creation of …

fix(externallayers): handle network error correctly

---

i18n/en.pot
src/epics/earthEngine.js

Fixes: https://jira.dhis2.org/browse/DHIS2-6318
The ee.initialize method is wrapped in a promise, and not called synchronously. We also show an alert if a connection to Google Earth Engine could not be established.

Async loading of EE collections with error handling

---

package.json
src/epics/earthEngine.js
yarn.lock

Fixes: https://jira.dhis2.org/browse/DHIS2-6377
This PR uses a newer version of the GIS API with fixes for the Earth Engine dependency. 
It's also setting the error message to the correct promise.

Empty filters error with Earth Engine layers

---

src/util/favorites.js
src/util/requests.js

Fixes: https://jira.dhis2.org/browse/DHIS2-6501
This PR will transform the old map favorite format (having thematic layers 1-4) to the current format, before loading/drawing the map layers.

Translate old map favorite object in maps plugin

---

src/util/favorites.js

This PR solves a case where the dashboard is passing a full map map config (analytical object) to the maps plugin where an external basemap is specified in mapViews. This is an old format we need to support for backward compability.

Support old external basemap format

---

src/components/layers/basemaps/BasemapCard.js
src/components/layers/layers/LayerCard.js

Fixes: https://jira.dhis2.org/browse/DHIS2-6681
If layer is open tooltip should read 'Collapse', if layer is closed tooltip should read 'Expand'.

fix: expand/collapse layer tooltip

---

src/loaders/eventLoader.js

This PR fixes an issue where there are invalid (empty) dimensions in a saved map. When the invalid dimension had the same id as the "style by data item" the events were not styled. 
If was fixed by the dimension validity check before adding the style data item.

fix: remove invalid dimensions for event layers

---

src/components/dataItem/CoordinateField.js

Issue: https://jira.dhis2.org/browse/DHIS2-6733
Strange issue that I'm not able to reproduce locally. It seems to originate from the code line changed where the field is undefined. I've added an extra check if the data item exist. 
I'll do some extra testing when this is fix is deployed from the v32 branch.

fix: error when checking for coordinate fields

---

src/epics/favorites.js

Fixes issue: https://jira.dhis2.org/browse/DHIS2-6750
When we save a map, the Web API returns the id in the Location header. The format of this string is changed in the backend, so we need to change how we extract the id. 
We now get the uid from the response itself which should be less fragile.

fix: extract map id from web api response

---

src/components/edit/EventDialog.js
src/components/edit/thematic/ThematicDialog.js

This PR moves the filter tab after the org units tab. Reasons are:
1. its nice to have the _mandatory_ dimensions come first, so that user can quickly create a map (i know org unit is preselected). Filters are optional while org unit is mandatory).
2. this makes it consistent with pivots/charts where we have data, period, org unit in that order.

Change order of layer dialog tabs

---

src/components/dataItem/CoordinateField.js
src/epics/programs.js
src/util/helpers.js

Fixes app crash: https://jira.dhis2.org/browse/DHIS2-6733
The root cause to this issue is that the Web API allows an empty data item (no properties) to pass through: https://jira.dhis2.org/browse/DHIS2-6760
With this PR we validate that all program stage data elements and tracked entity attributes contains id, name and valueType properties which are required by the app. 
This replaces the fix in https://github.com/dhis2/maps-app/pull/128 which is reverted im this PR.

Validity check of program stage data elements and tracked entity attributes

---

src/util/geojson.js

Fixes: https://jira.dhis2.org/browse/DHIS2-6776
To draw polygons before points, they need to be first in the data array.

fix: sort to draw polygons before points

---

src/util/styleByDataItem.js

This fixes [DHIS2-6913](https://jira.dhis2.org/browse/DHIS2-6913) which was introduced by a change to use lowercase strings in the OptionSet map (a15cd4f6904ac163c953fa7517c51869f27e61d3)

fix: correctly look up lowercase option code

---

scss/layout.scss

Fixes: https://jira.dhis2.org/browse/DHIS2-4726 for Maps 2.30
The fix allows drop down menus to have a width of its content, rather than the width of the select field that triggers it. 
I applied a quickfix for this backport as the original select field component is in another repo that is no longer maintained. I've clicked through all layer dialogs and did't notice any unwanted side effects.

fix: expand the width of drop down menus

---

src/components/edit/EarthEngineDialog.js
src/epics/earthEngine.js
src/loaders/earthEngineLoader.js
src/reducers/layers.js

Fixes: https://jira.dhis2.org/browse/DHIS2-6993
This PR changes to an up-to-date temperature layer from Google Earth Engine. I've also included a transformation to allow saved temperature layers to load. 
This fix should be backported to 2.30, 2.31 and 2.32

fix: new temperature layer from google earth engine

---

src/components/earthengine/Collection.js
src/epics/earthEngine.js
src/util/time.js

Fixes: https://jira.dhis2.org/browse/DHIS2-6321
This PR solves an issue with precipitation and temperature layers from Google Earth Engine. The data is provided in 5 and 8-days intervals, and with multiple years the period dropdown gets too big. The solution was to include a separate year select for these layers. 
The most recent year is autoselected. If a saved map is loaded, the year is extracted from the used period.

feat: improved period selection for google earth engine layers

---

src/components/edit/EarthEngineDialog.js
src/epics/earthEngine.js
src/loaders/earthEngineLoader.js
src/reducers/layers.js

Backport of #140 to DHIS2 Maps 2.32
Fixes: https://jira.dhis2.org/browse/DHIS2-6993

fix: new earth engine temperature layer for 2.32

---

src/util/styleByDataItem.js

Fixes: https://jira.dhis2.org/browse/DHIS2-7041
Fixes an issue where events are not styled by an option set, due to different case. 
We should switch to use uid to match options - it was previously not supported by the Web API, but we should check again.

fix: use lower case when comparing options

---

public/plugin.html

This simply adds a `<textarea>` to `plugin.html` to support debugging of raw JSON config objects, rather than loading the plugin map by ID.  Note that to prevent the Plugin code from fetching a "favorite" from the server this requires the config to **omit** the `id` property and also for the `id` text field to be empty.
There's some divergence in how "fetched" and "configured" favorites are loaded which may cause some problems or make things harder to test with this method.  We should refactor the logic so that it is shared after the config is fetched.

chore: add tool to input JSON config object to plugin.html

---

src/map.js

For backward compatibility, we need to allow basemap to be "none", e.g. don't show any basemap. We now control this with the visibility paramenter. 
Later (when we retire the old GIS app) we should fix this in a db upgrade script. 
Fixes: https://jira.dhis2.org/browse/DHIS2-7075
Needs to be backported.

fix: allow basemap to be 'none'

---

src/components/earthengine/Collection.js

A small refactoring to show the year dropdown when the user is editing an EE layer which is already created (and collections are loaded). 
Related issue: https://jira.dhis2.org/browse/DHIS2-6321

Period selection fix for EE layers

---

package.json
yarn.lock

Backport to v31
Update interpretations package.
Update includes removal of "apply" button on new interpretations.
Ticket [DHIS2-6250](https://jira.dhis2.org/browse/DHIS2-6250).

chore(v31): update interpretations panel [DHIS2-6250]

---

package.json
yarn.lock

Backport to v32.
Update interpretations package.
Update includes removal of "apply" button on new interpretations.
Ticket [DHIS2-6250](https://jira.dhis2.org/browse/DHIS2-6250).

chore(v32): update interpretations panel [DHIS2-6250]

---

src/components/core/Tabs.js

This is a tiny fix for a console error resulting from an upgraded dependency - we were previously using the `fullWidth` property for the tabs in layer dialog, but that property is deprecated.  The console error was:
```
checkPropTypes.js:20 Warning: Failed prop type: The prop `fullWidth` of `Tabs` is deprecated. Instead, use the `variant="fullWidth"` property.
```
Fixed by switching to use variant instead.

Fix: use variant fullwidth instead of deprecated property

---

src/components/map/ThematicLayer.js

Fixes: 
https://jira.dhis2.org/browse/DHIS2-7474
https://jira.dhis2.org/browse/DHIS2-7479
This PR fixes an issues where there are no data for certain period. When there is no data for an org unit for a time period, we set the value to "No data" and the color to null (it will then get the default no data color. 
We also make sure that the data (feature array) is unique for each period map by using the spread operator.

fix: make data for each period map unique

---

src/components/map/ThematicLayer.js
src/components/periods/Timeline.js

Fixes: 
https://jira.dhis2.org/browse/DHIS2-7490
https://jira.dhis2.org/browse/DHIS2-7478
The ticks still don't align with the periods on narrow screens, but I think it's acceptable. Changing it further requires us to edit the d3.js source implementation, which is not worth the effort.

fix: timeline fix for Firefox and bi-monthly periods

---

src/components/app/App.css
src/components/map/EventLayer.js
src/util/helpers.js

Fixes: https://jira.dhis2.org/browse/DHIS2-6394
The Web API returns corrdinates as a string array with high decimal precision. The fix formats this value to use 6 decimals (meter precision). 
Needs to be backported.

fix: format coordinate values in event popups

---

src/epics/dataDownload.js
src/loaders/thematicLoader.js

Fixes: https://jira.dhis2.org/browse/DHIS2-7556
Value for each period is included in the data download from split view or timeline maps.

fix: download multiple values for each feature

---

src/components/map/MapContainer.js
src/reducers/map.js

Fixes an issue with https://github.com/dhis2/maps-app/pull/177 where the loading spinner was not showing for newly created layers. The layer don't exist in the redux store before it's loaded the first time, so it's not possible to set the loading state. As a fix, I've added a "newLayerIsLoading" property on the map object which is used in this case.

fix: loading indicator for new layers

---

src/components/edit/thematic/ThematicDialog.js
src/constants/layers.js
src/loaders/thematicLoader.js

Fixes: https://jira.dhis2.org/browse/DHIS2-7690
Default radius low and high are defined as constants. 
The radius is calculated for each period if split view or timeline maps.

fix: point radius for thematic layers with time dimension

---

src/components/map/EventLayer.js
src/components/orgunits/OrgUnitDialog.js
src/loaders/boundaryLoader.js

Fixes: https://jira.dhis2.org/browse/DHIS2-7773
The problem was that we didn't return any layer config if the array was empty. The code works fine empty arrays, so the fix was to remove an early return, and then include an alert if no boundary features was retuned (= empty array).

Show alert if no boundaries was returned

---

src/components/periods/PeriodSelect.js

Fixes: https://jira.dhis2.org/browse/DHIS2-7839
This PR fixes 2 issues with the period selector:
1. Avoids crash if year is changed into the future, and then period type is changed. The crash happened because filterFuturePeriods would return an empty periods array as all of them would be in the future. If this is the case, we return the first period in the array.
2. If you select a period type, change the year, and then then change the tab, the period will no longer be selected. This PR fixes the issue by making sure the year is still the same, and not reset to the most recent year. 
The long term plan is to switch to a shared period selector component, so I've tried to make as few changes as possible here, as the fix also needs to be backported.

fix: period select fixes

---

src/components/dimensions/DimensionFilterRow.js

Fixes: https://jira.dhis2.org/browse/DHIS2-7866
When the user changed filter dimension, we did not clear the selected dimension items, which resulted in a crash.

fix: clear dimension items array when filter is changed

---

i18n/en.pot
package.json
src/components/dimensions/DimensionFilterRow.js
src/components/filter/FilterSelect.js
src/components/periods/PeriodSelect.js
src/loaders/trackedEntityLoader.js
src/util/analyticalObject.js
src/util/dom-to-image.js

Backport #262, #263 and #264 to 2.32

fix: backport #262, #263 and #264 to 2.32

---

i18n/en.pot
package.json
src/components/datatable/ResizeHandle.css
src/components/map/BoundaryLayer.js
src/components/map/EventLayer.js
src/components/map/EventPopup.js
src/components/map/FacilityLayer.js
src/components/map/Layer.js
src/components/map/Map.js
src/components/map/Popup.css
src/components/map/Popup.js
src/components/map/ThematicLayer.js
src/components/map/TrackedEntityLayer.js
src/util/helpers.js
yarn.lock

Fixes: https://jira.dhis2.org/browse/DHIS2-7675
This PR refactors the popup handling in the Maps app, which is part of the larger Maps GL transition. Instead of generating HTML strings of popup content, we use react and createPortal from react-dom. 
A separate Popup component was created where the content is passed in as child elements. 
The event layer popup handling is complex, and an EventPopup component was created to separate it from the layer handling.

fix: refactor popup handling

---

src/map.js

Fixes: https://jira.dhis2.org/browse/DHIS2-8215
Allows the user to authenticate with username and password with the map plugin.

fix: authentication header for map plugin

---

.travis.yml
cypress/integration/common/smoke.spec.js
cypress/integration/layers/facilitylayer.spec.js
package.json
src/components/map/MapApi.js
yarn.lock

This PR will switch from gis-ap to the new maps-gl engine.

feat: switch to maps gl

---

src/loaders/boundaryLoader.js
src/reducers/map.js
webpack.config.js

Fixes: https://jira.dhis2.org/browse/DHIS2-8222
If alerts is NULL, it will not be set to an empty array here: https://github.com/dhis2/maps-app/blob/master/src/components/plugin/Legend.js#L88
This PR sets alerts to undefined. 
Should also be backported to 2.33. 
This PR also sets baseUrl to '../' for production builds.

fix: set alerts to undefined

---

package.json
src/components/map/BoundaryLayer.js
src/components/map/ContextMenu.js
src/components/map/FacilityLayer.js
src/components/map/Layer.js
src/components/map/Map.js
src/components/map/ThematicLayer.js
src/components/plugin/ContextMenu.js
yarn.lock

By right-clicking the map the mapping api is sending back the lng, lat position and the point position relative to the map container. 
This works fine for the map plugins (dashboard) but the context menu need to take the position of the map container into account as it's fixed positioned. This PR does this calculations. 
I've also done some refactoring on increase code reuse and to use hooks for the plugin context menu. 
The app context menu also need some love and refactoring, but this need to wait.

fix: map context menu positioning and refactoring

---

src/map.js

We have issues with class names collisions on the Dashboard, probably due to different Material UI versions and JSS. This PR wraps the maps plugin in a JssProvider using a maps-plugin- prefix.

fix: use JssProvider for maps plugin

---

package.json
src/map.js

The previous try using JssProvider to add a prefix to class names did't have an effect, so I'm switching to StylesProvider as documented on https://material-ui.com/styles/api/#creategenerateclassname-options-class-name-generator

fix. class name prefix for map plugins

---

src/app.js
src/components/core/SelectField.js
src/components/download/DownloadDialog.js
src/components/layers/legend/LegendItem.js

This PR fixes:
- Bing Maps key is loaded before a saved map to make sure if have the Bing Maps key available.
- Select lists are more compact. 
- Bing Maps logo is not included in map download (it's blocked by CORS policy).
- Allow maps to be downloaded if no title in present. 
- Set max radius for legend items

fix: Bing Maps download and more compact select lists

---

package.json
src/components/layers/toolbar/LayerToolbarMoreMenu.js
src/components/map/MapItem.js
src/loaders/thematicLoader.js
yarn.lock

This PR fixes: 
- Less padding for toolbar more menu (needed after Material UI upgrade)
- Show 2x2 for split view with 4 maps (not 3x1)
- Use predefined legend for data item if exist (as default)

fix: style and default legend

---

src/components/classification/NumericLegendStyle.js
src/loaders/thematicLoader.js

Fixes: https://jira.dhis2.org/browse/DHIS2-8471
This PR fixes a bug when editing thematic layers multiple times. If style tab is not visited on the first edit, the default legend from the data item is not stored. This fix makes sure the default legend is applied. 
It also clear the alerts between edits.

fix: set default legend set from data item

---

src/components/map/Layer.js
src/components/map/ThematicLayer.js
src/loaders/thematicLoader.js

Partly fixes:  https://jira.dhis2.org/browse/DHIS2-8479
Related to the same issue with invalid org unit selections for facility layers: https://github.com/dhis2/maps-app/pull/495
The error originates in an invalid org unit selection that was not handled properly. 
This PR includes a fix that check if period(s) are available (which is not the case if org unit selection is invalid). We allow the limited layer config to pass through so the user can edit the layer and fix the org unit selection. 
The error message received could be more descriptive, but I think it will work until we get new org uni selection in place: https://jira.dhis2.org/browse/DHIS2-8481

fix: Handle error if org unit selection is invalid for thematic layers (DHIS2-8479)

---

src/components/dimensions/DimensionSelect.js

Fixes: https://jira.dhis2.org/browse/DHIS2-8487
Avoids double scrollbars for dimension select popover: 
Setting overflow-y to "hidden" is not affecting the inner scroll to reach the bottom of the list.

fix: remove doble scrollbars for dimension select

---

i18n/en.pot
src/components/edit/thematic/ThematicDialog.js

Fixes: https://jira.dhis2.org/browse/DHIS2-8485
This PR fixes an issue with thematic layer not getting default classification/legend stored if the styled tab is not visited by the user before "Add layer" button is clicked. 
The solution is to set the default classification/legend whenever a data item is first selected or changed.
Before this fix making this selection would produce a map with a predefined legend: 
But the predefined legend was not saved with the map, as the selection was never made in the UI without first visiting the Style tab. This PR makes sure this is happening.

fix: set the default classification/legend for selected data item (DHIS2-8485)

---

package.json
src/components/map/ThematicLayer.js
src/components/plugin/Plugin.js

Fixes: https://jira.dhis2.org/browse/DHIS2-8520
The right-click context menu is not shown in the correct position for plugin maps (including Dashboards): 
The fix calculates the position relative to the window/document:
This is fixed in a more elegant way in Maps app master/2.34.

Correct context menu position for plugin maps  (DHIS2-8520)

---

package.json
src/components/map/ThematicLayer.js
src/constants/mapControls.js
yarn.lock

Fixes: https://jira.dhis2.org/browse/DHIS2-8524
Related PR in `maps-gl` which is now merged and the dependency is updated in this PR: https://github.com/dhis2/maps-gl/pull/77
The `isPlugin` option is removed from the fullscreen control as it's no longer in use. 
A bug was discovered while working on this issue, and a fix is included in this PR. The bug was introduced in a previous PR which is not present in the 2.34 release candidate. 
The `if (this.state)` check failed as we now set `state = {};` in the Layer component, so the check is always true. We then got an error as we can't called setState on an unmounted component. The fix is to use the callback parameter to decide if the component is mounted or not.

fix: change fullscreen control container and period state handling (DHIS2-8524)

---

src/loaders/eventLoader.js

Fixes: https://jira.dhis2.org/browse/DHIS2-8529
When editing an existing event layer, the serverCluster option is not cleared. This option is not set by the user, but based on the number of events.

fix: delete serverCluster option if previously set

---

src/loaders/thematicLoader.js

Fixes: https://jira.dhis2.org/browse/DHIS2-8564
The issue is that the data and legend is not cleared for a thematic layer if a new org unit selection is invalid. This fix will clear the data and legend from the config object. 
Before this fix, the map and legend is not cleared: 
After this fix:

fix: clear data and legend when loading fails (DHIS2-8564)

---

src/util/analyticalObject.js

Fixes: https://jira.dhis2.org/browse/DHIS2-8575
This PR fixes an issue to keep dynamic filters are not kept when switching from DV to Maps. 
This screenshots shows a map opened from DV where the dynamic filters are kept:

fix: keep dynamic filters when switching from DV (DHIS2-8575) 

---

src/components/plugin/Plugin.js

Fixes: https://jira.dhis2.org/browse/DHIS2-8618
This PR adds a new boolean "hideTitle" option for plugin maps. Default value is "false" (show title). When "true" the map title will not be shown on the map. 
NB! "hideTitle: true" needs to be added for the maps plugin in the Dashboard app after this PR is merged. 
When "hideTitle" is "false" or option not present. 
When "hideTitle" is "true":

feat: hideTitle option for plugin maps (DHIS2-8618)

---

src/util/analyticalObject.js
src/util/favorites.js

Fixes: https://jira.dhis2.org/browse/DHIS2-8585
This PR fixes an issue where we try to serialise OU dimensions represented as models resulting in a circular structure error.  This fix is to use the same approach as we do on save, to clean the OU dimensions by only allowing the needed properties to pass through. 
Solves this error:

fix: clean ou dimension before app switching

---

src/components/map/ThematicLayer.js

Fixes: https://jira.dhis2.org/browse/DHIS2-8640
This bug was introduced by this PR: https://github.com/dhis2/maps-app/pull/496/
So this bug has never faced the user. 
It is not present in 2.34.0-rc tested on: https://verify.dhis2.org/2.34.0-rc/
`(!period || !periods)` returned true if period was undefined while periods was not. If no period is defined the first period should be used. Fixed by using `&&` - the function should only return if both period and periods are undefined.

fix: use first period as default

---

src/components/edit/thematic/ThematicDialog.js

Fixes: https://jira.dhis2.org/browse/DHIS2-7924
For thematic layers we use the second level as the default org unit selection. This fix makes sure that this level is only selected when no other org units are selected, including user org units. 
Before this fix, the second org unit level is selected even though a user org unit level is selected. It is not possible deselect the org unit level, leading to an error when the layer is updated. 
With this PR the default org unit level is not selected:

fix: only set default org unit level if no other org units are selected (DHIS2-7924)

---

src/components/filter/FilterSelect.js

Fixes: https://jira.dhis2.org/browse/DHIS2-7089
For event filtering we show some operators not supported by the Web API, and this PR removes them. 
Supported operators: 
https://docs.dhis2.org/master/en/dhis2_developer_manual/web-api.html#filtering_1
For option sets the `!IN` (not in) operator has been removed. 
For text the `!LIKE `(not contains) operator has been removed, and the `!EQ` operator has been renamed to `NE`. 
As there is only one operator (`IN`) available for option sets, the selection could be removed. I decided to keep it to have minimal changes for this bugfix which should be backported. 
There is a plan to use similar components as in use for DV map.

fix: remove unsupported filter operators for event layers (DHIS2-7089)

---

package.json
src/loaders/eventLoader.js
src/util/analyticalObject.js
yarn.lock

This PR is a backport of the following issues:
- [DHIS2-8496](https://jira.dhis2.org/browse/DHIS2-8496) - Support layer ordering for tracked entities layers (https://github.com/dhis2/maps-gl/pull/69)
- [DHIS2-8498](https://jira.dhis2.org/browse/DHIS2-8498) - Update server clusters when map is zoomed to layer bounds (https://github.com/dhis2/maps-gl/pull/70)
- [DHIS2-8529](https://jira.dhis2.org/browse/DHIS2-8529) - Editing Event layer from "Group events" to "Show all events" result… (#528)

fix: backport fixes to 2.34.0

---

src/components/map/ThematicLayer.js

Fixes: https://jira.dhis2.org/browse/DHIS2-8176
We're treating nodata for timeline and split view maps differently than for the default single (aggregate) maps. For single maps, we don't show org units with no data values, and with this PR we do the same for timeline and split view maps. 
There is a separate issue to make this user selectable in a future release: https://jira.dhis2.org/browse/DHIS2-8642
Before:
After: 
Before: 
After:

fix: only show org units with data values for timeline and split view maps (DHIS2-8176)

---

i18n/en.pot
src/components/classification/Classification.js
src/components/edit/EarthEngineDialog.js
src/components/edit/LayerEdit.js
src/components/edit/TrackedEntityDialog.js
src/components/edit/thematic/AggregationTypeSelect.js
src/components/layers/layers/LayerCard.js
src/components/orgunits/OrgUnitTree.js
src/components/orgunits/SelectedOrgUnits.js
src/components/orgunits/UserOrgUnitsSelect.js
src/components/periods/PeriodTypeSelect.js
src/components/periods/RelativePeriodSelect.js
src/components/periods/RenderingStrategy.js
src/constants/aggregationTypes.js
src/constants/layers.js
src/constants/periods.js
src/epics/favorites.js
src/epics/layers.js
src/loaders/earthEngineLoader.js
src/loaders/thematicLoader.js
src/reducers/layers.js
src/util/analytics.js

Fixes: https://jira.dhis2.org/browse/DHIS2-8658
The PR wraps non-translatable strings in `i18n.t()`. It is also a larger refactor to avoid using variables directly in `i18n.t()`, as these strings are not identified when the localisation files are generated.
This regex can be used to identify translation strings in Visual Studio Code which are not properly formatted: `i18n.t\([^'"]`

fix: translation strings (DHIS2-8658)

---

src/components/map/MapContainer.js
src/components/plugin/Plugin.js

Fixes: https://jira.dhis2.org/browse/DHIS2-8713
The reason fullscreen was not working in Safari is that div elements don't have width 100% by default, so the fix was to add it, both to the app container and the plugin. 
Map in app opened in fullscreen in Safari:
Plugin map opened in fullscreen in Safari:
Before this fix the fullscreen in Safari was black, as the map container didn't take any horizontal space.

fix: set width of fullscreen container

---

src/components/edit/thematic/ThematicDialog.js
src/components/filter/FilterSelect.js
src/loaders/facilityLoader.js
src/util/analyticalObject.js
src/util/favorites.js

2.32 backports of: 
- [DHIS2-7089](https://jira.dhis2.org/browse/DHIS2-7089) | #586 | https://github.com/dhis2/maps-app/pull/621/commits/2734023ca3202e8a4ae81dd0d026d71b1b7f8959 | Filtering on data element option with "Not one of" gives error
- [DHIS2-7924](https://jira.dhis2.org/browse/DHIS2-7924) | #585 | https://github.com/dhis2/maps-app/pull/621/commits/3d436b5b10a642d681abadc7abfd36a74d48043b | Editing map layer with OU grandchildren selected breaks map 
- [DHIS2-8474](https://jira.dhis2.org/browse/DHIS2-8474) | #495 | https://github.com/dhis2/maps-app/pull/621/commits/653afca047ca2c06e4151c133ef331db5a322c0c | Handle error if org unit selection is invalid for facility layers
- [DHIS2-8575](https://jira.dhis2.org/browse/DHIS2-8575) | #565 | …

Backports to 2.32.5

---

i18n/en.pot
src/components/plugin/Plugin.js
src/loaders/thematicLoader.js

This is a partly backport of https://jira.dhis2.org/browse/DHIS2-8479
Original PR: #496 
The app crash is not present in Maps 2.33, but we don't show the layer name in the left panel if the loading fails: 
With this PR, the layer name will show and the panel will be expanded: 
This makes it easier for the user to edit and correct the layer.

fix: show layer name for when loading fails, 2.33 backport (DHIS2-8479)

---

i18n/en.pot
src/loaders/thematicLoader.js

This is a partly backport of https://jira.dhis2.org/browse/DHIS2-8479
Original PR: #496
The app crash is not present in Maps 2.32, but we don't show the layer name in the left panel if the loading fails: 
With this PR, the layer name will show and the panel will be expanded: 
This makes it easier for the user to edit and correct the layer.

fix: show layer name for when loading fails, 2.32 backport (DHIS2-8479)

---

src/components/edit/LayerEdit.js
src/util/analytics.js

Small correction from #590: the `periodNames` import needs to be renamed to `getPeriodNames` after it was wrapped in a function:  https://github.com/dhis2/maps-app/blob/master/src/constants/periods.js#L78

fix: rename period names import

---

i18n/en.pot
package.json
src/components/layers/layers/Layer.js
yarn.lock

Fixes: https://jira.dhis2.org/browse/DHIS2-8658?focusedCommentId=33085&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-33085
Backport of: #657
Added some missing translation handing for layer names. 
Upgraded d2-ui dependencies to version 7.0.2 for translation fixes.
rx.js was upgraded to the same version as used in the d2-ui dependencies.

fix: 2.34 d2-ui dependency upgrades with translation fixes (DHIS2-8658)

---

i18n/en.pot
package.json
src/components/layers/layers/Layer.js
src/epics/externalLayers.js
yarn.lock

Fixes: https://jira.dhis2.org/browse/DHIS2-8658?focusedCommentId=33085&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-33085
Backport of: #657
Added some missing translation handing for layer names.
Upgraded d2-ui dependencies to version 7.0.2 for translation fixes.
I got an error with rxjs after the upgrades: 
It was corrected by using the same rxjs version as in the d2-ui dependencies, and fixing an import.

fix: 2.32 d2-ui dependency upgrades with translation fixes (DHIS2-8658)

---

i18n/en.pot
package.json
src/components/layers/layers/Layer.js
src/epics/externalLayers.js
yarn.lock

Fixes: https://jira.dhis2.org/browse/DHIS2-8658?focusedCommentId=33085&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-33085
Backport of: #657
Added some missing translation handing for layer names.
Upgraded d2-ui dependencies to version 7.0.2 for translation fixes.
I got an error with rxjs after the upgrades: 
It was corrected by using the same rxjs version as in the d2-ui dependencies, and fixing an import.

fix: 2.33 d2-ui dependency upgrades with translation fixes (DHIS2-8658)

---

i18n/en.pot
src/components/core/FontStyle.js
src/components/edit/LayerEdit.js
src/components/layers/basemaps/Basemap.js
src/components/layers/basemaps/BasemapCard.js
src/components/map/mapLocale.js
src/constants/basemaps.js
src/map.js
src/reducers/basemaps.js
src/reducers/map.js
yarn.lock

This PR adds i18n support for strings that couldn't be translated in the maps app. 
`i18n.t(name)` will not be discovered by the translation system, but all names are translated in basemaps.js, but this reducer is evaluated before the language setting is available. Will fix better when we switch to the app plattform. 
`subtitle: 'Basemap'` is removed as this is the default value defined here: https://github.com/dhis2/maps-app/blob/master/src/components/layers/basemaps/BasemapCard.js#L71

fix: add missing translations (DHIS2-8658)

---

package.json
src/map.js
src/util/analytics.js

Fixes: https://jira.dhis2.org/browse/DHIS2-8880
Problem description: When multiple maps are included on the same dashboard the CSS class names are shared between different maps, while the styling is different between single, timeline and split view maps. 
The styles from the different map types are combined as they share the same class names (`map-plugin-x`):
The suggested fix is to include "rendering strategy" in the class name prefix to avoid this naming conflict (`map-plugin-single-x`, `map-plugin-timeline-x`, `map-plugin-split-by-period-x`)
The fix is not yet tested on the Dashboard. Easier to test when this fix is merged. If the fix works, I will also backport to 2.34 and 2.33.

fix: plugin rendering class names (DHIS2-8880)

---

package.json
src/map.js
src/util/analytics.js

2.34 backport of #755 
Fixes: https://jira.dhis2.org/browse/DHIS2-8880
I've tested that the fix works fine in master/v35:

fix: plugin rendering class names 2.34 backport (DHIS2-8880)

---

package.json
webpack.config.js
yarn.lock

Added `dhis2/prop-types` to the list for babel-loader, because it isn't pre-transpiled.  See https://github.com/dhis2/prop-types/issues/143

fix: upgrade headerbar to support translations

---

package.json
src/components/app/App.js

This PR solves an issue with api requests sent from the headerbar in production. The base url is not set properly: 
This fix uses the URL defined here: https://github.com/dhis2/maps-app/blob/v33/src/app.js#L34 (excludes the `/api/xx` part which is added by the app-runtime Provider). 
We're moving away from d2 config, but for 2.33 we can still use it to avoid defining the base url multiple places.

fix: set proper base url for production

---

i18n/en.pot
package.json
src/components/datatable/DataTable.js
src/components/layers/legend/Legend.js

2.32 backport of #786 (excluding the maps-gl update which is not present in this version)

fix: add missing translation strings

---

src/util/favorites.js
src/util/helpers.js

Fixes: https://jira.dhis2.org/browse/DHIS2-9060
This PR fixes an issue reported by HISP India. They we're not allowed to resave the map as they had a constraint in the db that "created" and "lastupdated" could not be NULL (it is likely that other DHIS2 users have this restriction as well). The backend will set all properties to NULL if they are not passed with PUT request. This used to work, and I'm not sure if the backend logic was changed at some time. This could potentially set several fields unintentional to NULL, and @maikelarabori will check it out. Maybe we should switch to a PATCH request?
For Maps, we currently restrict the properties we load and save for a map. We should not change this behaviour for released versions as it might create other bugs. The fix here is to include …

fix: keep created and lastUpdated map properties (DHIS2-9060)

---

src/components/classification/LegendSetSelect.js
src/components/classification/NumericLegendStyle.js
src/components/edit/thematic/ThematicDialog.js
src/components/orgunits/SelectedOrgUnits.js

If the user selects "Predefined color legend" it is also required to select a legend set. 
Fixes: https://jira.dhis2.org/browse/DHIS2-9314

fix: require legend set selection (DHIS2-9314)

---

package.json
src/components/orgunits/OrgUnitLevelSelect.js
src/loaders/thematicLoader.js
yarn.lock

This PR allows org unit levels to be formatted as "LEVEL-uid".
Fixes: https://jira.dhis2.org/browse/TECH-427
DHIS2 Maps has so far used the `LEVEL-x` ("LEVEL-2") format to identify org unit levels, and not `LEVEL-uid` ("LEVEL-wjP19dkFeIk") which is currently used by DV. 
With this PR, Maps will start to use `LEVEL-uid` for new maps created, but a converter is added to support the old format for maps that are already saved. 
This fix should be backported, so I've tried to make the changes minimal. 
The long term plan is to use a shared org unit selection component across the apps.

fix: allow uid to idenitfy org unit levels (TECH-427)

---

src/components/map/MapItem.js
src/map.js

Fixes (hopefully): https://jira.dhis2.org/browse/DHIS2-9315
The problem is that elements get the wrong css classes assigned in production. 
Wit this PR we try to have one common style class, and move the prop based style handling to the style attribute.

fix: map plugin style handling (DHIS2-9315)

---

.eslintignore
package.json
src/app.js
src/components/app/App.js
src/map.js

Use the same web api version as the app version.

chore: upgrade to v35 of web api

---

src/util/infrastructural.js

Infrastructural data (org unit right click -> "Show information") is not showing in Maps master/2.35.0 due to a backend bug. This PR is not fixing the backend issue, but adds some additional checks in case no data is returned from the Web API, resulting in a console error. The PR also fixes a missing period translation string. 
Related issue: https://jira.dhis2.org/browse/DHIS2-9451
Before this fix the dialog will show like this with an error in the console: 
After this fix (and without a backend fix) it will show: 
Backend bug:

fix: additional checks for infrastructural data (DHIS2-9451)

---

src/components/edit/event/EventDialog.js

This PR fixes a bug where the default relative period is set when there are start and end dates that should be used. 
Fixes: https://jira.dhis2.org/browse/DHIS2-9504

fix: don't set default period if start/end dates is set

---

package.json
src/components/map/ThematicLayer.js

This PR avoids setting initial period when rendering strategy is single map. 
Fixes: https://jira.dhis2.org/browse/DHIS2-9543

fix: set single map rendering strategy as default (DHIS2-9543)

---

src/components/periods/StartEndDates.js

Fixes: https://jira.dhis2.org/browse/DHIS2-9592
Before this fix, the date field is removed if the user is entering a date directly - if the date is invalid while typing an empty string is returned would not pass this check 
`return startDate && endDate ?`
The fix was to check for undefined so empty strings will pass.

fix: only remove date field if undefined

---

package.json
src/map.js

This PR fixes an issue with colling class names when having multiple maps on the same dashboard. 
Fixes: https://jira.dhis2.org/browse/DHIS2-9593
The solution is to include an unique map id in the class prefix. The default is to use the id from the analytical object, if undefined, a new id will be generated. 
Including rendering method in the class prefix is obsolete when using unique ids, so it was removed. 
The plan is to only merge this fix to master and test it thoroughly on play dev before backporting. 
This is related to an issue with the styling solution in Material UI described here (mutiple react contexts): 
https://github.com/mui-org/material-ui/issues/8872#issuecomment-340043309
The plan is to stop using Material UI in future versions of DHIS2 Maps.

fix: unique class name prefix for each map plugin item (DHIS2-9593)

---

src/components/edit/trackedEntity/TrackedEntityDialog.js
src/loaders/trackedEntityLoader.js
src/util/teiRelationshipsParser.js

Partly reverts changes from #993 (2. Show TEI relationships outside program)
This functionality was made as a change just before 2.35 soft freeze and not well tested, partly because of limited demo data. 
The code has bugs: https://jira.dhis2.org/browse/DHIS2-9634
It is safer to remove the support for TEI relationships outside program than to fix it just before a major release, as the implementation is quite complex. 
Most of the functionality is kept in code, so it can be enabled again at a later stage.

Remove functionality to show TEI relationships outside program

---

src/util/classify.js
src/util/numbers.js

Fixes: https://jira.dhis2.org/browse/DHIS2-9701
The bug appeared after upgrading the d3-format dependency to the latest version (v2.0.0). In this version the minus sign was changed: https://github.com/d3/d3-format/issues/62
It works in earlier versions which are used in v34 and v33 branches. 
d3-format now uses a minus sign (&#8722;) which returns NaN when using Number() to convert from a string. It would work if hyphen-minus (&#45;) was used. 
The fix was to round the numbers in JavaScript using Math.round, which also allowed us to skip the string to number casting. 
We are still using precisionRound to find the optimal number of decimals. 
Automatic legend with equal intervals:
Automatic legend with equal counts:
Aggregation type = Count:
We should consolidate number formatting across …

fix: allow negative values in legend (DHIS2-9701)

---

src/components/map/ThematicLayer.js

fix: avoid app crash if missing period id (2.35.0 backport)

---

src/components/orgunits/OrgUnitDialog.js
src/components/orgunits/OrgUnitDialogTable.js
src/components/orgunits/__tests__/OrgUnitDialog.spec.js
src/components/orgunits/styles/OrgUnitDialog.module.css
src/components/orgunits/styles/OrgUnitDialogTable.module.css

This PR replaces Material UI components and styles in the org unit dialog (right click an org unit and select "Show information"). The table from @dhis2/ui is used to show infrastructural data. 

chore: switch to material ui to @dhis2/ui for org unit dialog (DHIS2-9699)

---

src/components/core/Tab.js
src/components/core/Tabs.js
src/components/edit/BoundaryDialog.js
src/components/edit/EarthEngineDialog.js
src/components/edit/FacilityDialog.js
src/components/edit/event/EventDialog.js
src/components/edit/thematic/ThematicDialog.js
src/components/edit/trackedEntity/TrackedEntityDialog.js

This PR replaces Material UI tab components with equivalents from @dhis2/ui. Some wrapper components was created to have a single onChange handler which simplifies the code in the layer dialogs. Please note that only the tabs are updated, there are still several Material UI components in the layer dialogs (will be fixed in separate PRs). 
After this PR:

chore: switch to @dhis2/ui tabs (DHIS2-9699)

---

i18n/en.pot
src/components/app/App.js
src/components/edit/LayerEdit.js
src/components/edit/styles/LayerEdit.module.css
src/components/layers/download/DataDownloadDialog.js
src/components/layers/download/DataDownloadDialogActions.js
src/components/layers/download/DataDownloadDialogContent.js
src/components/layers/download/__tests__/DataDownloadDialog.spec.js
src/components/layers/download/__tests__/DataDownloadDialogActions.spec.js
src/components/layers/download/__tests__/DataDownloadDialogContent.spec.js
src/components/layers/download/styles/DataDownloadDialogActions.module.css
src/components/layers/download/styles/DataDownloadDialogContent.module.css
src/components/openAs/OpenAsMapDialog.js
src/components/openAs/styles/OpenAsMapDialog.module.css

The primary focus for this PR is to is to switch from Material UI dialogs to @dhis2/ui modals. There will still be Material UI components within the modals that will be replaced in later PRs. 
The updated components are: 
- Layer dialog (add/edit layer)
- Layer download dialog
- Open as map dialog
There are also som updated translations that originates in a previous PR #1147 
Layer modal after this PR (@dhis2/ui modal and buttons): 
Layer dialog before this PR: 
Open as map modal after this PR (@dhis2/ui modal and buttons): 
Open as map dialog before this PR: 
Layer download modal after this PR (@dhis2/ui modal and buttons): 
In "download state": 
Showing error: 
Layer download before PR: 
There are issues with z-index with this PR, …

chore: switch to @dhis2/ui modals (DHIS2-9699)

---

package.json
yarn.lock

Upgrades the Earth Engine API to the latest version.

fix: ee api upgrade v33

---

src/components/core/DatePicker.js
src/components/core/styles/DatePicker.module.css

This PR switches from MUI TextField to @dhis2/ui InputField for the date picker. We don't yet have a custom date picker so this is still using browser native. 
We also plan to switch to the period selector used in DV, but I don't want to mix that in the MUI -> @dhis2/ui work. 

chore: switch to @dhis2/ui InputField for date picker (DHIS2-9699)

---

src/components/orgunits/styles/OrgUnitDialog.module.css
src/components/periods/PeriodSelect.js
src/components/periods/styles/PeriodSelect.module.css

This PR replaces MUI buttons with @dhis2/ui buttons, and switches to CSS Modules for the period select. 
The tooltip is not showing correctly due to the same placement issue as earlier (which is hopefully fixed when we get rid of all MUI styles, we are not merging to master yet). 
Before: 
Before:

chore: refactor period select to use @dhis2/ui and css modules

---

src/components/core/Checkbox.js
src/components/core/styles/Checkbox.module.css
src/components/download/DownloadDialog.js
src/components/download/__tests__/DownloadDialog.spec.js
src/components/download/__tests__/__snapshots__/DownloadDialog.spec.js.snap
src/components/edit/BoundaryDialog.js
src/components/edit/FacilityDialog.js
src/components/edit/event/EventDialog.js
src/components/edit/styles/LayerDialog.module.css
src/components/edit/thematic/NoDataColor.js
src/components/edit/thematic/ThematicDialog.js
src/components/edit/thematic/styles/NoDataColor.module.css
src/components/edit/trackedEntity/TrackedEntityDialog.js
src/components/filter/FilterSelect.js
src/components/layers/download/EventDownloadInputs.js
src/components/layers/download/__tests__/EventDownloadInputs.spec.js

This PR switches from MUI Checkbox to @dhis2/ui Checkbox.
I decided to keep the wrapper component to avoid a div around every checkbox to apply styles, and to make event handling simpler. 
Some examples after this PR: 
---
---

chore: replace MUI Checkbox with @dhis2/ui Checkbox (DHIS2-9699)

---

src/components/classification/LegendTypeSelect.js
src/components/core/Radio.js
src/components/core/RadioGroup.js
src/components/core/styles/RadioGroup.module.css
src/components/dataElement/TotalsDetailsSelect.js
src/components/edit/thematic/ThematicMapTypeSelect.js
src/components/edit/trackedEntity/PeriodTypeSelect.js
src/components/periods/RenderingStrategy.js

This PR switches from MUI Radio and RadioGroup to @dhis2/ui Radio and FieldGroup.
There is no @dhis2/ui RadioGroup, so I created a wrapper around FieldGroup with onChange prop, so we don't need to add it for each radio. This is similar to what I did for Tab/TabGroup in #1147 
---
---
---

chore: replace MUI Radio with @dhis2/ui Radio (DHIS2-9699)

---

i18n/en.pot
public/index.html
src/components/app/App.js
src/components/map/ContextMenu.js
src/components/map/styles/ContextMenu.module.css

This PR switches from MUI to @dhis2/ui for the context menu, including an overhaul of the code. 
After this PR:
Vertical placement of the context menu is not correct, same issue as before - will hopefully be fixed when we get rid of all MUI styles. We're not merging to master before the popover placement issues are fixed. 
There are no changes in translation file, just a reordering.

chore: refactor context menu to use @dhis2/ui (DHIS2-9699)

---

src/components/map/ContextMenu.js
src/components/map/Popup.css

This PR includes "Show ..." before the earth engine layer name + adds some extra padding above the popup content. 
After this PR:

fix: context menu layer name and popup padding

---

src/components/core/ColorPicker.js
src/components/core/styles/ColorPicker.module.css
src/components/optionSet/OptionSetStyle.js
src/components/optionSet/styles/OptionSetStyle.module.css
src/components/optionSet/styles/OptionStyle.module.css

This PR is a refactoring of the color picker to use popover from @dhis2/ui,  CSS modules and functional components. 
We don't have a color picker in @dhis2/ui, so we are still using the chrome picker from react-color: https://casesandberg.github.io/react-color/
After this PR:
Still a placement issue for the popover, - will fix the issue when all MUI styles are gone.

chore: refactor color picker to use @dhis2/ui and css modules (DHIS2-9699)

---

src/components/edit/trackedEntity/TrackedEntityRelationshipTypeSelect.js
src/components/map/MapLoadingMask.js
src/components/optionSet/OptionSetStyle.js

This small PR is replacing MUI CircularProgress with CircularLoader to @dhis2/ui. ComponentCover and CenteredContent is also used to add a mask and to center the circular loader on the map. 
After this PR:

 chore: refactor circular loaders to use @dhis2/ui (DHIS2-9699)

---

src/components/core/FontStyle.js
src/components/core/styles/FontStyle.module.css
src/components/layers/LayersToggle.js
src/components/layers/styles/LayersToggle.module.css
src/components/layers/toolbar/LayerToolbar.js
src/components/layers/toolbar/LayerToolbarMoreMenu.js
src/components/layers/toolbar/OpacitySlider.js
src/components/layers/toolbar/__tests__/LayerToolbar.spec.js
src/components/layers/toolbar/__tests__/LayerToolbarMoreMenu.spec.js
src/components/layers/toolbar/__tests__/__snapshots__/LayerToolbar.spec.js.snap
src/components/layers/toolbar/__tests__/__snapshots__/LayerToolbarMoreMenu.spec.js.snap
src/components/layers/toolbar/styles/LayerToolbar.module.css
src/components/layers/toolbar/styles/LayerToolbarMore.module.css
src/components/layers/toolbar/styles/OpacitySlider.module.css

This PR refactors the layer toolbar and places where MUI IconButton was used. The main changes are: 
- Switch from MUI to @dhis2/ui (Tooltip, Popover, Menu, MenuItem, Divider)
- There is no Toolbar or IconButton (without an outline) in @dhis2/ui, so they are replaced by styled divs. 
- Inline styles are moved to css modules
- Class components are translated to functional components
The opacity slider still uses MUI, will be fixed in a separate PR. 
There are still issues with the placements of @dhis2/ui components (tooltip and popover menu). Will be fixed in a separate PR after all MUI styles are gone. 
After this PR:

chore: refactor layer toolbar to use @dhis2/ui and css modules (DHIS2-9699)

---

package.json
yarn.lock

Fixes: https://jira.dhis2.org/browse/DHIS2-10071
This PR allows the right click context menu to be closed by clicking the map on dashboard maps.

fix: allow the right click context menu to be closed (DHIS2-10071)

---

package.json
yarn.lock

2.35 backport of: https://jira.dhis2.org/browse/DHIS2-10071
This PR allows the right click context menu to be closed by clicking the map on dashboard maps.

fix: allow the right click context menu to be closed (DHIS2-10071, 2.35 backport)

---

package.json
yarn.lock

2.34 backport of: https://jira.dhis2.org/browse/DHIS2-10071
This PR allows the right click context menu to be closed by clicking the map on dashboard maps.

fix: allow the right click context menu to be closed (DHIS2-10071, 2.34 backport)

---

src/components/map/ContextMenu.js

This PR will remove the "Swap longitude/latitude" and "Relocate" options in the right-click context menu for point facilities. This is blocked by https://jira.dhis2.org/browse/TECH-482 and won't be fixed before 2.35.1 is released. 
The removal will be temporarily if the backend support is added again. 
JIRA: https://jira.dhis2.org/browse/DHIS2-9957

fix: disable relocate options in context menu (DHIS2-9957)

---

src/components/edit/LayerEdit.js
src/components/layers/overlays/AddLayerPopover.js
src/components/legend/Legend.js
src/components/legend/styles/Legend.module.css
src/components/plugin/Legend.js
src/components/plugin/LegendLayer.js
src/epics/externalLayers.js
src/loaders/externalLoader.js
src/util/external.js

Fixes: https://jira.dhis2.org/browse/DHIS2-3201
This PR adds legend support for external layers. The legend can be a predefined in DHIS2, or a url to a legend image. 
This was already supported for external layers in the maintenance app:
Showing a predefined legend and a legend image in the maps app: 
We don't control the design of an external layer image - the max-width is adjusted to the container. 
The same legends shown for a plugin map (dashboard): 
The logic for saving external layers is changed: Before we save the full layer config so we can recreate the layer from the analytical object alone. This is not sufficient when we now start to add additional capabilities to external layers. If the legend is updated this should be reflected on all saved maps using the layer. After this PR …

feat: legend support for external layers (DHIS2-3201)

---

public/plugin.html
src/components/map/MapView.js
src/components/plugin/Plugin.js
src/components/plugin/styles/MapName.module.css
src/components/plugin/styles/Plugin.module.css
src/constants/mapControls.js
src/util/mapControls.js

Fixes: https://jira.dhis2.org/browse/DHIS2-10125
This PR makes the map plugin controls configureable. The default is to only show the zoom control:
The fullscreen control is removed from plugin maps by default. For dashboard maps fullscreen will be handled outside the plugin: https://jira.dhis2.org/browse/DHIS2-9879
For other uses of the plugin, the user can now add the map controls as they like: 
All map controls can be added, not only the fullscreen control. 
Code example:
```
mapPlugin.load({
id: mapId,
el: 'map',
controls: [
{ type: 'zoom' },
{ type: 'fullscreen' },
{ type: 'fitBounds' },
{ type: 'scale', imperial: false },
{ type: 'search' },
{ type: 'measure' },
],
});
```
The legend control is moved to the left side as the number of controls on the right side is no longer constant: …

feat: configurable map controls (DHIS2-10125)

---

package.json
public/plugin.html
src/components/map/Map.js
src/components/map/MapView.js
src/components/map/PeriodName.js
src/components/map/SplitView.js
src/components/plugin/Plugin.js
src/map.js
yarn.lock

Fixes: https://jira.dhis2.org/browse/DHIS2-10252
This PR fixes: 
1. Switch to multitouch for map panning to avoid "scroll trap" on touch screens. This was fixed in maps-gl: https://github.com/dhis2/maps-gl/pull/236
2. Allow map to be resized outside the plugin component. The plugin resize method now has an additional argument: isFullscreen - mapPlugin.resize(el, **isFullscreen**) - if true mouse scroll zoom will be enabled. This is disabled by default to avoid "scroll trap" when scrolling a long dashboard. The old fullscreen handling code is kept to also support the built-in fullscreen control. 
3. Fixed a styling issue for the period labels in split view maps (occured in the MUI-UI transition):
Before:
After: 
I've tested that this worked locally - can be tested fully when this fix is …

fix: allow mouse scroll in fullscreen (DHIS2-10252)

---

src/components/map/Map.js
src/components/map/MapItem.js

Fixes an issue caused by previous PR: https://github.com/dhis2/maps-app/pull/1420
The map scroll zoom should always be available in the app, only in fullscreen for the plugin.

fix: allow map scroll zoom in app

---

src/map.js
src/util/analyticalObject.js
src/util/favorites.js

Fixes: https://jira.dhis2.org/browse/DHIS2-9602
The maps app had two different ways of translating analytical objects (ao) on the dashboard, and when switching from DV to Maps. This PR will unify the way the ao is translated, and use a predefined legend set if associated with the indicator/data element. 
The PR also sets a default layer opacity for the thematic layer created.
Before this PR the dashboard map had an automatic legend while the same ao gets a predefined legend in the app: 
After this PR the plugin/dashboard map will also have predefined legend:

fix: unify translations of analytical objects 

---

package.json
src/components/edit/styles/LayerDialog.module.css
src/components/edit/thematic/styles/NoDataColor.module.css
src/components/map/layers/earthEngine/EarthEnginePopup.js
yarn.lock

This PR contains the following style fixes:
- Wider select fields in layer dialogs.
- Wider checkbox field for no data selection
- Show period in popup on separate line
- Remove focus outline for search popups
After: 
Before: 
After: 
Before: 
After: 
Before: 
After: 
Before:

fix: various style fixes

---

src/components/edit/earthEngine/AggregationSelect.js
src/components/edit/earthEngine/BandSelect.js
src/components/edit/earthEngine/styles/SelectField.module.css

This PR makes the select fields in the EE data tab full width. 
Before:

fix: wider select fields in EE data tab

---

src/components/download/DownloadDialog.js
src/components/download/styles/DownloadLegend.module.css
src/components/map/MapContainer.js
src/components/map/styles/MapContainer.module.css

This PR makes map download work after upgrading to DHIS2 UI. 
Maps can now be downloaded again: 
Legend will not overflow the header bar: 
Before:

fix: map download support and avoid legend overflow

---

src/loaders/earthEngineLoader.js
src/util/earthEngine.js

This PR will make sure the period name is updated when changed in the EE layer dialog. It will also include year when a weekly period is selected.
Before:

fix: update period in legend and include year

---

src/components/edit/earthEngine/EarthEngineDialog.js
src/components/edit/shared/BufferRadius.js
src/reducers/layerEdit.js

This PR will fix two issues with the buffer checkbox and input field: 
- The checkbox can now be unchecked 
- The input field can be empty - allow user to delete the value before typing a new one. 
After this PR:

fix: allow buffer to be unchecked and empty value field

---

i18n/en.pot
src/components/layers/toolbar/LayerToolbarMoreMenu.js
src/components/layers/toolbar/__tests__/LayerToolbar.spec.js
src/components/layers/toolbar/__tests__/__snapshots__/LayerToolbar.spec.js.snap
src/components/legend/Legend.js

This PR will change the layer menu label to "Hide data table" when the table is open. It also includes a fix to open data source links in a new browser tab.
After this PR:

fix: show "hide data tabel" i layer menu when table is open

---

i18n/en.pot
package.json
src/actions/layerEdit.js
src/components/core/NumberField.js
src/components/edit/earthEngine/StyleSelect.js
src/components/layers/toolbar/__tests__/__snapshots__/LayerToolbar.spec.js.snap
src/constants/earthEngine.js
src/loaders/earthEngineLoader.js
src/reducers/layerEdit.js
yarn.lock

Fixes: https://jira.dhis2.org/browse/DHIS2-10582
From the monkey testing: 
- Only show legend preview when the values are valid
- Min, max and step should not reset each other
- Allow steps to be changed with the keyboard
- Number of steps align the the number of colors shown, not the number of steps between min and max
In addition: 
- Show help text when values are missing or not correct
This PR upgrades DHIS2 UI to latest version 6.5.0 - with support for min, max and step values for input fields. This update also solved an issue where the color palette where changed back to default when min, max and steps where changed. 
After this PR when number of steps is reduced the palette is kept: 
Before this PR the palette was changed back to default: 
The PR also allows for …

fix: keep palette and support decimals for EE layers (DHIS2-10582)

---

src/components/edit/earthEngine/AggregationSelect.js
src/components/map/layers/earthEngine/EarthEnginePopup.js
src/constants/aggregationTypes.js
src/constants/earthEngine.js

This PR restrict the aggregation types show for different Earth Engine layers, so we only show those that are relevant
"Count" (number of cells) was removed for all layers. "Sum" was removed from all layers except the two population layers. 
Before: 
The PR also includes a fix so we don't show unit in the popup when only "sum" is selected (confusing for the user). 
Before:

fix: restrict aggregation types shown

---

src/epics/favorites.js

Fixes: https://jira.dhis2.org/browse/DHIS2-10585
To enable all file menu options, the map is now loaded instantly after it is saved. This gives us the map sharing and access setting applied on the server. 
Before this PR
A later optimalisation would be to only load the properties needed, to avoid triggering a reload of the layer data and a redraw of the map.

fix: update file menu when map is saved (DHIS2-10656) 

---

src/loaders/earthEngineLoader.js

This PR will show the error message from the Web API if the org unit selection is wrong: 
This is the same behaviour as we have for other layers. The layer will still load, allowing the user to change the org unit selection. 
Before this PR the layer will not load and no error message is shown to the user:
The error message shown to the user should be improved in a later release.

fix: show error message when org unit selection is wrong

---

src/components/map/layers/Layer.js
src/components/map/layers/earthEngine/EarthEngineLayer.js

This PR makes sure the popup is closed when the context menu is opened. It avoids reopening the popup when the user drills down/up. 
Before:

fix: close popup when context menu is shown

---

i18n/en.pot
src/components/orgunits/OrgUnitDialog.js
src/components/orgunits/styles/OrgUnitDialog.module.css

This PR shows a circular loader while data is loading in the org unit dialog:

fix: show circular loader in org unit dialog

---

src/components/datatable/DataTable.js
src/components/layers/toolbar/LayerToolbarMoreMenu.js
src/components/layers/toolbar/__tests__/__snapshots__/LayerToolbarMoreMenu.spec.js.snap

Fixes an issue where "Hide data table" was showing in all layer menus, and not only for the layer where the table is currently open. 
The PR also includes an extra check of cell value existence when switching between data tables.

fix: hide data table only if table belongs to layer

---

src/components/edit/shared/BufferRadius.js

This PR sets the min buffer radius to 0, and also allows the value 0 to be shown.

fix: set min buffer radius to 0

---

src/components/edit/earthEngine/EarthEngineDialog.js
src/components/edit/earthEngine/PeriodSelect.js
src/util/earthEngine.js

This PR fixes two issues with the period selection for EE layers: 
1. Don't reset year selection to latest value
2 Don't show year twice for landcover

fix: don't reset year selection for ee layers

---

src/loaders/earthEngineLoader.js

This PR fixes an issue where the legend items where not updated when the style params were changed.

fix: update legend items when style params is changed

---

src/loaders/earthEngineLoader.js

For some org unit selections, the features returned don't have geometry (this is the case for top level Sierra Leone in the demo db). 
If only this feature is returned the data features array will be empty. I've added an extra check so we don't pass empty feature arrays. The EE API requires at least on feature in a collection. 
This PR removes this error message: 
and adds this message:

fix: don't pass empty feature array for ee layers

---

src/util/map.js

This PR fixes an issue where parent org unit was not checked in the org unit tree after drill down/up. The fix as to include the org unit path when updating `rows`. 
After this PR:

fix: include org unit path on drill down/up

---

src/loaders/facilityLoader.js

Fixes an issue where name was used before it was defined. It probably worked before because const was transpiled to var.

fix: define name before it's used

---

src/components/layers/toolbar/LayerToolbar.js

Opacity might be missing in older analytical objects.

chore: don't make opacity required in layer toolbar

---

src/map.js

Fixes: https://jira.dhis2.org/browse/DHIS2-10684
The map plugin us created using `NEW`, and it is not working after upgrading the webpack/transpiler setup in #1565
The plugin loads fine after this PR: 

fix: don't use const with arrow function for maps plugin

---

src/map.js

This PR will switch to the DHIS2 UI CircularLoader for the maps plugin:

fix: new circular loader to map plugin

---

src/components/dataItem/CoordinateField.js

Fixes: https://jira.dhis2.org/browse/DHIS2-10721
Two fixes where applied: 
1. Check if the coordinate field exist before selecting it. An invalid value was accepted by Material UI, but not by the DHIS2 UI select field. 
2. Reset the coordinate field if the program is changed. 
I've checked that the coordinate field is kept when a saved map is loaded. 
After this PR:

fix: reset coordinate field on program change

---

src/components/map/MapLoadingMask.js
src/components/map/styles/MapLoadingMask.module.css

Temporarily fixes: https://jira.dhis2.org/browse/DHIS2-10801
This fix in temporary until the favorites dialog (opened from the file menu) is upgraded from MUI to DHIS2 UI. 
The DHIS2 UI  ComponentCover has a z-index of 2000, while the MUI dialog uses 1300. 
As a general rule, we should not uses "!important" to override styles, but it was the only way to change the ordering without creating a custom cover component. 

fix: place map loading mask below favorites dialog (DHIS2-10801)

---

i18n/en.pot
src/constants/layers.js
src/loaders/eventLoader.js

Fixes: https://jira.dhis2.org/browse/DHIS2-10807
Allows us to show more than 50 events in a map layer.  Max number of events loaded by the client is set to 500,000 - we show a warning if the total number is higher. 
After this PR:
(500 is only for illustration, it is 500000)

fix: set max page size for event analytics (DHIS2-10807)

---

src/constants/layers.js

This PR reduces the number of events that can be downloaded in one request to 100k. 
The backend is slow returning more than 100k events due to partitioning. Will be improved in 2.37. 
Maps app can have difficulties showing more than 100k when not clustered.

fix: reduce event page size to 100k

---

package.json
yarn.lock

Some library translations don't load because there were multiple copies of d2-i18n (both cjs and es).  This downgrades d2-i18n to before the es build was included, and upgrades `@dhis2/analytics` to latest in order to ensure translations are loaded correctly.

fix: load all translations by preventing d2-i18n dual package hazard and upgrading dhis2/analytics [DHIS2-10846]

---

package.json
yarn.lock

2.36.0 port of #1628 - critical regression, should be fixed but will run by RCB

fix: [2.36.0] load all translations by preventing d2-i18n dual package hazard and upgrading dhis2/analytics [DHIS2-10846]

---

src/loaders/eventLoader.js

Fixes: https://jira.dhis2.org/browse/DHIS2-10867
Counting the number of events can be heavy for the backend, and should only be performed when needed. We check the event count to decide if the events should be clustered on the server or the client. When the user is "styling by data item" we don't need to check the event count, as this is only supported using client donut clusters. 
"config.bounds" is only needed for server cluster when we zoom the map to the combined bounds of all the events.

fix: don't check event count when styling by data item (DHIS2-10867)

---

src/components/datatable/DataTable.js

Fixes: https://jira.dhis2.org/browse/DHIS2-10872
This PR will include color in the data table for thematic layer. It was present earlier, but a bug from 2.35 removed it. 

fix: show color in data table for thematic layers (DHIS2-10872)

---

webpack.config.js

Fixes: https://jira.dhis2.org/browse/DHIS2-10882
This PR removes the last slash from the default base URL in production. 
The only change is in line 7,  `'production' ? '../'` is changed to `'production' ? '..'`.
The rest is linting (maps still uses semicolons for line ending).

fix: remove slash from base url

---

i18n/en.pot
package.json
src/components/edit/EarthEngineDialog.js
src/components/map/EarthEngineLayer.js
src/epics/earthEngine.js
src/loaders/earthEngineLoader.js
src/reducers/layers.js
yarn.lock

Fixes: https://jira.dhis2.org/browse/DHIS2-10912
This PR will make DHIS2 Maps compatible with the latest @dhis2/maps-gl version (currently 1.8.6). 
The maps-gl code for handling Google Earth Engine layers was improved to support aggregations, and some adjustments to the legend handling was changed at the same time. Although earlier versions (before 2.36) of the maps app don't support EE aggregations the same maps-gl version can be used with this PR. 
The Landcover dataset we used in 2.35 is no longer supported, and this PR changes the dataset to a new version. 
This maps-gl upgrade will also fix the following issues for 2.35: 
- https://jira.dhis2.org/browse/DHIS2-10889
- https://jira.dhis2.org/browse/DHIS2-10734
After this PR the landcover layer shows: 
All donut clusters show on first …

fix: make maps v35 compatible with latest maps-gl version (DHIS2-10912)

---

i18n/en.pot
package.json
src/components/edit/EarthEngineDialog.js
src/components/map/EarthEngineLayer.js
src/epics/earthEngine.js
src/loaders/earthEngineLoader.js
src/reducers/layers.js
yarn.lock

Fixes: https://jira.dhis2.org/browse/DHIS2-10912
This PR will make DHIS2 Maps compatible with the latest @dhis2/maps-gl version (currently 1.8.6). 
The maps-gl code for handling Google Earth Engine layers was improved to support aggregations, and some adjustments to the legend handling was changed at the same time. Although earlier versions (before 2.36) of the maps app don't support EE aggregations the same maps-gl version can be used with this PR. 
The Landcover dataset we used in 2.34 is no longer supported, and this PR changes the dataset to a new version. 
This maps-gl upgrade will also fix the following issues for 2.34: 
- https://jira.dhis2.org/browse/DHIS2-10889
- https://jira.dhis2.org/browse/DHIS2-10734
After this PR the landcover layer shows: 
All donut clusters show on first …

fix: make maps v34 compatible with latest maps-gl version (DHIS2-10912)

---

i18n/en.pot
package.json
src/components/edit/EarthEngineDialog.js
src/epics/earthEngine.js
src/loaders/earthEngineLoader.js
src/reducers/layers.js

Fixes: https://jira.dhis2.org/browse/DHIS2-10912
The Landcover dataset we used in 2.33 is no longer supported, and this PR changes the dataset to a new version.
Note that we have improved the Earth Engine code in 2.36, and the dataset id 'MODIS/006/MCD12Q1' is no longer at multiple places in the code. This si not backported as it required a large refactor. 
After this PR the landcover layer shows:

fix: upgrade landcover dataset in maps v33 (DHIS2-10912)

---

i18n/en.pot
package.json
src/components/edit/EarthEngineDialog.js
src/epics/earthEngine.js
src/loaders/earthEngineLoader.js
src/reducers/layers.js

Fixes: https://jira.dhis2.org/browse/DHIS2-10912
The Landcover dataset we used in 2.32 is no longer supported, and this PR changes the dataset to a new version.
Note that we have improved the Earth Engine code in 2.36, and the dataset id 'MODIS/006/MCD12Q1' is no longer at multiple places in the code. This si not backported as it required a large refactor. 
After this PR the landcover layer shows:

fix: upgrade landcover dataset in maps v32 (DHIS2-10912)

---

i18n/en.pot
src/components/classification/NumericLegendStyle.js
src/components/dataItem/StyleByDataItem.js
src/components/edit/event/EventDialog.js

Fixes: https://jira.dhis2.org/browse/DHIS2-10821
This PR makes it required to select a legend set, if predefined legend is selected for "style by data item" for event layer. It will autoselect the legend set associated with the data item, also when the user is switching between automatic and predefined legends. 
This error will only show if the data item don't have a legend set defined, and no selection is made. 
Previously, the legend set select would be empty when switching back from automatic.

fix: set default legend set for event layers (DHIS2-10821)

---

package.json
src/components/download/DownloadDialog.js
src/components/map/MapContainer.js

Fixes: https://jira.dhis2.org/browse/DHIS2-11143
This PR will exclude the attribution toggle button from the map download, as it's not supported by the dom-to-image dependency. It will have no effect for the map download, as the toggle button is not used in this mode. 
After this PR:

fix: exclude attribution toggle button from map download

---

package.json
src/components/download/DownloadDialog.js
src/components/map/MapContainer.js

Fixes: https://jira.dhis2.org/browse/DHIS2-11143
2.35.4 backport of #1712

fix: exclude attribution toggle button from map download (DHIS2-11143)

---

README.md
cypress/elements/boundary_layer.js
cypress/elements/event_layer.js
cypress/elements/facility_layer.js
cypress/elements/layer.js
cypress/elements/thematic_layer.js
cypress/fixtures/example.json
cypress/integration/layers/boundarylayer.cy.js
cypress/integration/layers/eventlayer.cy.js
cypress/integration/layers/facilitylayer.cy.js
cypress/integration/layers/thematiclayer.cy.js
cypress/support/extendedTimeout.js
src/components/core/SelectField.js
src/components/edit/FacilityDialog.js
src/components/indicator/IndicatorSelect.js
src/components/layers/overlays/AddLayerButton.js
src/components/orgunits/OrgUnitGroupSetSelect.js
src/components/program/ProgramSelect.js
src/components/program/ProgramStageSelect.js

Test adding map layers. It does not yet test the actual rendered map.
The files in the /elements folder are a first attempt at page objects. They are classes that hide complexity of interacting with the page so that the actual tests in the /integration folder read nicely. Most methods in the page objects return `this` so that the tests can chain the methods.
I'm not generally a big fan of complex class inheritance, but in the case of the page object layers, it made sense to me. Open to other ideas though.

chore: tests for adding map layers

---

package.json
src/components/download/DownloadDialog.js
src/components/map/MapContainer.js

Fixes: https://jira.dhis2.org/browse/DHIS2-11143
2.34 backport of #1712
This PR will exclude the attribution toggle button from the map download, as it's not supported by the dom-to-image dependency. It will show the text attribution instead.

fix: exclude attribution toggle button from download (DHIS2-11143)

---

package.json
src/util/i18n.js
src/util/periods.js
src/util/time.js
yarn.lock

Fixes for 2.35: https://jira.dhis2.org/browse/DHIS2-11335
DHIS2 uses underscore to define locales, while the browser/JS APIs use hyphen (BCP 47). This PR will replace underscores with hyphens before the locale is passed to ECMAScript Internationalization API. 
Avoids a crash when opening the interpretations panel with a locale with language_country format
See dhis2/d2-ui#700
After this PR with interface language set to "Arabic (Iraq)":

fix: use hyphen in locale strings passed to the browser(DHIS2-11335)

---

package.json
src/util/time.js
yarn.lock

Fixes for 2.36: https://jira.dhis2.org/browse/DHIS2-11335
DHIS2 uses underscore to define locales, while the browser/JS APIs use hyphen (BCP 47). This PR will replace underscores with hyphens before the locale is passed to ECMAScript Internationalization API.
Avoids a crash when opening the interpretations panel with a locale with language_country format
See dhis2/d2-ui#700
After this PR with interface language set to "Arabic (Iraq)":

fix: use hyphen in locale strings passed to the browser 2.36 backport (DHIS2-11335)

---

package.json
src/constants/periods.js
src/util/periods.js
src/util/time.js
yarn.lock

Fixes for 2.34: https://jira.dhis2.org/browse/DHIS2-11335
DHIS2 uses underscore to define locales, while the browser/JS APIs use hyphen (BCP 47). This PR will replace underscores with hyphens before the locale is passed to ECMAScript Internationalization API.
Avoids a crash when opening the interpretations panel with a locale with language_country format
See dhis2/d2-ui#700
After this PR with interface language set to "Arabic (Iraq)":

fix: use hyphen in locale strings passed to the browser 2.34 backport (DHIS2-11335)

---

package.json
src/util/time.js
yarn.lock

Fixes in master: https://jira.dhis2.org/browse/DHIS2-11335
DHIS2 uses underscore to define locales, while the browser/JS APIs use hyphen (BCP 47). This PR will replace underscores with hyphens before the locale is passed to ECMAScript Internationalization API.
Avoids a crash when opening the interpretations panel with a locale with language_country format
See dhis2/d2-ui#700
After this PR with interface language set to "Arabic (Iraq)":

fix: use hyphen in locale strings passed to the browser (DHIS2-11335)

---

src/util/infrastructural.js

Fixes: https://jira.dhis2.org/browse/DHIS2-11433
The bug appeared after switching to period generators from @dhis2/analytics in #1734 
For the new period generators the period type needs to be in uppercase, and this was not changed for the infrastructural data (organisation unit dialog). 
Before:

fix: period type in uppercase (DHIS2-11433)

---

package.json
src/components/download/DownloadDialog.js
src/components/map/styles/Popup.css
src/components/orgunits/RelocateDialog.js
yarn.lock

Fixes: https://jira.dhis2.org/browse/DHIS2-11406
This PR upgrades to @dhis2/maps-gl 2.0.0 where mapbox-gl is replaced by maplibre-gl: https://github.com/dhis2/maps-gl/pull/374
Some class names had to be changed from "mapboxgl-" to "maplibregl-".

feat: switch from mapbox-gl to maplibre-gl

---

src/constants/settings.js

This PR will upgrade the Web API version to 37 for DHIS2 Maps master.

fix: upgrade web api version to 37

---

src/components/orgunits/OrgUnitInfo.js
src/components/orgunits/__tests__/OrgUnitInfo.spec.js

Improves: https://jira.dhis2.org/browse/DHIS2-11178
This PR will only show opening/closed date in the org unit profile if the selected unit is a point facility. "Opening date" is a mandatory field for all org units, but they don't apply to district levels. 

fix: only opening/closed dates if org unit is a point facility

---

i18n/en.pot
src/components/edit/BoundaryDialog.js
src/components/edit/FacilityDialog.js
src/components/edit/shared/Labels.js
src/components/edit/thematic/ThematicDialog.js
src/components/map/layers/BoundaryLayer.js
src/components/map/layers/FacilityLayer.js
src/components/map/layers/ThematicLayer.js
src/util/labels.js

Partly implements: https://github.com/dhis2/maps-app/pull/1720
This PR refactors and unifies how we handle map labels in DHIS2 Maps. A lot of code was duplicated across different layer types, and is now reused. 
A separate Labels component was created and shared between Thematic, Boundary and Facility layers. 
Boundary layers will now have the same font styling options as other layers. 
Thematic layer after this PR: 
This is the same as before. 
Facility layer after this PR: 
Before (only layout change): 
Boundary layer after this PR: 
Before (not possible to change font color and set bold style): 
Boundary map after this PR: 
Before it was not possible to set font color and bold style.

fix: unify map label handling

---

.github/workflows/dhis2-verify-app.yml

dboard-dev-e2e is down, so use dev for cypress tests for now.

fix: use debug/dev for now until test instance is fixed

---

src/util/api.js

This PR fixes an issue with new configuration endpoints in 2.37: 
https://debug.dhis2.org/dev/api/37/configuration/facilityOrgUnitLevel
https://debug.dhis2.org/dev/api/37/configuration/facilityOrgUnitGroupSet
If the config is not set, it returns an empty body, which gives an error when we use response.json()
This fix checks if the response is an empty string before trying to parse it. 
I found the solution on https://stackoverflow.com/a/51320025
@larshelge is this empty response by design?

fix: check if response body is empty

---

src/loaders/earthEngineLoader.js
src/util/earthEngine.js

Fixes: https://jira.dhis2.org/browse/DHIS2-11749
We slightly changed the config syntax for Earth Engine layers in 2.36, and there are some EE datasets we no longer support as they are not updated. There are some issues for maps saved before 2.36 as they still have the old syntax. We could update these in a db update script, but for now it was easier to add some checks in the app. 
All layers load before this fix, but the period is not shown in the map legend, and it is not possible to change the period in DHIS2 Maps. This PR fixes both issues. We still allow deprecated layers (e.g. "Nightime lights") to be edited, if they are created in a previous version of DHIS2 Maps.
For the Sierra Leone demo database, the fix applies to the following maps:
- Malaria: LLITN coverage and rainfall EE
- …

fix: backward compatibility for EE layers 

---

package.json
src/components/groupSet/GroupSetStyle.js
src/components/groupSet/styles/GroupSetStyle.module.css
src/util/orgUnits.js
yarn.lock

This PR fixes the following issues for facility layer: 
- Upgrades maps-gl dependency with symbol opacity fix https://github.com/dhis2/maps-gl/pull/395
- Extra space above the group set preview 
- More bullet proof fallback symbols and colors
- Made the fallback colors more distinguishable
Colors and icon symbols for org unit groups sets needs to be set the maintenance app, but we support some simple fallbacks.
For icon symbols the fallback is colored circles. The icon set we have used for a long time only contains 5 color circles. This PR makes sure we select one of those. If there are more than 5 groups without symbols, the same color circle is used. 
Same with colors except that we have unlimited number of colors: If a group is not having a color set, we will pick from our 12 …

fix: facility layer and group set styling improvements

---

src/components/legend/styles/LegendItem.module.css
src/loaders/trackedEntityLoader.js

This PR includes some style fixes for tracked entity layer legends: 
- the legend item symbols are center aligned
- "focus area" is represented by a polygon, not point
Before: 
Before:

fix: align tracked entity legend and use polygon symbol for areas

---

i18n/en.pot
src/components/core/Checkbox.js
src/components/core/FontStyle.js
src/components/core/Radio.js
src/components/core/SelectField.js
src/components/core/styles/FontStyle.module.css
src/components/edit/FacilityDialog.js
src/components/edit/event/EventDialog.js
src/components/edit/orgUnit/OrgUnitDialog.js
src/components/edit/shared/BufferRadius.js
src/components/edit/shared/Labels.js
src/components/edit/shared/styles/BufferRadius.module.css
src/components/edit/styles/LayerDialog.module.css
src/components/edit/trackedEntity/TrackedEntityDialog.js
src/components/orgunits/styles/OrgUnitProfile.module.css
src/components/periods/styles/PeriodSelect.module.css
src/constants/layers.js
src/loaders/orgUnitLoader.js

Fixes: 
- Org unit layer: "No org units found" -> "No coordinates found"
- When select user org group - deselect level and group (across all layer types)
- Add min and max for radius and label size (across all layer types)
- Org unit profile: align close x
- Org unit profile: make sure next/prev year buttons always are aligned (change browser zoom)
- Org unit layer: Change "Color" to "Boundary colour", and add more space above
- Faciliy layer: Move color and point radius below "Style by group set"
- Checkbox and Radio buttons: add dense property
- Add buffer input field on a separate line (to better support long text translations)
After this PR:
Before: 
Before: 
After this PR ('x' moved 1 px down):
Before: 
Before: 
After this PR:
Before: 
After this PR: …

fix: improvements to facility and org unit layers

---

package.json
src/components/legend/LegendItem.js
src/components/map/layers/EventLayer.js
src/loaders/eventLoader.js
yarn.lock

This PR will add a contrasting stroke and cluster count color for events. If the event color is dark, the stroke/vount color will be bright, and opposite. Stroke will only be used for single color maps, not when events that are "styled by data item". 
Storke is also added to the legend item, and legend item is added for server cluster (see screenshot below). 
Depends on https://github.com/dhis2/maps-gl/pull/398
Before:

fix: constrasting event stroke and cluster count color

---

src/components/edit/styles/LayerDialog.module.css
src/components/orgunits/styles/OrgUnitTree.module.css

Fixes: https://github.com/dhis2/maps-app/pull/1862
This PR makes the layer dialog 20 px higher to avoid vertical scroll. The org unit tree selection is made 40 px higher to better fit the space available. 
After this PR:
Before: 
Before:

fix: make layer dialog higher to avoid vertical scroll (DHIS2-11038)

---

src/components/orgunits/OrgUnitProfile.js

This PR will add a circular loader to the org unit profile:

fix: add loading spinner to org unit profile

---

src/components/download/styles/DownloadLegend.module.css
src/loaders/trackedEntityLoader.js

This PR will improve the legend shown on downloaded maps: 
- Same max width as the left column legend in the maps app
- Include title for TEI layers
- Increased space between title and period
Before:

fix: improved map download legend

---

src/components/periods/styles/PeriodSelect.module.css

This PR will align the period stepper buttons with the selection field. 
Before:

fix: period stepper buttons alignment

---

src/components/edit/event/EventDialog.js

Fixes: https://jira.dhis2.org/browse/DHIS2-11919
This PR makes sure that the default start/end dates are only set once. 
After this PR the date in the layer dialog is the same as layer card: 
Before the dates are noe equal:

fix: keep start/end dates for event layer (DHIS2-11919)

---

src/reducers/layerEdit.js

Fixes: https://jira.dhis2.org/browse/DHIS2-11920
This PR makes sure the style by data item is removed when program (+stage) is changed for event layers. It avoids an app crash. 
After this PR:

fix: remove style data item on program change (DHIS2-11920)

---

i18n/en.pot
src/loaders/facilityLoader.js
src/loaders/orgUnitLoader.js

Fixes: https://jira.dhis2.org/browse/DHIS2-11922
This PR fixes a bug where layer titles were not shown in the map legend on dashboards. 
Before:

fix: include legend title for facility and org unit layers (DHIS2-11922)

---

package.json
yarn.lock

Improves: https://jira.dhis2.org/browse/DHIS2-12013
The maps-gl upgrade include two small fixes that are already approved:
**Don't update auth library for earth engine api**
We don't need to update the Google authentication library when we set the token for the EE API. This small change will remove two Google requests. https://github.com/dhis2/maps-gl/pull/414
**Only reference image scale on the server**
The image scale value is only used in server processing, and we don't need to get the value on the client side. https://github.com/dhis2/maps-gl/pull/416

fix: maps-gl upgrade with earth engine fixes

---

src/loaders/eventLoader.js
src/loaders/thematicLoader.js
src/loaders/trackedEntityLoader.js
src/util/__tests__/time.spec.js
src/util/time.js

fixes: https://jira.dhis2.org/browse/DHIS2-12169
If a string with this format "2018-10-01" is passed to javascript Date, the assumed time is "00:00" and the returned date will be according to the user's timezone. So if you are in <= GMT-1, then the resulting date will actually be the previous day. To avoid this, the date string is converted to an array, and Date converts this correctly.
The screenshot shows the Layer card with the incorrect date shown (note that the analytics request uses the correct date)
Fixed:
https://user-images.githubusercontent.com/6113918/142910473-5506abaa-ddb2-48e4-bbaa-6e996497e007.mov

fix: parse date string to array to get correct date in all timezones

---

package.json

2.36 backport of https://github.com/dhis2/maps-app/pull/1956

chore: allow core app override 2.36

---

package.json
yarn.lock

2.37 backport of https://github.com/dhis2/maps-app/pull/1956

chore: allow core app override 2.37

---

src/loaders/earthEngineLoader.js

2.35 backport of #1848
This PR makes sure that we show the period for EE layers saved with a different format.
Before:

fix: backward compability for EE layers (DHIS2-11749, 2.35 backport)

---

i18n/en.pot
src/components/core/SelectField.js
src/components/edit/earthEngine/BandSelect.js
src/components/edit/earthEngine/EarthEngineDialog.js
src/components/legend/Legend.js
src/components/map/layers/earthEngine/EarthEnginePopup.js
src/components/map/layers/earthEngine/styles/EarthEnginePopup.module.css
src/constants/aggregationTypes.js
src/loaders/earthEngineLoader.js

Fixes: https://jira.dhis2.org/browse/DHIS2-11039
Depends on this PR in maps-gl: https://github.com/dhis2/maps-gl/pull/422
Will be merged to the EE web worker refactor PR in maps-app: https://github.com/dhis2/maps-app/pull/1931
This PR will show aggregation values for each age/gender groups for the population layer. Currently we only show the aggregated values for all age/gender groups combined.
After this PR:
Before: 
If only one group is selected after this PR:
Before: 
This PR also adds a restriction to select max 10 groups (selecting more will result in very long response time from EE API):
Aggregated values for each age/gender group will not show in the data table, as there is no room with the current layout: 
Support can be added by having expandable rows - which is included in: …

Show aggregate values for each age group (DHIS2-11039)

---

cypress/integration/systemsettings.cy.js
package.json
yarn.lock

Fixes: https://jira.dhis2.org/browse/DHIS2-12276
This PR is only upgrading the maps-gl dependency. The issue was fixed in https://github.com/dhis2/maps-gl/pull/425

fix: only preload earth engine aggregations if org units are passed (DHIS2-12276)

---

src/components/core/DatePicker.js
src/components/core/styles/DatePicker.module.css
src/components/periods/StartEndDates.js

Backport of #1925
Fixes https://jira.dhis2.org/browse/DHIS2-11934
Controlled input type date components are problematic because of the way date validation is handled by the native element.
Use an uncontrolled input component, pass in a default value, and use onBlur instead of onChange to set the date value in the redux store.
Styles are copied from dhis2/ui input.

fix: use native input instead of dhis2/ui input in order to correctly validate manually entered dates [v36] 

---

src/loaders/eventLoader.js
src/loaders/thematicLoader.js
src/loaders/trackedEntityLoader.js
src/util/__tests__/time.spec.js
src/util/time.js

Backport of https://github.com/dhis2/maps-app/pull/1937
fixes: https://jira.dhis2.org/browse/DHIS2-12169
If a string with this format "2018-10-01" is passed to javascript Date, the assumed time is "00:00" and the returned date will be according to the user's timezone. So if you are in <= GMT-1, then the resulting date shown in the card will actually be the previous day (though the analytics request does use the correct date, so the data is correct). 
The fix is to convert the date string to an array, and Date converts this correctly.

fix: parse date string to array to get correct date in all timezones [v37]

---

src/loaders/eventLoader.js
src/loaders/thematicLoader.js
src/loaders/trackedEntityLoader.js
src/util/__tests__/time.spec.js
src/util/time.js

Backport of #1937 
fixes: https://jira.dhis2.org/browse/DHIS2-12169
If a string with this format "2018-10-01" is passed to javascript Date, the assumed time is "00:00" and the returned date will be according to the user's timezone. So if you are in <= GMT-1, then the resulting date shown in the card will actually be the previous day (though the analytics request does use the correct date, so the data is correct).
The fix is to convert the date string to an array, and Date converts this correctly

fix: parse date string to array to get correct date in all timezones [v36]

---

src/loaders/eventLoader.js
src/loaders/thematicLoader.js
src/loaders/trackedEntityLoader.js
src/util/__tests__/time.spec.js
src/util/time.js

Backport of #1937
fixes: https://jira.dhis2.org/browse/DHIS2-12169
If a string with this format "2018-10-01" is passed to javascript Date, the assumed time is "00:00" and the returned date will be according to the user's timezone. So if you are in <= GMT-1, then the resulting date shown in the card will actually be the previous day (though the analytics request does use the correct date, so the data is correct).
The fix is to convert the date string to an array, and Date converts this correctly

fix: parse date string to array to get correct date in all timezones [v35]

---

src/components/layers/overlays/OverlayCard.js
src/components/map/layers/Layer.js
src/components/map/layers/OrgUnitLayer.js
src/util/analyticalObject.js

Fixes: https://jira.dhis2.org/browse/DHIS2-12462
This PR fixes 3 issues only present in master: 
- Run updateLayer method in the layer scope
- Remove "removeLayer" method of org unit layer (we don't use the click event anymore)
- Set the correct base url when open as chart

fix: layer scope, data table filter and open as chart base url (DHIS2-12462)

---

src/components/layers/toolbar/LayerToolbarMoreMenu.js
src/components/legend/Legend.js
src/components/map/MapLoadingMask.js
src/constants/earthEngine.js
src/reducers/aggregations.js

Implements: https://jira.dhis2.org/browse/DHIS2-12464
Included in this PR:
- Disable "Download data" from layer toolbar until aggregated values are returned (screenshot below). 
- Clear current aggregation data when an EE layer is updated. Will trigger a loading spinner in the data table (see screen recording below).
- Add translucent mask while Earth Engine layers are loading. I tried to remove the mask to allow user interactions, but it had some side effects: If the users navigates a map there will be a sudden change of view when the layer is loaded. Better to keep the mask for now, and make it visible. 
- Remove ":" after "Group" in legend
- Order default aggregations so the mose useful one is shown first

feat: improved handling of earth engine layers

---

src/components/datatable/ResizeHandle.js

Partly fixes: https://jira.dhis2.org/browse/DHIS2-12483
This PR makes sure that the table will not resize after dragging the handle stopped. 
I've not been able to find a solution to the globe cursor issue in chrome. As we have more pressing issues, I don't plan to spend more time on looking for a solution :-)

fix: disable data table dragging after handle is released (DHIS2-12483)

---

src/loaders/earthEngineLoader.js

Fixes: https://jira.dhis2.org/browse/DHIS2-12504
This PR will make sure the API error message is displayed when the org unit selection is invalid:

fix: display api error when org unit selection is invalid (DHIS2-12504)

---

src/components/layers/toolbar/LayerToolbarMoreMenu.js
src/components/map/layers/earthEngine/EarthEngineLayer.js

Fixes: https://jira.dhis2.org/browse/DHIS2-12475
This PR fixes two issues: 
- When no aggregation types are selected (empty array) we will no longer show an error, but show a map without aggregating for each org unit. 
- When no org units are selected, "Download data" will be disabled in the layer more menu. 
Download is disabled when no aggregation types are selected: 
Download is disabled when no org units are selected: 
Download is disabled when the layer is loading: 
Download is enabled when aggregations and org units are selected + the layer has loaded:

fix: handle no aggregation types or no org units for Earth Engine layers (DHIS2-12475)

---

i18n/en.pot
package.json
src/components/map/MapApi.js
src/components/map/layers/earthEngine/EarthEngineLayer.js
src/components/map/layers/earthEngine/EarthEnginePopup.js
src/util/earthEngine.js
yarn.lock

Fixes for Maps 2.37: https://jira.dhis2.org/browse/DHIS2-12013
With this PR we use the new Earth Engine web worker for DHIS2 Maps 2.37. 
It is a minimal backport of https://github.com/dhis2/maps-app/pull/1931
The PR also includes a backport of:
https://jira.dhis2.org/browse/DHIS2-12506
EE layer loaded with through the web worker:

fix: use EE Web Worker in DHIS2 Maps 2.37 (DHIS2-12013)

---

i18n/en.pot
package.json
src/components/map/MapApi.js
src/components/map/layers/earthEngine/EarthEngineLayer.js
src/components/map/layers/earthEngine/EarthEnginePopup.js
src/util/earthEngine.js
yarn.lock

Fixes for Maps 2.36: https://jira.dhis2.org/browse/DHIS2-12013
With this PR we use the new Earth Engine web worker for DHIS2 Maps 2.36.
It is a minimal backport of #1931
The PR also includes a backport of:
https://jira.dhis2.org/browse/DHIS2-12506
EE layer loaded with through the web worker in Maps 2.36:

fix: use EE Web Worker in DHIS2 Maps 2.36 (DHIS2-12013)

---

src/components/layers/toolbar/LayerToolbarMoreMenu.js
src/components/map/layers/earthEngine/EarthEngineLayer.js
src/components/orgunits/styles/UserOrgUnitSelect.module.css
src/loaders/earthEngineLoader.js

Fixes for DHIS2 Maps 2.37: 
https://jira.dhis2.org/browse/DHIS2-12475
https://jira.dhis2.org/browse/DHIS2-12504
2.37 backport of https://github.com/dhis2/maps-app/pull/2018 and https://github.com/dhis2/maps-app/pull/2016
This PR also fixes a smal style issue: Filled style for user org unit levels.
Before:

fix: handle no aggregation types or no org units for Earth Engine layers (DHIS2-12475, 2.37 backport)

---

src/components/datatable/ResizeHandle.js

Partly fixes: https://jira.dhis2.org/browse/DHIS2-12483
2.36 backport of #2012

fix: disable data table dragging after handle is released (DHIS2-12483, 2.36 backport)

---

src/components/datatable/ResizeHandle.js

Partly fixes: https://jira.dhis2.org/browse/DHIS2-12483
2.35 backport of #2012

fix: disable data table dragging after handle is released (DHIS2-12483, 2.35 backport)

---

i18n/en.pot
src/constants/earthEngine.js

This PR will use male/female instead of men/women for the population age group layer. Male/female is more commonly used as category options in DHIS2. 
After this PR:

fix: use male/female instead of men/women

---

.github/workflows/dhis2-verify-app.yml
cypress/integration/layers/thematiclayer.cy.js
package.json
yarn.lock

Fixes for 2.37.3:  https://jira.dhis2.org/browse/DHIS2-12583
Approved in: https://github.com/dhis2/maps-gl/pull/436

fix: make sure map is present before removing layers and source (DHIS2-12583)

---

src/loaders/facilityLoader.js
src/util/orgUnits.js

Fixes for facility layer: https://jira.dhis2.org/browse/DHIS2-12504
This PR avoids and infinitive loading spinner when the backend api reports an invalid org unit selection. 
After this PR we will show the error message from the backend and the user is able to change the layer settings: 
Before this PR an infinite spinner was shown and it was not possible to change the layer settings:

fix: improved error handling for facility layers (DHIS2-12504)

---

src/components/legend/LegendItem.js
src/components/legend/PolygonSymbol.js

This PR will make it possible to show a filled polygon in the map legend. 
Partly fixes: https://jira.dhis2.org/browse/DHIS2-11969
The "OutlineSymbol" component has been renamed to "PolygonSymbol" and a new fill property was added. 
It is backward compatible so it still shows as a boundary outline for org unit layers: 
It will allow us to apply a fill color for the upcoming catchement area support:

fix: polygon legend item (DHIS2-11969)

---

src/components/datatable/DataTable.js
src/util/filter.js

This PR will make sure that an org unit only is displayed once in the data table. 
Partly fixes: https://jira.dhis2.org/browse/DHIS2-11969
When we introduce catchment areas we the same org unit will be represented by to features - one having the original org unit geometry, and the other having an associated geometry (catchment area, polygon). 
Do avoid duplicate rows in the data table (except the geometry) we will only show one of the features. When the user is hovering an org unit in the data table - we will highlight both features in the map through https://github.com/dhis2/maps-gl/pull/447
With this PR org units will not be duplicated in the data table: 
Without this fix org units would show like this:

fix: remove duplicate org units from data table (DHIS2-11969)

---

src/components/datatable/DataTable.js
src/components/edit/FacilityDialog.js
src/components/orgunits/OrgUnitGeometryAttributeSelect.js
src/loaders/earthEngineLoader.js
src/loaders/orgUnitLoader.js
src/reducers/layerEdit.js
src/util/filter.js
src/util/orgUnits.js

Fixes: https://jira.dhis2.org/browse/DHIS2-11969
This PR contains some code improvements:
- Org units having additional geometry (catchment area) are marked, and this property is used to exclude them from the data table. 
- 'none' is now a constant. 
- Facilities having additional geometry displayed get a smaller radius for the point showing the location (ORG_UNIT_RADIUS_SMALL).

fix: catchment areas fixes (DHIS2-11969)

---

src/constants/basemaps.js

This PR will switch back to the OSM Light basemap using image tiles. We will only support vector tiles as external layer in this release. There are not enough benefits for the switch, and less performant when we need to redraw all map layers if the user is switching to/from a vector style. 
With this PR the default basemap is OSM Light image tiles:

fix: switch back to default image tiles basemap

---

src/components/datatable/DataTable.js
src/components/layers/toolbar/LayerToolbarMoreMenu.js
src/components/layers/toolbar/__tests__/__snapshots__/LayerToolbarMoreMenu.spec.js.snap

Fixes: https://jira.dhis2.org/browse/DHIS2-12800
This PR will disable data table and download options from the layer menu if no org units are selected. The download data option will only be enabled if the layer is finished loading. 
After this PR if no org units are selected for an EE layer:

fix: disable data table if no org units are selected (DHIS2-12800)

---

i18n/en.pot
src/components/edit/FacilityDialog.js
src/components/edit/earthEngine/StyleTab.js
src/components/edit/shared/BufferRadius.js
src/components/edit/shared/styles/BufferRadius.module.css

With this PR we will show an explanation when buffer is disabled due to associated geometry:

fix: show explanation when buffer is disabled

---

src/util/map.js

This PR will filter out GeoJSON polygons that have no coordinates `[[]]`. 
After this PR no error shows when selecting catchment areas in Kailahun:

fix: filter out invalid geojson

---

cypress/elements/layer.js
cypress/integration/layers/orgunitlayer.cy.js
src/components/map/layers/earthEngine/EarthEngineLayer.js

This PR fixes two issues for the new buildings layer:
1. While we show an error from the Earth Engine API the map can still be clicked. 
2. The popup loading spinner is removed if we get an error, as data will never arrive. 
After this PR:

fix: allow popups for buildings layer while showing an error

---

i18n/en.pot
src/constants/eventStatuses.js

This PR will remove event statuses that are not supported in analytics tables:
- Schedule
- Overdue
- Skipped
After this PR:

fix: remove unused event statuses

---

cypress/elements/layer.js
cypress/integration/layers/orgunitlayer.cy.js
src/loaders/thematicLoader.js

With this PR we will show a warning if the user has selected to show "assoicated geometries", but there are no geometries found for selected org units. We also allow multiple warnings to be shown at the same time.

fix: show warning if no catchment areas for thematic layer

---

src/components/datatable/DataTable.js
src/components/layers/toolbar/LayerToolbarMoreMenu.js
src/components/layers/toolbar/__tests__/__snapshots__/LayerToolbarMoreMenu.spec.js.snap

Fixes for 2.37: https://jira.dhis2.org/browse/DHIS2-12800
2.37 backport of: https://github.com/dhis2/maps-app/pull/2075
This PR will disable data table and download options from the layer menu if no org units are selected. The download data option will only be enabled if the layer is finished loading.

fix: disable data table if no org units are selected (DHIS2-12800, 2.37 backport)

---

src/components/datatable/DataTable.js
src/components/layers/toolbar/LayerToolbarMoreMenu.js
src/components/layers/toolbar/__tests__/__snapshots__/LayerToolbarMoreMenu.spec.js.snap

Fixes for 2.36: https://jira.dhis2.org/browse/DHIS2-12800
2.36 backport of: https://github.com/dhis2/maps-app/pull/2075
This PR will disable data table and download options from the layer menu if no org units are selected. The download data option will only be enabled if the layer is finished loading.

fix: disable data table if no org units are selected (DHIS2-12800, 2.36 backport)

---

package.json
yarn.lock

Use latest maps-gl in DHIS2 Maps 2.26. 
Includes fix for: https://jira.dhis2.org/browse/DHIS2-12196

fix: maps-gl upgrade v36 (DHIS2-12196)

---

src/components/layers/toolbar/LayerToolbarMoreMenu.js

Fixes: https://jira.dhis2.org/browse/DHIS2-12475
This PR will disable data table option from the layer menu if: 
1. There are no org units selected, and
2. It is not an earth engine layer OR the earth engine layer has no aggregated data
The download option will be disabled if: 
1. Same conditions as above, OR
2. The earth engine aggregated data is still loading
After this PR for EE layers: 
Aggregations and org units are selected:
No aggregations are selected: 
No org units are selected: 
Aggregated data is stil loading:

fix: disable data table and download if no aggregations (DHIS2-12475)

---

src/components/download/DownloadDialog.js
src/components/legend/styles/LegendItem.module.css

Fixes: 
https://jira.dhis2.org/browse/DHIS2-12861
https://jira.dhis2.org/browse/DHIS2-12862
This PR fixes issue with the map download style: 
1. Remove padding below legend items to avoid overflow
2. Add 2 px width to map name to avoid text wrap
3. Don't hide map attribution
These style issues are related to limitations of the dom-to-image dependency: https://github.com/tsayen/dom-to-image
Before:

fix: improved map download style (DHIS2-12861, DHIS2-12862) 

---

package.json
yarn.lock

Fixes for DHIS2 Maps: https://jira.dhis2.org/browse/DHIS2-13015
This PR upgrades to version @dhis2/analytics to version 21.5.2 including this fix:
https://github.com/dhis2/analytics/pull/1196
We already show the translated name on the map.

fix: upgrade @dhis2/analytics to filter on displayName (DHIS2-13015)

---

package.json
yarn.lock

Fixes for DHIS2 Maps 2.38.0: https://jira.dhis2.org/browse/DHIS2-13015
This PR upgrades to version @dhis2/analytics to version 21.5.2 including this fix: 
https://github.com/dhis2/analytics/pull/1196

fix: upgrade @dhis2/analytics to filter on displayName (DHIS2-13015, 2.38.0 backport)

---

src/loaders/orgUnitLoader.js

Fixes: https://jira.dhis2.org/browse/DHIS2-12504
This PR avoids and infinitive loading spinner when the backend api reports an invalid org unit selection.
After this PR we will show the error message from the backend and the user is able to change the layer settings:

fix: show error when org unit selection is invalid for org unit layer (DHIS2-12504)

---

src/components/edit/thematic/CompletedOnlyCheckbox.js
src/components/edit/thematic/ThematicDialog.js

Improves: https://jira.dhis2.org/browse/DHIS2-13095
If the user selects "Data element" or "Reporting rates" as value type for a thematic layer, this PR will make sure that we reset the eventStatus param and the checkbox will be unchecked. If the user switches between value types that supports event data, the value will still be kept.

fix: uncheck completed events only checkbox if value type don't support events

---

src/components/map/MapContainer.js
src/components/map/MapView.js
src/constants/mapControls.js
src/reducers/interpretation.js

This PR contains the following fixes: 
1. resizeCount in MapContainer.js uses current state to increment the counter
2. mapControls in MapView.js is wrapped in a useMemo to avoid triggering a redraw on every render. 
3. Search control is removed from split view maps as it was not working well for multiple synced maps (and it is not important in this context)
4. interpretation.js renames "programs" to "interpretation" which is only cosmetic.

fix: minor fixes

---

package.json
src/components/map/layers/earthEngine/EarthEngineLayer.js
src/components/map/layers/earthEngine/EarthEnginePopup.js
src/components/map/layers/earthEngine/styles/EarthEnginePopup.module.css
src/constants/earthEngine.js
yarn.lock

Fixes for 2.36: https://dhis2.atlassian.net/browse/DHIS2-13689
2.36 backport of https://github.com/dhis2/maps-app/pull/2281
The max height of the popup was set to 240 px to add vertical scroll when several age groups are selected: 
Added @babel/helper-environment-visitor as a dev dependency to avoid this error: 
```
● Test suite failed to run
[BABEL] /Users/mastermaps/DHIS2/maps-app/config/testSetup.js: Cannot find module '@babel/helper-environment-visitor'
```

fix: use tileScale to avoid ee aggregation timeout (DHIS2-13689, 2.36 backport)

---

src/constants/settings.js

This PR will update the Web API version to 2.39.

fix: bump web api version to 39

---

src/constants/settings.js

This PR will update the Web API version to 2.39.1
v39 backport of https://github.com/dhis2/maps-app/pull/2306

fix: bump web api version to 39 (v39 backport)

---

.github/workflows/dhis2-verify-app.yml

Setting DHIS2_BASE_URL globally causes the value from the repository secret to override the value from the instance environment, causing the app to crash. The value from the repository secret DHIS2_BASE_URL was being coded into the build file app.js (e.g. `test.e2e.dhis2.org/analytics-2.37`)

fix: DHIS2_BASE_URL should not be set globally

---

src/components/map/layers/BasemapLayer.js

The recent basemap layer refactor caused a bug in the plugin: basemap isn't visible since the opacity and isVisible properties are missing.
From debug/dev
Before: 
After:

fix: basemap default opacity and isVisible needed since they are not stored in visualization

---

src/components/map/styles/MapContainer.module.css

This PR adds a white background to the canvas when maps are downloaded.
Fixes: https://dhis2.atlassian.net/browse/DHIS2-14291
After this PR:

fix: white background for download maps (DHIS2-14291)

---

src/components/map/styles/MapContainer.module.css

2.39 backport of https://github.com/dhis2/maps-app/pull/2404

fix: white background for download maps (DHIS2-14291 - 2.39 backport)

---

src/components/map/styles/MapContainer.module.css

2.38 backport of https://github.com/dhis2/maps-app/pull/2404

fix: white background for download maps (DHIS2-14291 - 2.38 backport)

---

src/components/map/styles/MapContainer.module.css

2.37 backport of https://github.com/dhis2/maps-app/pull/2404

fix: white background for download maps (DHIS2-14291 - 2.37 backport)

---

src/components/map/styles/MapContainer.module.css

2.36 backport of https://github.com/dhis2/maps-app/pull/2404

fix: white background for download maps (DHIS2-14291 - 2.36 backport)

---

i18n/en.pot
package.json
src/components/app/FileMenu.js
yarn.lock

This PR fixes an issue with the "/" character in map names. 
Partly fixes: https://dhis2.atlassian.net/browse/DHIS2-14436
The fix is similar to: https://github.com/dhis2/analytics/pull/1405 
Before: 
The error message shown when a map is saved without a name is not solved in this PR. This should be solved by:
1. Improve the error message returned from the API (which we currently show), or
2. Make name required for FileMenu in @dhis2/analytics (at least for maps).

fix: special characters in map name

---

src/components/edit/event/EventDialog.js
src/components/program/ProgramStageSelect.js

`variables` are not needed for lazy query as they are passed with `refetch` method.

chore: remove query variables for lazy query

---

src/components/app/FileMenu.js

If map name is not set (undefined) when saving from file menu, it will be set to "Untitled map _date_". The same will happen if the map name is removed under File menu > Rename.  
Fixes: https://dhis2.atlassian.net/browse/DHIS2-14436
After this PR:

fix: untitled map name (DHIS2-14436)

---

src/components/orgunits/OrgUnitData.js

Fixes https://dhis2.atlassian.net/browse/DHIS2-14496
There was an extra call to setItems which set the items to undefined so that the data never displays.

fix: component OrgUnitData should not setItems with value undefined [v39]

---

src/components/orgunits/OrgUnitData.js

Fixes https://dhis2.atlassian.net/browse/DHIS2-14496
There was an extra call to setItems which set the items to undefined so that the data never displays.

fix: component OrgUnitData should not setItems with value undefined [v38]

---

src/components/orgunits/OrgUnitData.js

Fixes https://dhis2.atlassian.net/browse/DHIS2-14496
There was an extra call to setItems which set the items to undefined so that the data never displays.
Before (year 2021):
After (year 2021):

fix: component OrgUnitData should not setItems with value undefined [v37]

---

src/components/map/layers/Alert.js
src/components/map/layers/FacilityLayer.js
src/components/map/layers/Layer.js
src/components/map/layers/earthEngine/EarthEngineLayer.js
src/util/orgUnits.js

This PR will add support for SVG symbols for facility layer, and improve the symbol error handling. 
Fixes: https://dhis2.atlassian.net/browse/DHIS2-14440 (in https://github.com/dhis2/maps-gl/pull/517)
Fixes: https://dhis2.atlassian.net/browse/DHIS2-14438
If one or more symbols are missing, we will still show the remaining symbols on the map. A warning message about the first symbol missing is shown to the user.
The same error handling as we have for Earth Engine layers was reused. Added support for both critical and warning errors. 
Two new methods was added to the Layer class: 
- onError -> if plugin (dashboard) the error will only be in the console, if not it will be handled by the specific layer
- onErrorHidden -> Should be called when the error message is not showing anymore
After …

fix: improved facility symbol handling (DHIS2-14438)

---

src/components/BaseUrlShim.js
src/components/map/layers/TrackedEntityLayer.js
src/util/api.js

apiFetch currently uses d2 to get the baseUrl. This PR is part of removing d2 from maps, which is also good for the migration to platform.
apiFetchWithBaseUrl is a copy of apiFetch except that it uses the passed in baseUrl instead of baseUrl from d2. Eventually both these functions will go away, but for now i wanted to keep them separate since apiFetch is dependent on d2

chore: add shim to provide baseUrl to apiFetch

---

src/components/dataItem/EventDataItemSelect.js
src/hooks/useProgramTrackedEntityAttributes.js

With this PR we will not store program data elements and program tracked entity attributes by program id. This was added when we stored the data in the redux store that would work as a local cache. This is less useful when we load data in the component and in a hook, and I suggest that we only store the data for the program selected.

chore: only keep data for the program selected

---

package.json
yarn.lock

Fixes for 2.39: https://dhis2.atlassian.net/browse/DHIS2-14440
This PR will upgrade to the maps-gl 3.7.0 with SVG symbols support:
https://github.com/dhis2/maps-gl/releases/tag/v3.7.0

fix: maps-gl upgrade with SVG symbols support (DHIS2-14440, 2.39 backport)

---

package.json
yarn.lock

Fixes for master/2.40: https://dhis2.atlassian.net/browse/DHIS2-14440
This PR will upgrade to the maps-gl 3.7.0 with SVG symbols support:
https://github.com/dhis2/maps-gl/releases/tag/v3.7.0

fix: maps-gl upgrade with SVG symbols support (DHIS2-14440)

---

package.json
yarn.lock

Fixes for 2.38: https://dhis2.atlassian.net/browse/DHIS2-14440
This PR will upgrade to the maps-gl 3.7.0 with SVG symbols support:
https://github.com/dhis2/maps-gl/releases/tag/v3.7.0

fix: maps-gl upgrade with SVG symbols support (DHIS2-14440, 2.38 backport)

---

src/components/app/App.js

This PR will switch from redux connect to useDispatch to fire actions. 
Also includes a small fix to restrict having both map id in URL combined with currentAnalyticalObject (to avoid loading both a saved map and an analytical object from data store).

chore: refator app component from redux connect to useDispatch

---

src/components/orgunits/OrgUnitLevelSelect.js

Bug introduced during recent refactorings.
Before:
After:

fix: org unit levels do not have short names

---

i18n/en.pot
src/components/edit/FacilityDialog.js
src/components/edit/earthEngine/EarthEngineDialog.js
src/components/edit/event/EventDialog.js
src/components/edit/orgUnit/OrgUnitDialog.js
src/components/edit/thematic/ThematicDialog.js
src/components/edit/trackedEntity/TrackedEntityDialog.js
src/components/orgunits/AssociatedGeometrySelect.js
src/components/orgunits/OrgUnitSelect.js
src/components/orgunits/styles/OrgUnitSelect.module.css

Instead of overriding the orgUnitWrapper from the analytics lib (and passing in "style"), calculate the needed height based on how many additional selects are present. Removed the `flexRowFlow` class since it doesn't have any effect. 54px and 108px are the heights of 1 or 2 select fields (incl padding, border, margin)

fix: calculate orgunit dimension height rather than passing prop

---

src/components/map/layers/ThematicLayer.js
src/util/geojson.js

The jest test are fragile when refactoring because of the maps-gl dependency in util/geojson. The function depending on maps-gl is only used in the ThematicLayer, so the function is moved to that file instead.

fix: removed maps-gl dependency from util/geojson

---

src/loaders/eventLoader.js

This PR sets the same request page size for all event queries. 
Fixes for 2.39: https://dhis2.atlassian.net/browse/DHIS2-14826
I have tested with the "Inpatient morbidity and mortality" program and checked that we get the same number of events in the data table and in the download (1408).

fix: set page size for all event query requests (DHIS2-14826, 2.39)

---

src/loaders/eventLoader.js

This PR sets the same request page size for all event queries.
Fixes for 2.38: https://dhis2.atlassian.net/browse/DHIS2-14826
I have tested with the "Inpatient morbidity and mortality" program and checked that we get the same number of events in the data table and in the download (1408).

fix: set page size for all event query requests (DHIS2-14826, 2.38)

---

src/loaders/eventLoader.js

This PR sets the same request page size for all event queries.
Fixes for 2.37: https://dhis2.atlassian.net/browse/DHIS2-14826
I have tested with the "Inpatient morbidity and mortality" program and checked that we get the same number of events in the data table and in the download (1408).

fix: set page size for all event query requests (DHIS2-14826, 2.37) 

---

package.json
yarn.lock

Fixes for 2.37: https://dhis2.atlassian.net/browse/DHIS2-14440
This PR will upgrade to the maps-gl 3.7.0 with SVG symbols support:
https://github.com/dhis2/maps-gl/releases/tag/v3.7.0

fix: maps-gl upgrade with SVG symbols support (DHIS2-14440, 2.37 backport)

---

package.json
src/components/OrgUnitsProvider.js
src/components/Root.js
src/components/edit/LayerEdit.js
src/components/edit/earthEngine/EarthEngineDialog.js
src/components/edit/event/EventDialog.js
src/components/edit/thematic/ThematicDialog.js
src/components/edit/trackedEntity/TrackedEntityDialog.js
src/components/orgunits/OrgUnitSelect.js

This PR is partly a revert of https://github.com/dhis2/maps-app/pull/2459
In #2459 we set the default org units in the new OrgUnitSelect component. The problem with this approach is the users needs to visit the Org unit tab in the layer dialog before the default value is set. We would like users to create new layers with minimal number of clicks, and in this PR we set the default Org units when the layer dialog is opened (like previously).
A new OrgUnitsProvider component was created to only fetch the default values once. 
Thematic layer with default org unit level selected: 
Earth Engine layer with default org unit level selected: 
Event layer with the org unit root selected:
Tracked entity layer with the org unit root selected:

chore: set default org unit level and roots

---

src/util/favorites.js

This PR will include path for all org unit dimension items to avoid a crash in the org unit modal in DV. 
Fixes: https://dhis2.atlassian.net/browse/DHIS2-14850

fix: include path in org unit dimension items (DHIS2-14850)

---

src/util/favorites.js

This PR will include path for all org unit dimension items to avoid a crash in the org unit modal in DV.
Fixes for 2.39: https://dhis2.atlassian.net/browse/DHIS2-14850
Backport of https://github.com/dhis2/maps-app/pull/2502

fix: include path in org unit dimension items (DHIS2-14850, 2.39 backport)

---

src/util/favorites.js

This PR will include path for all org unit dimension items to avoid a crash in the org unit modal in DV.
Fixes for 2.38: https://dhis2.atlassian.net/browse/DHIS2-14850
Backport of https://github.com/dhis2/maps-app/pull/2502

fix: include path in org unit dimension items (DHIS2-14850, 2.38 backport)

---

src/util/favorites.js

This PR will include path for all org unit dimension items to avoid a crash in the org unit modal in DV.
Fixes for 2.37: https://dhis2.atlassian.net/browse/DHIS2-14850
Backport of https://github.com/dhis2/maps-app/pull/2502

fix: include path in org unit dimension items (DHIS2-14850, 2.37 backport)

---

cypress/elements/file_menu.js
cypress/integration/basemaps.cy.js
cypress/integration/dataDownload.cy.js
cypress/integration/fetcherrors.cy.js
cypress/integration/interpretations.cy.js
cypress/integration/systemsettings.cy.js

Some tests had to be disabled for now:
* dataDownload - tests need to use a regex to find the saved file for the checks
* systemSettings - a race condition is causing the dialogs to be opened before the default relative period has been set
* fetchErrors - due to changing the org unit component, this test needs to be re-written or possibly removed

fix: add robustness to some cypress tests

---

src/components/edit/FacilityDialog.js
src/components/edit/earthEngine/EarthEngineDialog.js
src/components/edit/thematic/ThematicDialog.js
src/util/orgUnits.js

This PR will include `name` when setting the default org unit level. `name` is a required prop for `OrgUnitDimension` component in `@dhis2/analytics`.

fix: include name in default org unit level

---

d2.config.js
package.json
yarn.lock

This will stop all the thousands of pbf files from being downloaded.
Also, other platform dependencies were upgraded to keep consistent versions.
Waiting on this PR:  https://github.com/dhis2/app-platform/pull/793

fix: omit fonts and images from precache

---

src/components/core/styles/Checkbox.module.css
src/components/download/DownloadSettings.js

Info icon alignment:
Legend visibility:
Layers:
Download:

fix: only show legends for visible layers, fix info icon alignment

---

src/components/app/FileMenu.js
src/components/download/DownloadSettings.js
src/reducers/dataTable.js
src/util/dataDownload.js

Fixes: 
1. Download mode is kept when user is downloading a map
2. Close data table if entering download mode
3. Download filename changes: Special characters are removed (not replaced with '_'. Uppercase letters and spaces are kept in the filename. We don't append a random string at the end. Filename examples with or without a map name:

fix: issues found during team testing of 2.40 release

---

src/actions/basemap.js
src/components/app/FileMenu.js
src/components/layers/basemaps/Basemap.js
src/reducers/map.js

This PR will store the basemap config in redux store when a basemap is selected. This config is then available when a user opens a map in the interpretation dialog. 
Before:

fix: store basemap config for interpretation map

---

src/components/download/NorthArrow.js
src/components/map/MapPosition.js
src/components/map/layers/Layer.js

This PR will: 
1. Keep the map rotation when entering/leaving download mode
2. Reset the map rotation to north when a new map is opened/created
3. If the basemap is dark the north arrow will be white:

fix: map rotation and pitch

---

src/components/loaders/LayersLoader.js

This PR avoids an infinite loop when the data table was opened for an event data table with extended data. 
This fix is to always check if the layer is already loading.
After this PR data table show with extended data:

fix: avoid infinite loop when opening event data table

---

src/components/core/DatePicker.js

We have switched to the HTML5 date picker which requires date to be in yyyy-mm-dd format. The dates returned from the API also include the time (2021-01-01T01:00:00.000 2022-10-01T02:00:00.000). This PR will strip the time part before passing the value to the date picker.
After this PR the dates show:

fix: format start/end dates

---

i18n/en.pot
src/components/edit/earthEngine/EarthEngineDialog.js
src/constants/earthEngine.js
src/loaders/earthEngineLoader.js
src/util/earthEngine.js
src/util/favorites.js

With this PR we are using the same Earth Engine dataset for both totalt population and age/gender groups. This makes sure that the totalt population numbers are the same. 
Fixes: https://dhis2.atlassian.net/browse/DHIS2-14282
This means that we only have population values for 2020. 
As we use the same EE dataset for two layers, we couldn't rely to the `datasetId` to be unique, a new `layerId` was therefore added. 
Some code that where included to support old EE layers where removed, as these layers have not been supported for several DHIS2 versions. 
After this PR the total population in Bo is identical to selecting all age/gender groups: 
Before this PR the totalt population in Bo is much less: 
We should also update the Import/Export app to reflect these changes.

fix: new total population layer

---

src/components/edit/earthEngine/EarthEngineDialog.js
src/constants/earthEngine.js
src/loaders/earthEngineLoader.js
src/util/earthEngine.js
src/util/favorites.js

With this PR we are using the same Earth Engine dataset for both totalt population and age/gender groups. This makes sure that the totalt population numbers are the same.
Fixes for v40: https://dhis2.atlassian.net/browse/DHIS2-14282
v40 backport of https://github.com/dhis2/maps-app/pull/2557

fix: new total population layer (DHIS2-14282, 2.40 backport)

---

src/components/edit/earthEngine/EarthEngineDialog.js
src/constants/earthEngine.js
src/loaders/earthEngineLoader.js
src/util/earthEngine.js
src/util/favorites.js

With this PR we are using the same Earth Engine dataset for both totalt population and age/gender groups. This makes sure that the totalt population numbers are the same.
Fixes for v39: https://dhis2.atlassian.net/browse/DHIS2-14282
v39 backport of https://github.com/dhis2/maps-app/pull/2557

fix: new total population layer (DHIS2-14282, 2.39 backport)

---

src/components/edit/earthEngine/EarthEngineDialog.js
src/constants/earthEngine.js
src/loaders/earthEngineLoader.js
src/util/earthEngine.js
src/util/favorites.js

With this PR we are using the same Earth Engine dataset for both totalt population and age/gender groups. This makes sure that the totalt population numbers are the same.
Fixes for v38: https://dhis2.atlassian.net/browse/DHIS2-14282
v38 backport of https://github.com/dhis2/maps-app/pull/2557

fix: new total population layer (DHIS2-14282, 2.38 backport)

---

.github/workflows/dhis2-preview-pr.yml
.github/workflows/dhis2-verify-app.yml
.github/workflows/nightly.yml
cypress/plugins/index.js
cypress/support/getExcludedTags.js
package.json
src/__tests__/cypressGetExcludedTags.spec.js
yarn.lock

BREAKING CHANGE:
- Set to breaking change to trigger version push to 100.0.0
- add cypress tags to allow testing features that are toggled on for versions
- align the PR workflow with DV and LL
- use `dhis2/action-semantic-release@master` action, same as DV and LL
- add the nightly workflow
- add the preview pr workflow

feat: prepare maps-app for continuous release on the app hub

---

src/components/edit/earthEngine/EarthEngineDialog.js
src/constants/earthEngine.js
src/loaders/earthEngineLoader.js
src/util/earthEngine.js
src/util/favorites.js

that the totalt population numbers are the same.
Fixes for v36: https://dhis2.atlassian.net/browse/DHIS2-14282
v36 backport of https://github.com/dhis2/maps-app/pull/2557

fix: new total population layer (DHIS2-14282, 2.36 backport)

---

src/components/edit/earthEngine/EarthEngineDialog.js
src/constants/earthEngine.js
src/loaders/earthEngineLoader.js
src/util/earthEngine.js
src/util/favorites.js

With this PR we are using the same Earth Engine dataset for both totalt population and age/gender groups. This makes sure that the totalt population numbers are the same.
Fixes for v37: https://dhis2.atlassian.net/browse/DHIS2-14282
v37 backport of https://github.com/dhis2/maps-app/pull/2557

fix: new total population layer (DHIS2-14282, 2.37 backport)

---

src/components/edit/event/EventDialog.js

This PR will temporarily remove the fallback coordinate field from the event layer dialog as it is not working properly: https://dhis2.atlassian.net/browse/DHIS2-8165?focusedCommentId=182171
v40 backport of https://github.com/dhis2/maps-app/pull/2575
These issues need to be addressed before we can release the new component.
After this PR the fallback coordinate field is not shown:
Before:

fix: remove fallback coordinate field (DHIS2-8165, v40 backport)

---

package.json
src/PluginWrapper.js
src/util/getPWAInstallationStatus.js
yarn.lock

Pretty much a copy of https://github.com/dhis2/data-visualizer-app/pull/2273
Implements [DHIS2-15097](https://jira.dhis2.org/browse/DHIS2-15097)
Will be paired with a dashboard PR: https://github.com/dhis2/dashboard-app/pull/2285
To help test the "installation" handling locally more easily, you can add these lines to `node_modules/@dhis2/pwa/build/es/service-worker/set-up-service-worker.js`, at the bottom of `setUpServiceWorker()`, before running `yarn start`:
```js
// Prolong installation event
self.addEventListener('install', (event) => {
console.log('installing')
event.waitUntil(new Promise((res) => {
setTimeout(() => res(), 10000)
}))
})
```
---
1. Sends PWA installation status to the parent app to share when it is cached and ready to be served locally
[DHIS2-15097]: …

feat(plugin): send installation status

---

package.json
src/PluginWrapper.js
src/util/getPWAInstallationStatus.js
yarn.lock

Backport of https://github.com/dhis2/maps-app/pull/2580
Sends PWA installation status to the parent app to share when it is cached and ready to be served locally

feat(plugin): send installation status [patch/2.40.0]

---

package.json
src/PluginWrapper.js
src/util/getPWAInstallationStatus.js
yarn.lock

Backport of https://github.com/dhis2/maps-app/pull/2580
Sends PWA installation status to the parent app to share when it is cached and ready to be served locally

feat(plugin): send installation status [v40]

---

package.json
yarn.lock

Implements [LIBS-499](https://jira.dhis2.org/browse/LIBS-499)
[LIBS-499]: https://dhis2.atlassian.net/browse/LIBS-499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: bumps cli-app-scripts to 10.3.8 for LIBS-499 fix

---

package.json
yarn.lock

Implements [LIBS-499](https://jira.dhis2.org/browse/LIBS-499)
Backport of #2592 
[LIBS-499]: https://dhis2.atlassian.net/browse/LIBS-499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: bump cli-app-scripts to 10.3.8 for LIBS-499 fix (v40)

---

package.json
src/PluginWrapper.js
src/components/edit/event/EventDialog.js
src/util/getPWAInstallationStatus.js
yarn.lock

The following 3 commits are in this PR:
* Fixes [DHIS2-15097](https://dhis2.atlassian.net/browse/DHIS2-15097) post installationStatus message from plugin. This is needed by the dashboard to better manage performance effects of loading plugin assets. Without this fix, only the first map on a dashboard will load.
* Fixes [LIBS-499](https://dhis2.atlassian.net/browse/LIBS-499), which can happen when the SW is unavailable (for example private browsing in FF)
* Fixes [DHIS2-8165](https://dhis2.atlassian.net/browse/DHIS2-8165)
These fixes are already in 2.40.0.
[DHIS2-15097]: https://dhis2.atlassian.net/browse/DHIS2-15097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIBS-499]: https://dhis2.atlassian.net/browse/LIBS-499?atlOrigin=eyJpIjoiNWRkNTljN …

fix: post installationStatus message from plugin

---

src/components/edit/thematic/ThematicDialog.js

This PR will make sure that "Display periods" for thematic layer is set to "Single (aggregate)" if a non-relative period is selected. Timeline and split view maps are only supported for relative periods so far.  
Fixes: https://dhis2.atlassian.net/browse/DHIS2-15435

fix: set rendering strategy to single if not relative period (DHIS2-15435)

---

cypress.json

We seem to get random failures pretty regularly and they are often caused by slow instance. This will increase the default timeout for all DOM activity, which I hope will alleviate some of this.

chore: increase cypress default timeout for DOM activity

---

cypress/elements/layer.js

The "add event layer" test continues to be flaky. This change increases the timeout to 50 seconds. Also, since the default timeout is now 15 seconds, the EXTENDED_TIMOUT option isn't needed anymore (since that also sets to 15 seconds)

chore: use 50 second timeout for card title to appear

---

src/components/map/layers/Layer.js

This PR will make sure the layer visibility is kept when the timeline period is changed.
Fixes: https://dhis2.atlassian.net/browse/DHIS2-15439
After this PR:

fix: keep layer visibility when period is changed

---

src/components/download/DownloadSettings.js
src/components/map/MapPosition.js

This PR will hide the north arrow in download mode for split view maps. It will also hide the north arrow position select in the left panel. 
The north arrow is not supported for split view maps. 
Fixes: https://dhis2.atlassian.net/browse/DHIS2-15436
Before:

fix: don't show north arrow for split view maps

---

.github/dependabot.yml

Test this to see if dependabot uses the default branch set in the repo

chore: remove target-branch from dependabot config

---

src/constants/earthEngine.js

Fixes: https://dhis2.atlassian.net/browse/DHIS2-15472
This PR will upgrade to the latest version of the Landcover dataset on Google Earth Engine: 
https://developers.google.com/earth-engine/datasets/catalog/MODIS_061_MCD12Q1
The previous version (https://developers.google.com/earth-engine/datasets/catalog/MODIS_006_MCD12Q1) showed this message: 
The layerId was kept so that saved landcover maps will still work. LayerId is only used internally, datasetId is the is the Earth Engine dataset id. 
After this PR the new landcover dataset is loaded:

fix: upgrade landcover dataset (DHIS2-15472)

---

.github/workflows/nightly.yml

Disable for July as the tests are failing due to slow instances and nobody is around to look into it.

chore: disable nightly scheduled run

---

src/constants/earthEngine.js

2.38 backport of https://github.com/dhis2/maps-app/pull/2732
Fixes for 2.38: https://dhis2.atlassian.net/browse/DHIS2-15472

fix: upgrade landcover dataset (DHIS2-15472, v38 backport)

---

src/components/dataItem/CoordinateField.js
src/components/periods/RenderingStrategy.js
src/hooks/usePrevious.js

This PR will turn RenderingStrategy from a class-based to a functional component. It also creates a new usePrevious hook to access the previous value of a property. The CoordinateField component was updated to use the same hook. 
Both components should work as before as shown in the screen recordings below:

chore: RenderingStategy as functional component and usePrevious hook

---

package.json
yarn.lock

Fixes: https://dhis2.atlassian.net/browse/DHIS2-15793
This PR will make sure DHIS2 Maps get this fix: https://github.com/dhis2/maps-gl/pull/549
After this PR there the no opacity flashing is no longer present:

fix: draw layers with opacity (DHIS2-15793)

---

src/components/dataSets/DataSetsSelect.js

This PR use display name for data sets (reporting rates) based on system / user settings. 
Partly fixes: https://dhis2.atlassian.net/browse/DHIS2-14999
Support for display name for org units and org unit groups are not supported in any of the analytics apps, and need to be implemented for the OrgUnitDimension component in @dhis2/analytics. There are currently no plans to add this support. 
After this PR:

fix: use display name based on system / user setting (DHIS2-14999)

---

cypress/elements/map_canvas.js
cypress/elements/map_context_menu.js
cypress/integration/layers/thematiclayer.cy.js
src/components/core/Radio.js
src/components/map/ContextMenu.js

https://dhis2.atlassian.net/browse/DHIS2-15798 
This PR will remove "Show longitude/latitude" from the context menu for split view maps, as it is not supported. 
After this PR the menu item is removed:

fix: hide "show longitude/latitude" from context menu for split view maps (DHIS2-15798)

---

src/components/program/ProgramIndicatorSelect.js

This PR will use the programIndicators API endpoint to fetch program indicators. This endpoint is respecting the sharing settings for the user. 
After this PR "BCG doses" is not included when "Public access" is set to "No access": 
Before this PR "BCG doses" is included:

fix: use programIndicators endpoint respecting sharing settings

---

cypress/integration/filemenu.cy.js
cypress/integration/smoke.cy.js
src/actions/map.js
src/components/app/FileMenu.js
src/util/apiDataStatistics.js

Fixes one part of https://dhis2.atlassian.net/browse/DHIS2-15800
When a map is opened, saved or save as, then POST a VISUALIZATION_VIEW event. The result is that the count in the Side panel "About this map" will show the correct number of views for the map.

fix: post a data statistics view when map is open or saved

---

i18n/en.pot
src/loaders/eventLoader.js

Improves the error message of: https://dhis2.atlassian.net/browse/DHIS2-13171
This PR will show an error message that the event filter is not supported if the API returns a message that includes "filter is invalid". 
Before this PR the message "You don't have access to this layer data" was shown in this case.

fix: show warning if event filter is not supported

---

src/components/map/layers/EventPopup.js
src/components/map/layers/styles/EventPopup.module.css
src/components/map/styles/Popup.css

Fixes: https://dhis2.atlassian.net/browse/DHIS2-5920
* Adding a `max-width` to the popup results in table cell content wrapping when needed.
* Event popup styles migrated from maps-gl. Styles are still in maps-gl as well so as not to break 2.38 and 2.39.
* Removed unused styles in popup.css
Before:
After:

fix: force table cell content to wrap to prevent overly wide modal

---

.github/workflows/dhis2-verify-app.yml

Be alerted to release success as well as failure in the `analytics-internal-bot` slack channel.

chore: send success message to slack when release succeeds

---

cypress/integration/interpretations.cy.js
cypress/integration/smoke.cy.js
src/components/app/App.js
src/components/app/DetailsPanel.js
src/components/app/__tests__/Detailspanel.spec.js
src/components/app/__tests__/__snapshots__/Detailspanel.spec.js.snap
src/components/interpretations/Interpretations.js

With the changes from the toolbar update, the Interpretations panel might not be loaded by default. So when the url included the interpretationId, no component was listening for it, resulting in the interpretation modal not being opened.  The url param listener is thus moved to App. Tests added

chore: update the toolbar feature commit with a fix for interpretationId url parameter

---

.github/workflows/dhis2-verify-app.yml

Currently messages are being sent to the bot slack channel with every commit to master that successfully completes the 'release' step. But we only want messages on the actual release, and this can be identified by the `chore(release)` in the commit message.

chore: only send bot messages on the actual release commit

---

src/components/orgunits/OrgUnitData.js
src/components/periods/PeriodSelect.js
src/util/__tests__/periods.spec.js
src/util/periods.js

This PR with translate PeriodSelect into a functional component. 
It also adds to additional properties, `firstDate` and `lastDate`,  allowing us to only show periods that are within a date range. These properties will be used in later PRs for Google Earth Engine layers. 
The component still works as before:

chore: fixed period select refactor

---

cypress.config.js
package.json
yarn.lock

Now you will be able to:
- see all the cypress tests merged in one Report portal launch
- find a launch by : 
- PR_TITLE
- BRANCH_NAME
- CI_BUILD_ID
Part of the work was done at the level of : 
- https://github.com/dhis2/agent-js-cypress/commit/d3afea4e74abdbef39c1121f820f23deca2368f4
- https://github.com/dhis2/workflows/pull/46
- https://github.com/dhis2/workflows/pull/47

chore: use reportportal fork

---

.github/workflows/dhis2-verify-app.yml
.github/workflows/nightly.yml
cypress.config.js
cypress/integration/interpretations.cy.js
i18n/ar.po
i18n/cs.po
i18n/es.po
i18n/fr.po
i18n/id.po
i18n/lo.po
i18n/nb.po
i18n/nl.po
i18n/prs.po
i18n/ps.po
i18n/pt.po
i18n/ur.po
i18n/uz_UZ_Cyrl.po
i18n/uz_UZ_Latn.po
i18n/vi.po
i18n/zh.po
i18n/zh_CN.po
jest.config.js
package.json
src/components/layers/download/__tests__/DataDownloadDialogActions.spec.js
src/components/layers/download/__tests__/__snapshots__/DataDownloadDialogActions.spec.js.snap
src/components/loaders/LayersLoader.js
src/components/loaders/__tests__/LayersLoader.spec.js
src/components/loaders/__tests__/__snapshots__/LayersLoader.spec.js.snap
src/util/apiDataStatistics.js
yarn.lock

Fixes:
- 3 transifex PRs
- Analytics [26.0.17 -> 26.2.0](https://github.com/dhis2/analytics/compare/v26.0.17...v26.2.0) upgrade fixes:
- - translations
- - saving map copy: https://dhis2.atlassian.net/browse/DHIS2-15722
- - interpretations timestamps: https://dhis2.atlassian.net/browse/DHIS2-15825,
- - interpretations modal height: https://dhis2.atlassian.net/browse/DHIS2-15558
- - renaming causes error https://dhis2.atlassian.net/browse/DHIS2-16154
Chores:
- report portal configuration

fix: merge to master Dec 20

---

cypress/integration/filemenu.cy.js
cypress/integration/smoke.cy.js
src/actions/map.js
src/components/app/FileMenu.js
src/util/apiDataStatisitcs.js
src/util/requests.js

Backport of https://github.com/dhis2/maps-app/pull/2951 and https://github.com/dhis2/maps-app/pull/3086

fix: record MAP_VIEW statistics when saving and opening maps [v39]

---

src/components/loaders/GeoJsonUrlLoader.js
src/loaders/geoJsonUrlLoader.js

In production, the baseUrl is ".." and therefore the comparison will always be false.
So check the instanceBaseUrl instead
Also, a failed response from fetch, like 400, will return !response.ok,
so that situation needed to be handled as well.

fix: check full instanceUrl and handle not response.ok

---

src/components/layers/overlays/OverlayCard.js
src/components/loaders/GeoJsonUrlLoader.js
src/loaders/geoJsonUrlLoader.js

the building footprints earth engine layer has a property named `error`. That was getting picked up by the new notice box in the Card that was added to report geojson loading errors. Solution was to rename the error property in geojsonloader to `loadError`.

fix: Building footprints earth engine layer was showing an error even though there was no error

---

cypress/integration/layers/geojsonlayer.cy.js
i18n/en.pot
src/components/core/NumberField.js
src/components/core/Tabs.js
src/components/datatable/useTableData.js
src/components/edit/shared/FeatureStyle.js
src/components/layers/overlays/OverlayCard.js
src/components/legend/LegendItem.js
src/components/loaders/GeoJsonUrlLoader.js
src/components/map/layers/GeoJsonLayer.js
src/loaders/geoJsonUrlLoader.js
src/util/__tests__/geojson.spec.js
src/util/geojson.js

1. Limit stroke width to 0-10
2. Tab length should only take the space of the tab title
3. Switching from invalid to valid layer when data table is open should update the table
https://github.com/dhis2/maps-app/assets/6113918/1389f0c7-b8f8-43a3-ad31-ad6422d86fe5
4. Highlight features when data table has a filter
https://github.com/dhis2/maps-app/assets/6113918/7b35606d-c727-43d4-b0e6-592442e5bd37
5. Improve legend for geojson layers
6. Map should show correct point radius for points
25px (green point):
5px (green point):
7. Set max line weight in legend to 5
Before:
After:
More understandable error messages. Discussed with Joe and we agreed to always output the same simple message. The administrator can then investigate by checking the network tab and learning more about the actual error.

fix: various fixes after release testing

---

package.json
yarn.lock

Fixes https://dhis2.atlassian.net/browse/DHIS2-16392
The upgrade of analytics from 26.3.0 to 26.6.0 fixes the flashing/re-rendering of the interpretations panel and thread in modal when liking and unliking an interpretation.

fix: upgrade analytics with fix for flashing interpretation panel and thread [DHIS2-15825]

---

package.json
yarn.lock

Fixes https://dhis2.atlassian.net/browse/DHIS2-16392
The upgrade of analytics from 26.3.0 to 26.6.0 fixes the flashing/re-rendering of the
interpretations panel and thread in modal when liking and unliking an interpretation.

fix: merge to master

---

package.json
src/components/orgunits/OrgUnitSelect.js
yarn.lock

Implements [DHIS2-15000](https://jira.dhis2.org/browse/DHIS2-15000)
**Requires https://github.com/dhis2/analytics/pull/1664**
---
Levels seem to get the translation, nameProperty not needed.
Settings: database language: Norwegian
displayName: shortName
For the OU tree, short names don't work. OULevels don't have short names.
[DHIS2-15000]: https://dhis2.atlassian.net/browse/DHIS2-15000?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: system / user setting for display name not respected in Org Unit tree (DHIS2-15000)

---

.github/dependabot.yml
.github/workflows/dhis2-verify-app.yml
.hooks/pre-commit
package.json
yarn.lock

Four changes:
1. do not run the git verify-app workflow on the 'dev' branch since it is no longer in use
2. configure dependabot to group together deps, reducing number of PRs and workflow runs.
3. add localization strings to commit in the pre-commit hook (this is how LL does it)
4. remove unused dependency and script (platform handles pot extraction)
dhis2 dependencies will still come as separate PRs (like analytics, ui, cli-app-scripts...)

chore: dependabot config and remove dev branch from workflows

---

package.json
src/components/edit/LayerEdit.js
src/components/edit/thematic/ThematicDialog.js
src/components/periods/PeriodSelect.js
src/util/__tests__/app.spec.js
src/util/app.js
src/util/periods.js
yarn.lock

Part of the fix for [DHIS2-16904](https://jira.dhis2.org/browse/DHIS2-16904)
Requires https://github.com/dhis2/analytics/pull/1685
--------------
- bump analytics dependency
- pass periodsSettings to @dhis2/analytics utility function: `getFixedPeriodsOptionsById`
-------------
The actual fix is in @dhis2/multi-calendar-dates which is a dependency of analytics and it's used in the PeriodSelector component the analytics apps use.
See also the PR in analytics.
For maps-app, the locale and calendar specs where not passed to the @dhis2/analytics utility function, so this was implemented as well.
_Note: this has not been implemented for selectors limited to years._
-------------
Translations don't work for week/bi-week:
Pending
Before / After
[DHIS2-16904]: …

fix: support "week", "bi-week" and months in period translations

---

src/components/plugin/MapContainer.js
src/components/plugin/getBasemapConfig.js

Implement [DHIS2-16218](https://dhis2.atlassian.net/browse/DHIS2-16218)
--------------
Pass `basemapVisible` prop to plugin's `getBasemapConfig` function.
-------------
Before:
After:
[DHIS2-16218]: https://dhis2.atlassian.net/browse/DHIS2-16218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: enable hidding basemap in dashboard

---

src/components/map/layers/earthEngine/EarthEngineLayer.js
src/constants/earthEngine.js

The population layers are "constrained" meaning the pixels without a population is removed from the original dataset. When we are calculating the mean population density we get the wrong result as only pixels with a population in taken into account. This PR will fix this issue for 2.39. 
After this PR the mean should take the full org unit area into account:

fix: unmask population layers to get correct mean population density

---

.github/workflows/release.yml

The actions/checkout action defaults to using the reference/SHA commit that triggered the workflow. Since a new commit is pushed (updating package.json and CHANGELOG.md) during the release job, we need to instead get that new commit in order to generate the bot message with the correct version and CHANGELOG info.

chore: checkout the latest commit to use for the bot message

---

src/loaders/earthEngineLoader.js
src/util/__tests__/pluginHelper.spec.js
src/util/pluginHelper.js

Maps plugin is crashing in the dasboard for EE maps due to a missing `filters` prop.  It also fixes issues with backward compatibility issues with older maps with EE layers. 
With this fix EE layers load on Dashboard: 
Thematic layers added to the same map respects the dashboard filters:

fix: plugin crashes for Earth Engine layers in the dashboard

---

.github/workflows/release.yml
.releaserc

There are 2 main improvements to the workflow to help solve all the failing builds:
* Instead of complex if statements in the gh workflow file (they aren't even working anyway!), use commit_analyzer config to prevent release for our [skip release] and [skip ci] PRs.
* publishing to AppHub fails if there is no build file, which there won't be in the case of chores and [skip release]. So add an if statement that checks for an env var. The env var gets set to true if there is a build.
Here's some workflow outputs that demonstrate the above changes in a test repo:
`build_exists` has been set to true and Publish AppHub runs: https://github.com/jenniferarnesen/dhis2-ci-demo/actions/runs/11667460947/job/32484827377
Skip publishing to App hub when [skip release] (even when the commit was a fix or …

chore: only push to AppHub if build was created

---

cypress/elements/layer.js
cypress/integration/layers/geojsonlayer.cy.js
cypress/integration/layers/thematiclayer.cy.js
src/components/layers/LayerCard.js
src/components/layers/toolbar/LayerToolbar.js
src/components/layers/toolbar/LayerToolbarMoreMenu.js
src/components/layers/toolbar/__tests__/LayerToolbar.spec.js
src/components/layers/toolbar/__tests__/LayerToolbarMoreMenu.spec.js
src/components/layers/toolbar/__tests__/__snapshots__/LayerToolbar.spec.js.snap
src/loaders/thematicLoader.js
yarn.lock

Fixes [DHIS2-18157](https://dhis2.atlassian.net/browse/DHIS2-18157)
If a user configures an invalid layer, it should be possible for them to edit it. For geojson url layers this isn't useful since there's nothing the user can do to fix an invalid geojson url layer. But for thematic layers, the user should be able to fix whatever is wrong most of the time
Checklist
-  [x] Dashboard tested
-  [x] Cypress tests added
-  [x] Manual testing complete
[DHIS2-18157]: https://dhis2.atlassian.net/browse/DHIS2-18157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Here's what an invalid map looks like in dashboard (hovering over the legend key button)
In maps app with the edit button enabled now

fix: allow editing invalid layers

---

cypress/elements/thematic_layer.js
cypress/integration/layers/thematiclayer.cy.js
package.json
src/components/map/layers/ThematicLayer.js
src/util/labels.js
yarn.lock

Implement [DHIS2-18427](https://dhis2.atlassian.net/browse/DHIS2-18427)
Linked maps-gl PR: https://github.com/dhis2/maps-gl/pull/596
Backport to v39 PR: https://github.com/dhis2/maps-app/pull/3415
---
- Bump maps-gl dependency to get fix on tooltip 'No data' logic and labelSource to support labelNoData for "name and value" and "value" labels.
- Update getLabelStyle to return labelNoData for labelSource in maps-gl: https://github.com/dhis2/maps-app/blob/cf9cd47dc0e998b4ced68c7c4345fd06035e44aa/src/util/labels.js#L16-L23
- Update pop-up 'No data' logic: https://github.com/dhis2/maps-app/blob/cf9cd47dc0e998b4ced68c7c4345fd06035e44aa/src/components/map/layers/ThematicLayer.js#L182
---
Checklist:
---
Before:
After:
[DHIS2-18427]: https://dhis2.atlassian.net/browse/DHIS2-18427?atlOrigin=eyJpIjoi …

fix: update 'No data' handling

---

package.json
src/components/map/layers/ThematicLayer.js
src/util/labels.js
yarn.lock

Implement [DHIS2-18427](https://dhis2.atlassian.net/browse/DHIS2-18427)
Linked maps-gl PR: https://github.com/dhis2/maps-gl/pull/596
Backport of PR: https://github.com/dhis2/maps-app/pull/3408
---
_Note `??` cannot be used with version of eslint (https://github.com/babel/babel-eslint/issues/611), using `value !== null && value !== undefined ? ... : ...` instead._
---
Checklist:
---
Before:
After:
[DHIS2-18427]: https://dhis2.atlassian.net/browse/DHIS2-18427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: update 'No data' handling [v39]

---

.github/workflows/release.yml
cypress/integration/layers/thematiclayer.cy.js

Setting environment variables doesn't persist between jobs, so use output instead to record whether a build was successful.
Also fixed a test that started to fail when "This month" became December rather than November. Choosing fixed dates should fix this problem.

chore: report release job of release workflow needs output from the release job

---

src/components/map/Map.js
src/components/map/layers/ThematicLayer.js
src/components/periods/Timeline.js

Implement: [DHIS2-18985](https://dhis2.atlassian.net/browse/DHIS2-18985)
---
Timeline component to recieve and use `resizeCount` from parent to trigger resize instead of getting `ui.layersPanelOpen` and  `ui.rightPanelOpen` from redux store (not available in plugin).
---
Before:
After:
[DHIS2-18985]: https://dhis2.atlassian.net/browse/DHIS2-18985?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Timeline not showning in dashboard

---

.github/pull_request_template.md
.prettierrc.js

The task list checker requires only a single space between the hyphen and the opening bracket of a task

chore: use PR task list format recognized by gh action task list checker

---

cypress/integration/pushAnalytics.cy.js

Implements [DHIS2-19123](https://dhis2.atlassian.net/browse/DHIS2-19123)
Similar to https://github.com/dhis2/line-listing-app/pull/655 and https://github.com/dhis2/data-visualizer-app/pull/3356.
The push analytics service uses Puppeteer to generate a map-artefact using the steps outlined in the `push-analytics.json`. This test is a contract test of sorts: when a change in the codebase causes this test to start failing, it is a sign that the instructions in `push-analytics.json` need to be updated, and possibly the push-analytics service itself as well.
[DHIS2-19123]: https://dhis2.atlassian.net/browse/DHIS2-19123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add e2e test to assert push-analytics prerequisites [DHIS2-19123]

---

src/components/edit/event/EventDialog.js

Implements [DHIS2-19204](https://dhis2.atlassian.net/browse/DHIS2-19204)
---
Set default values for start/end dates backup to be restored when switching. 
[DHIS2-19204]: https://dhis2.atlassian.net/browse/DHIS2-19204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: prevent app crash when switching event layer to start/end dates [DHIS2-19204]

---

src/components/map/layers/ThematicLayer.js

Implements [DHIS2-19008](https://dhis2.atlassian.net/browse/DHIS2-19008)
---
In thematicLayer, `onPeriodChange` if a popup is opened, update the `popup.feature.properties` state to get and display the updated value.
---
[DHIS2-19008]: https://dhis2.atlassian.net/browse/DHIS2-19008?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: update value in popup with period change in timeline [DHIS2-19008]

---

cypress/elements/map_canvas.js
cypress/integration/dataTable.cy.js
cypress/integration/mapDownload.cy.js
src/components/app/App.css
src/components/app/styles/App.module.css
src/components/datatable/BottomPanel.js
src/components/download/DownloadMenubar.js
src/components/download/styles/DownloadMenubar.module.css
src/components/map/MapPosition.js
src/components/map/styles/MapPosition.module.css
src/constants/layout.js
src/util/helpers.js
src/util/setHeaderbarVisible.js

Implements [DHIS2-19279](https://dhis2.atlassian.net/browse/DHIS2-19279)
---
- Detect if header is in global shell or same iframe and hide accordingly when in download mode.
- Streamline the use of css variables / constants to represent: 
- toolbar height (`--toolbar-height`)
- download mode header height (`--downloadheader-height`)
---
Entering download mode:
Leaving download mode:
[DHIS2-19279]: https://dhis2.atlassian.net/browse/DHIS2-19279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: header bar visibility issues in download mode [DHIS2-19279] [DHIS2-19279]

---

src/components/map/layers/EventPopup.js

Implements [DHIS2-18851](https://dhis2.atlassian.net/browse/DHIS2-18851)
---
Properly handle display "Not set" for missing values in event popup.
Backport bug fixes introduced with https://github.com/dhis2/maps-app/pull/3346 and https://github.com/dhis2/maps-app/pull/3407
---
[DHIS2-18851]: https://dhis2.atlassian.net/browse/DHIS2-18851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-15796]: https://dhis2.atlassian.net/browse/DHIS2-15796?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: replace empty values with 'Not set' in EventPopup [DHIS2-18851] [v39]

---

src/loaders/thematicLoader.js
src/loaders/trackedEntityLoader.js
src/util/__tests__/time.spec.js
src/util/event.js
src/util/time.js

Implements [DHIS2-19224](https://dhis2.atlassian.net/browse/DHIS2-19224)
Trim dates to yyyy-mm-dd in Evt and TE loaders requests with utility function.
Use new utility fonction in Thematic loader as well.
Layers dates are configured as simple dates (YYYY-MM-DD) but stored as date-time (YYYY-MM-DDT00:00:00) in the database which was causing a discrepancy between end dates in analytics requests when configured vs when opening a saved map.
---
---
[DHIS2-19224]: https://dhis2.atlassian.net/browse/DHIS2-19224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
1. Add new tracked entity layer:
2. Save the map.
3. Open the map.
The events should remain visible after opening the saved map.
Saved map: …

fix: prevent TE layer from becoming exclusive of last day on save [DHIS2-19224]

---

src/components/map/layers/Layer.js

Implements [DHIS2-19522](https://dhis2.atlassian.net/browse/DHIS2-19522)
Before layers get edited use all layers in map to fit bounds.
Preserve the behavior to zoom on the layer that has just been edited/added. 
---
---
[DHIS2-19522]: https://dhis2.atlassian.net/browse/DHIS2-19522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
1. Save a map with a couple or more layers showing data for different districts.
2. Open the map.
All layers should be entirely visible.
Saved map: https://dev.im.dhis2.org/maps-app-test/apps/maps#/D1mQ7gCmD5l
Build: [maps-DHIS2-19522.zip](https://github.com/user-attachments/files/19911155/maps-DHIS2-19522.zip)

fix: use all layers in map to fit bounds on initial render [DHIS2-19522]

---

cypress/support/e2e.js
cypress/support/util.js

Implements [DHIS2-19491](https://dhis2.atlassian.net/browse/DHIS2-19491)
Retrieve full version of dhis2 instance from `api/system/info?fields=version` and store in Cypress env variable `dhis2InstanceFullVersion`.
Give easy access via utility function `getDhis2Version`.
---
[DHIS2-19491]: https://dhis2.atlassian.net/browse/DHIS2-19491?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: get full version from dhis2 instance in cypress [DHIS2-19491]

---

.github/workflows/verify-pr.yml

Implements [DHIS2-19609](hhttps://dhis2.atlassian.net/browse/DHIS2-19609)
[DHIS2-19609]: https://dhis2.atlassian.net/browse/DHIS2-19609?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: use anly-e2e-4x format for cypress test instances

---

cypress/integration/dataTable.cy.js
src/components/datatable/__tests__/useTableData.spec.jsx
src/components/datatable/useTableData.js

Implements [DHIS2-19267](https://dhis2.atlassian.net/browse/DHIS2-19267)
Ensure values are  not undefined before sorting them. Undefined values are put at the bottom of the table.
---
---
[DHIS2-19267]: https://dhis2.atlassian.net/browse/DHIS2-19267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: data table crashes on columns containing empty values [DHIS2-19267]

---

cypress/integration/requestsErrors.cy.js
cypress/support/generateTestMatrix.js
src/components/app/useLoadDataStore.js

The version of `requestsErrors.cy.js` in this PR consistently passes on v40 and v42 but fails on v41.
In this test, the most reliable approach seems to be clearing the browser cache between each step in order to assess request failures independently. This also requires re-logging in.
The failures on v41 appear to be related to the login step:
To properly address this issue, we would likely need to understand the differences in the login process across backend versions.
**At the moment, the time required to investigate these failures seems to outweigh the benefits of maintaining this test. This is especially true since our current approach to handling such errors is inconsistent—or in some cases, missing entirely. I will just deactivate `requestsErrors.cy.js` for now.**
As part of the …

chore: deactivate requestsErrors.cy.js
